### ISSUE TITLE
Add support for Proxy Headers

### ISSUE THREAD

**Issue by keegangroth** [lostisland/faraday#1005]
Curl supports a "proxy-header" flag described as follow:

>        --proxy-header <header>
>               (HTTP) Extra header to include in the request when sending HTTP to a proxy. You may  specify
>               any  number of extra headers. This is the equivalent option to -H, --header but is for proxy
>               communication only like in CONNECT requests when you want a  separate  header  sent  to  the
>               proxy to what is sent to the actual remote host.
> 
>               curl  will  make  sure  that each header you add/replace is sent with the proper end-of-line
>               marker, you should thus not add that as a part of the header content: do not add newlines or
>               carriage returns, they will only mess things up for you.
> 
>               Headers specified with this option will not be included in requests that curl knows will not
>               be sent to a proxy.
> 
>               This option can be used multiple times to add/replace/remove multiple headers.

There does not appear to be any way to replicate this behavior in faradary. [ProxyOptions](https://github.com/lostisland/faraday/blob/bd322bba6b522e2ad28cad585f3c7227b5e2e2a6/lib/faraday/options/proxy_options.rb#L4) supports only uri, user, and password. Empirically, it also does not seem to work to do (for example) `faraday_connection.headers['Some-Proxy-Header'] = 'my_value'` before the request.

**Comment by iMacTia** [comment]
Hi @keegangroth, unfortunately Faraday doesn't implement low-level http communication and instead relies on [adapters](https://lostisland.github.io/faraday/adapters/) to perform HTTP requests. The only way to send this kind of headers, is to use an adapter that supports them. Since you're talking about cURL, there's a very high chance that the [`Patron`](https://lostisland.github.io/faraday/adapters/patron) adapter will be able to do so, but since I haven't used it before I can't tell for sure.

Please let me know if the above helped

**Comment by keegangroth** [comment]
Sorry for the delayed response. I happen to be using httpclient and I did work out how to do this. You're correct that it requires some form of support at the adapter level and it's not obvious to me that httpclient in intentionally supports this. I guess the easiest parallel to draw is proxy authentication support: clearly the adapters have to have a way to do this but faraday also handles it so that there's a common interface. Anyways, here's how I did it with httpclient:

```
# httpclient request filter to add headers to a proxy CONNECT request.
#
# See https://github.com/nahi/httpclient/blob/27fbb07685930d1c8dbdc8dd1e72027f79879bbe/lib/httpclient/session.rb#L644-L648
# and the links for #filter_request for the existing use of this
# functionality internal to httpclient.
class AddConnectHeaders
  def initialize(headers)
    @headers = headers
  end

  # see https://github.com/nahi/httpclient/blob/27fbb07685930d1c8dbdc8dd1e72027f79879bbe/lib/httpclient/auth.rb#L183-L185
  def filter_request(req)
    # only modify CONNECT requests, which go to the proxy
    return unless req.header.request_method == 'CONNECT'

    @headers.each do |k, v|
      req.header.set(k, v)
    end
  end

  # see https://github.com/nahi/httpclient/blob/27fbb07685930d1c8dbdc8dd1e72027f79879bbe/lib/httpclient/auth.rb#L202-L204
  def filter_response(req, res)
    # we don't want to modify responses
    nil
  end
end
```

And then you configure the faraday adapter like this

```
faraday.adapter(:httpclient) do |client|
  # request_filter is actually an attr_reader, but since it
  # returns an Array, which is mutable, we can add to it.
  client.request_filter << AddConnectHeaders.new({'Some-Proxy-Header' => 'my_value'})

  # you may or may not need this, some proxies seem to insist
  # on it and httpclient does not seem to do the negotiation part
  #client.protocol_version = 'HTTP/1.1'
end
```

I have not looked into the support in any other adapters.

**Comment by iMacTia** [comment]
Thanks for getting back with a solution for `httpclient`!
I'm sure it will help others trying to achieve the same thing.
As you correctly pointed out, this requires explicit support from the adapter and so it would be hard to factor it in for Faraday.
