### ISSUE TITLE
undefined method `write_timeout'

### ISSUE THREAD

**Issue by DeanDeBlock** [lostisland/faraday#1007]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.6.3

## Issue description
Using the Stripe Ruby gem (https://github.com/stripe/stripe-ruby) with Faraday v0.15.4 gives following error:
`undefined method 'write_timeout=' for #<StubSocket:0x0000563ebf613038 @read_timeout=80`

Rolling back to Faraday v0.13 seems to fix the issue

**Comment by olleolleolle** [comment]
This is a WebMock issue, which is fixed on their master.

Thanks for describing the issue.

https://github.com/bblimke/webmock/commit/f32d3b1c9460f338035a0afa121c10ab68832064
