### ISSUE TITLE
Faraday::ConnectionFailed (Failed to connect to bofur-us-east-1.searchly.com port 9200: Connection refused):

### ISSUE THREAD

**Issue by bumper21** [lostisland/faraday#1012]
** Faraday Version:**
gem 'faraday', '~> 0.13.0'

* Ruby Version:
ruby "2.4.5"

**Other possibly applicable gems.**
gem 'devise',  3.5.6
gem 'searchkick', 3.1.3
gem 'elasticsearch' 7.3.0

## Issue description
On user creation I get the error below. 
ps.
- To avoid confusion my Talent model inherits from User. Talent < User.
- Each User can be either a Talent or a Scout. In this scenario I'm trying to create a Talent. Talent's have TalentProfiles. So below what is happening is it's trying to save Talent first, then trying to save TalentProfile which comes into play via Talent.talent_profile. 
- This was working until I updated the Ruby from Ruby 2.3.0p0 to Ruby 2.4.5 and subsequently upgraded a few gems which I believe I've noted above. 

`Started POST "/account/talents" for ::1 at 2019-08-25 18:37:14 -0700
Processing by App::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wJW9oQf1YqhzcFx/suILeYcpcBDj2MaNAEgTNN8VL/YGoWwbRhRAb9vECfFXxg8aye4cewA8VfDYjjohQc99Mw==", "talent"=>{"first_name"=>"Armando", "last_name"=>"Oliver", "email"=>"qojadodawu@mailinator.net", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "phone_number"=>"+1 (154) 272-5984", "instagram_username"=>"feqybavy", "twitter_username"=>"zuwihox", "facebook_username"=>"pyhyle", "talent_profile_attributes"=>{"birth_date(1i)"=>"2000", "birth_date(2i)"=>"7", "birth_date(3i)"=>"26", "gender"=>"two-spirit", "height"=>"68", "hair_color"=>"e5a845", "eye_color"=>"1763a0", "skin_color"=>"FFEFEB"}}, "account_type"=>"Talent", "commit"=>"sign up"}
   (0.2ms)  BEGIN
  User Exists (0.9ms)  SELECT  1 AS one FROM "users" WHERE ("users"."id" IS NOT NULL) AND "users"."slug" = $1 LIMIT 1  [["slug", "profile"]]
  User Exists (8.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'qojadodawu@mailinator.net' LIMIT 1
   (0.9ms)  SELECT COUNT(*) FROM "users" WHERE "users"."type" IN ('Talent') AND "users"."authentication_token" = $1  [["authentication_token", "Gyz2HnpJ4CVzYUzLtLDS"]]
  Talent Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('Talent') AND "users"."confirmation_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["confirmation_token", "8634b4fbdc134c67cc3471540d00c232787ec87ff6a7859bbfd620837d58e321"]]
  SQL (3.7ms)  INSERT INTO "users" ("type", "email", "encrypted_password", "first_name", "last_name", "phone_number", "instagram_username", "facebook_username", "twitter_username", "slug", "authentication_token", "created_at", "updated_at", "confirmation_token", "confirmation_sent_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id"  [["type", "Talent"], ["email", "qojadodawu@mailinator.net"], ["encrypted_password", "$2a$10$rswlCPH4H4nK1z5vbpvsneYaeFTmCE4ZOgG72TdPJHNELvrht6.ye"], ["first_name", "Armando"], ["last_name", "Oliver"], ["phone_number", "+1 (154) 272-5984"], ["instagram_username", "feqybavy"], ["facebook_username", "pyhyle"], ["twitter_username", "zuwihox"], ["slug", "profile"], ["authentication_token", "Gyz2HnpJ4CVzYUzLtLDS"], ["created_at", "2019-08-26 01:37:14.377165"], ["updated_at", "2019-08-26 01:37:14.377165"], ["confirmation_token", "hxPdyYwoJKJf_2d2eQLZ"], ["confirmation_sent_at", "2019-08-26 01:37:14.491308"]]
  ApiKey Exists (1.5ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."access_token" = $1 LIMIT 1  [["access_token", "87f159232aa521c8391f5c98fb3e8726"]]
  SQL (0.4ms)  INSERT INTO "api_keys" ("user_id", "created_at", "updated_at", "access_token") VALUES ($1, $2, $3, $4) RETURNING "id"  [["user_id", 5200], ["created_at", "2019-08-26 01:37:14.496953"], ["updated_at", "2019-08-26 01:37:14.496953"], ["access_token", "87f159232aa521c8391f5c98fb3e8726"]]
  Rendered devise/mailer/confirmation_instructions.html.erb (0.6ms)

Devise::Mailer#confirmation_instructions: processed outbound mail in 344.8ms

Sent mail to qojadodawu@mailinator.net (24.0ms)
Date: Sun, 25 Aug 2019 18:37:14 -0700
From: do-not-reply@mymode.co
Reply-To: do-not-reply@mymode.co
To: qojadodawu@mailinator.net
Message-ID: <5d6337cad4003_f5c13fe81bc37790379e8@MacBook-Pro-2.local.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome qojadodawu@mailinator.net!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost:3000/account/users/confirmation?confirmation_token=hxPdyYwoJKJf_2d2eQLZ">Confirm my account</a></p>

  SQL (0.6ms)  INSERT INTO "talent_profiles" ("gender", "hair_color", "height", "eye_color", "skin_color", "birth_date", "talent_id", "age", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["gender", "two-spirit"], ["hair_color", "e5a845"], ["height", 68.0], ["eye_color", "1763a0"], ["skin_color", "FFEFEB"], ["birth_date", "2000-07-26"], ["talent_id", 5200], ["age", 19], ["created_at", "2019-08-26 01:37:14.887658"], ["updated_at", "2019-08-26 01:37:14.887658"]]
source=rack-timeout id=7b37ba4173c090c749f593380609d385 timeout=30000ms service=1004ms state=active
  TalentProfile Store (686.0ms)  {"id":5033,"exception":["Faraday::ConnectionFailed","Failed to connect to bofur-us-east-1.searchly.com port 9200: Connection refused"]}
   (0.4ms)  ROLLBACK
Completed 500 Internal Server Error in 1377ms (Searchkick: 686.0ms | ActiveRecord: 19.1ms)

Faraday::ConnectionFailed (Failed to connect to bofur-us-east-1.searchly.com port 9200: Connection refused):
  app/controllers/app/registrations_controller.rb:73:in `create'`

## Steps to reproduce
Honestly I'm not sure how to reproduce this. I think it has to do with the incompatibility between the upgraded gems but I've been wracking my brain for a solid week trying to figure out where the issue is happening.

The original error I was getting was...
`Searchkick::ImportError (IndexMissingException[[d01a215d-6c60-4a0c-842b-783532cc2a41_talent_profiles_development] missing]):
  app/models/user.rb:100:in `regenerate_slug'
  app/controllers/app/registrations_controller.rb:71:in `create'`

However after upgrading elasticsearch I started getting the error I'm asking help for. 

**Any help at all would be great. Wish I could link to the code base but it's a contract so I'm not able to show the entire project.**

**Comment by iMacTia** [comment]
Hi and thanks for the amount of details provided. According to the error message, this seems like a networking issue:

> Faraday::ConnectionFailed (Failed to connect to bofur-us-east-1.searchly.com port 9200: Connection refused)

As the error message says, your server where the code is running couldn’t connect to bofur-us-east-1.searchly.com:9200. 

Please ensure you can curl that URL from the server. If curl works fine then we can take it from there so please let us know how it goes!

**Comment by iMacTia** [comment]
Thanks for letting us know!
