### ISSUE TITLE
Streaming example - 'undefined method `on_data=`'

### ISSUE THREAD

**Issue by yowzadave** [lostisland/faraday#1025]
Haven't been able to replicate the streaming example presented here:

https://lostisland.github.io/faraday/usage/streaming

I get a `NoMethodError`:

```
undefined method `on_data=' for #<Faraday::RequestOptions (empty)>
```

**Comment by technoweenie** [comment]
What version of Faraday are you using?

**Comment by yowzadave** [comment]
Looks like I'm on `0.15.2` — perhaps I just need to upgrade to the latest?

**Comment by technoweenie** [comment]
Yes, try that :) 

https://github.com/lostisland/faraday/blob/8ba0797af97ae048213b5fc0837b7bf4febefa76/lib/faraday/options.rb#L204-L205

I didn't realize that feature was so new. I'll have to make a note if that in the docs page.

**Comment by yowzadave** [comment]
It looks like it's missing in `0.15.4` as well—it requires the pre-release 1.0. Any reason I should hesitate to upgrade to the 1.0 version?

**Comment by iMacTia** [comment]
@yowzadave 1.0 is mostly (if not fully) backwards-compatible with 0.15.x. Especially if you're working on a new application I'd say going with that is the best choice 😃. If you're upgrading a live system it's still doable but you may want to test thoroughly.

@technoweenie you mentioned the release of a v0.16.0 as well, would that take all changes from master in that case, including the streaming?

**Comment by technoweenie** [comment]
Dang, it's even newer than I thought! I can cut a v0.16.0 release next week, which will include everything in master up til now. 

@yowzadave You can install v1.0-rc1 to try it now with `gem install faraday --prerelease`. It's going to be super embarrassing if _that_ doesn't work. Bring it on :)
