### ISSUE TITLE
v0.16.0 contains breaking changes from 1.0.RC-1

### ISSUE THREAD

**Issue by rlafferty** [lostisland/faraday#1031]
## Basic Info

* Faraday Version: 0.16.0
* Ruby Version: 2.6.X

## Issue description
RC-1 changes the [namespacing on errors](https://github.com/lostisland/faraday/blob/v1.0-rc1/UPGRADING.md#errors).  These changes have been included in the release of 0.16.0, this is a backwards incompatible change, is it expected in this version or should it be held until 1.0.0?

## Steps to reproduce
```
[1] pry(main)> require 'faraday'
=> true
[2] pry(main)> Faraday::Error::RetriableResponse.new('oh noes')
NameError: uninitialized constant Faraday::Error::RetriableResponse
Did you mean?  Faraday::RetriableResponse
from (pry):2:in `__pry__'
[3] pry(main)> Faraday::RetriableResponse.new('oh noes')
=> #<Faraday::RetriableResponse #<Faraday::RetriableResponse: oh noes>>
```

**Comment by rlafferty** [comment]
Seems https://github.com/lostisland/faraday/pull/1030 may address this

**Comment by stuyam** [comment]
Yeah it seems to be a breaking change for a dependency that Octokit uses and is breaking Octokit: https://github.com/octokit/octokit.rb/issues/1155

**Comment by technoweenie** [comment]
Thanks for the report. If #1030 is good, we should be able to roll out v0.16.1 soon.

**Comment by rlafferty** [comment]
> Thanks for the report. If #1030 is good, we should be able to roll out v0.16.1 soon.

Thanks for the super quick turn around @technoweenie !! 🎉
