### ISSUE TITLE
Faraday::Logging::Formatter get removed in v0.17.0

### ISSUE THREAD

**Issue by leomao10** [lostisland/faraday#1060]
## Basic Info

* Faraday Version: v0.17.0
* Ruby Version: 2.4.3/2.5.3

## Issue description
In our project, we customize our log formatter with Faraday::Logging::Formatter according to the readme suggested. But when I `bundle update faraday` from 0.16.2 to 0.17.0, I got error saying Faraday::Logging::Formatter is not existed. And checking the 0.17.0 tag in github repo would show that the formatter is not existed.

Also, the code in master still got the log formatter, wondering if it is something wrong when cutting the 0.17.0.

## Steps to reproduce
- add this line in Gemfile: `gem 'faraday', '~> 0.17.0'`
- `bundle update faraday`
- try to require the log formatter like this: `require 'faraday/logging/formatter'`

**Comment by technoweenie** [comment]
Sorry, the 0.16.x line had to be reverted due to [some major issues](https://github.com/lostisland/faraday/releases/tag/v0.17.0). It will be available on v1.0, which you can try an early build through  [v1.0.0.pre.rc1](https://github.com/lostisland/faraday/releases/tag/v1.0-rc1).

**Comment by leomao10** [comment]
Took me sometime to make 0.16.2 work 😂 Will definitely try `v1.0.0.pre.rc1`

Thanks for the information
