### ISSUE TITLE
Life cycle for adapters

### ISSUE THREAD

**Issue by ioquatix** [lostisland/faraday#1067]
We are exploring how to improve persistence in https://github.com/socketry/async-http-faraday/issues/7

But I don't see `Adatper#close`. There should be some way to close persistent connections.

Just looking to get more information about how this should work.

**Comment by iMacTia** [comment]
Hi @ioquatix that's a good question and not the first time it has been asked!
I'd close this issue in favour of the older #241 where we already discussed about it a bit.

I'm not aware of any resistance from the core team about such a feature, but we are focusing on other features for v1.0 at the moment and I think the current rack-inspired implementation would make this a little harder to achieve.

We'd be more than happy to review a PR about it though, as far as it covers as many adapters as possible (if not all of them)
