### ISSUE TITLE
#get is not thread safe

### ISSUE THREAD

**Issue by ioquatix** [lostisland/faraday#1068]
https://github.com/lostisland/faraday/blob/d5eaa4ffe04b1cba00691b1cc2b2541e91093bf1/lib/faraday/adapter_registry.rb#L14-L26

Reading from a hash table while there are updates happening is not thread safe.

**Comment by iMacTia** [comment]
Ah I see what you mean, should we move the `@lock.synchronise` call into `get` instead?
I'm not sure we'd need it in `set` anymore after that?

**Comment by ioquatix** [comment]
You need it in both methods because you are reading and writing to `@constants`. You can't have synchronised access to the same hash table in any sitautions. Read only operations are not safe with simultaneous writes.

**Comment by olleolleolle** [comment]
Alright, I merged a change to wrap the `@constants` in a synchronize.

**Comment by olleolleolle** [comment]
Thanks, @ioquatix for the inspiration!
