### ISSUE TITLE
Adapter's extra options within assignment default_adapter

### ISSUE THREAD

**Issue by aleksb86** [lostisland/faraday#1073]
Hi,

It's seems that missing support adapter extra options within assignment default_adapter. I want to assign default_adapter once (in initialization) and use it in a few connections. Because typhoeus adapter need some extra options (`http_version: :httpv2_0`), I should to add it in each connection, that produces some duplications. It would be great - to assign default_adapter and set its options in the same place.

**Comment by iMacTia** [comment]
Hi @aleksb86, thanks for opening this.

That sounds like a reasonable feature, you'd be looking at something like this:

```ruby
Faraday.default_adapter = :typhoeus
Faraday.default_adapter_options = {...}

conn = Faraday.new(...)
# conn will use default adapter with default options
```

Would this work for you or did you have something different in mind?

**Comment by aleksb86** [comment]
Thanks for fast reply. It is looking great, but not working for me:
```
NoMethodError: undefined method `default_adapter_options=' for #<Faraday::Connection:0x00007fcbd79f6b18>
Did you mean?  default_parallel_manager=
/Users/aleks_overdrive/dev/gettransfer/config/config.rb:97:in `included'
/Users/aleks_overdrive/dev/gettransfer/app.rb:6:in `include'
/Users/aleks_overdrive/dev/gettransfer/app.rb:6:in `<class:Application>'
/Users/aleks_overdrive/dev/gettransfer/app.rb:5:in `<module:GetTransfer>'
/Users/aleks_overdrive/dev/gettransfer/app.rb:3:in `<top (required)>'
/Users/aleks_overdrive/dev/gettransfer/environment.rb:49:in `require'
/Users/aleks_overdrive/dev/gettransfer/environment.rb:49:in `block in <top (required)>'
/Users/aleks_overdrive/dev/gettransfer/environment.rb:52:in `<top (required)>'
config.ru:10:in `require'
config.ru:10:in `block in <main>'
config.ru:in `new'
config.ru:in `<main>'
/Users/aleks_overdrive/dev/gettransfer/Rakefile:390:in `block in <top (required)>'
Tasks: TOP => console
(See full trace by running task with --trace)
```
my current Faraday version: 0.12.2. Maybe update need

**Comment by iMacTia** [comment]
Great, I've labelled it as a new feature so we'll pick it for development at some point.
Since this is not a critical part of the library, we're happy to review a contributor PR if anyone wants to work on it
