### ISSUE TITLE
change log level in the default log formatter

### ISSUE THREAD

**Issue by amrrbakry** [lostisland/faraday#1078]
Hello,

currently, there's no option to specify the log level in the default formatter. I think it would be better if we're able to do that. what do you guys think?

If I implement my own formatter to solve this, will I be able to log the headers/body of the request?

**Comment by iMacTia** [comment]
Hello @amrrbakry,
you're right, the default formatter uses `info` and `debug` log levels and doesn't currently allow you to change that.

We'd be happy to review a PR that adds the possibility to configure that.

You can also implement your own formatter as you said, where you'll have full control of what log level to use. That formatter could inherit from the default one (so you could reuse methods like `apply_filters`) and you can provide it to the logging middleware as an option.

**Comment by amrrbakry** [comment]
Hi @iMacTia,

I'd be happy to help with this. I will try to send a PR as soon as possible :+1:

**Comment by amrrbakry** [comment]
@iMacTia r?

**Comment by iMacTia** [comment]
Fixed in #1079 🎉
