### ISSUE TITLE
Add support for Digest Authentication

### ISSUE THREAD

**Issue by eric** [lostisland/faraday#109]
Here's an implementation of digest authentication for `Net::HTTP`: [net-http-digest_auth](https://github.com/drbrain/net-http-digest_auth/blob/master/lib/net/http/digest_auth.rb)

**Comment by iMacTia** [comment]
Hi @giovannism20, sorry this issue should be closed.

Considering the current direction of taking middleware and adapters OUT of the core Faraday library, I'd suggest to use existing extensions like https://github.com/bhaberer/faraday-digestauth.

We're not looking at adding more middleware into the core Faraday library unless it's widely used.
