### ISSUE TITLE
v1.0 GitHub tag/release

### ISSUE THREAD

**Issue by epistrephein** [lostisland/faraday#1113]
Congratulations on v1.0 of this amazing gem! 🎉🎉

Is it possible to get a GitHub tag and release for this version?
Commit history is not super-clear, but from a quick diff with the gem on rubygems I assumed ff9dc1d1219a1bbdba95a9a4cf5d135b97247ee2 is the commit of v1.0. Is this correct?
Thanks!

**Comment by bastelfreak** [comment]
Hi people. I run into this as well. Which version is supposed to be the newest one, 1.0.0 or 0.17.3?

**Comment by olleolleolle** [comment]
https://github.com/lostisland/faraday/tree/v1.0.0 is now that tagged release - including a GitHub Releases document, which links to the `UPGRADING.md` document.

1.0.0 is the latest release.

Thanks!
