### ISSUE TITLE
Shared default certificate store

### ISSUE THREAD

**Issue by ball-hayden** [lostisland/faraday#1115]
## Basic Info

* Faraday Version: 0.17.3 (also in 1.0.0)
* Ruby Version: ruby 2.6.3p62

## Issue description

When using the default adapter (in my case `:net_http`), a new `OpenSSL::X509::Store` is initialized for each connection.

Each initialized store then loads the default certificates (`set_default_paths` is a misnomer and actually loads certificates into the store - see OpenSSL's `X509_STORE_set_default_paths` documentation).

This results in a `Faraday::Connection` object holding references to a significant (~1MB on my system) amount of memory.

In itself, this isn't too much of a problem, but I'm opening this following on from a downstream issue whereby a pool of connections is causing a memory leak:
https://github.com/Azure/azure-storage-ruby/issues/150

I wonder if a single default certificate store should be shared between all connections that don't specify `cert_store`?

## Steps to reproduce

The problem can be observed by running the following gist with `TIMES` set to a notable number (I tried 100):
https://gist.github.com/ball-hayden/5ab0171ee76cd9b0b256b45f7e631b43

**Comment by iMacTia** [comment]
Hi @ball-hayden, apologies for the slow reply.
Faraday (or the adapter, in this case) tries to help the user initialising a new `OpenSSL::X509::Store` for each connection.

However, it's worth nothing that is the fallback behaviour. As you can see in the code (https://github.com/lostisland/faraday/blob/54c5c2e96c99d1f72aa1adc9d4634b14e52dedbf/lib/faraday/adapter/net_http.rb#L133), there's a guard at the beginning of the method that simply returns the provided store, if any. If no store is provided, THEN the adapter creates a new one.

The solutions then is simply to initialise the store outside and pass it to the connection when initialising it:

```ruby
store = OpenSSL::X509::Store.new
conn1 = Faraday.new(..., ssl: { cert_store: store })
conn2 = Faraday.new(..., ssl: { cert_store: store })
```

This way the same store will be reused and you should not see the increase in memory anymore.
I hope the above helps, so I'm closing this issue. But if that's not the case then please feel free to follow up.

**Comment by ball-hayden** [comment]
Thanks @iMacTia - that makes sense.
