### ISSUE TITLE
Replace EMSynchrony adapter with pure-EventMachine

### ISSUE THREAD

**Issue by mislav** [lostisland/faraday#112]
Working with parallelism got me thinking what's the point of EMSynchrony adapter at all? EMSynchrony is basically EM + Fibers, the point of which is to untagle evented code. But since the adapter code is abstracted from the user of Faraday anyway, I see no point in requiring EMSynchrony and Fibers when we can simply make everything happen in pure EM.

I wrote an experimental [EMHttp adapter](https://github.com/technoweenie/faraday/blob/6dc0726165aea3d23f7269685f802efa8d5af213/lib/faraday/adapter/em_http.rb). If you agree, I would replace the EMSynchrony adapter with this one, since it offers the same features but with less dependencies. There's still some TODO items here, like SSL support and better error callbacks support, but the majority of work is done and the code is less messy than in EMSynchrony adapter.

I have one request for feedback, and that is about errors while using this adapter for parallel requests in synchonous code:

``` rb
require 'faraday'

conn = Faraday.new 'http://127.0.0.1:4567' do |c|
  c.adapter :em_http
end

conn.in_parallel do
  3.times { conn.get }
end
```

These 3 requests will be performed in parallel, but I'm wondering about how to deal with multiple failed requests. In general, we throw exceptions for failed requests because there's no useful response that can be returned to middleware. Now, let's suppose 2 of the above 3 requests fail. There's no question that the parallel manager should raise an exception, but with what message? Should I concatenate the messages of all errors together in a single exception? Right now I only use the first error message in the exception. Maybe this requires making a specialized error class.

Related: #70 #102 #53

**Comment by iMacTia** [comment]
Closing as adapters now live outside of Faraday
