### ISSUE TITLE
[CHORE] Add Faraday awesome website to the GitHub description

### ISSUE THREAD

**Issue by vvo** [lostisland/faraday#1121]
## Basic Info

Hi there, I find the Faraday website great but it's easy to miss its link when you're on the GitHub README. Should we add the link to the website in the GitHub header directly?

Here:
![2020-01-27 20 27 22](https://user-images.githubusercontent.com/123822/73206603-78970980-4143-11ea-9ecc-d249815bcfb5.gif)

**Comment by vvo** [comment]
@olleolleolle do you have the proper rights to do it? otherwise would could do it? thanks!

**Comment by olleolleolle** [comment]
@vvo I went and checked, and heck, I had access so I changed it.

Thanks a LOT for taking note of this.
