### ISSUE TITLE
Encode Spaces in Query Strings as '%20' Instead of '+'

### ISSUE THREAD

**Issue by jeffsawatzky** [lostisland/faraday#1124]
## Issue description
While `+` is supposed to be a valid encoding for spaces in query strings, it seems like it is causing some issues with some servers (namely [Apple's](https://github.com/nhosoya/omniauth-apple/pull/16))

Given that encodeURIComponent encodes spaces as `%20`, and `%20` is what is recommended by [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.1) maybe that could be the default?

Or provide some way to make this configurable?

## Steps to reproduce
See [omniauth-apple](https://github.com/nhosoya/omniauth-apple/pull/16)

**Comment by jeffsawatzky** [comment]
Apples server's actually handle `+` fine. The issue submited to the omniauth-apple repo is a red herring

**Comment by iMacTia** [comment]
Thanks for the update @jeffsawatzky
I'd still appreciate if @karlentwistle wants to wrap-up his PR so we can offer both solution via some sort of configuration

**Comment by technoweenie** [comment]
The url encoder should escape ` ` as `%20` and `+` as `%2B`. It's the best way to be sure the server is interpreting the url correctly, in my experience. I don't think URL readability is an issue here, since Faraday is likely going to be making the request.

**Comment by iMacTia** [comment]
Agree with you @technoweenie, although changing the default escaping for ` ` from `+` to `%20` might bring unexpected results.
I'd feel more comfortable with an option for doing so
