### ISSUE TITLE
Question: is there a way to disconnect keepalived connections?

### ISSUE THREAD

**Issue by miyazakt** [lostisland/faraday#1137]
When using the net_http_persistent adapter, is there a way to disconnect the keepalived connections?
If the CNAME of DNS is changed, the connection is always kept, so the old one will continue to be accessed.

If it's the responsibility of the net-http-persistent rather than the Faraday, I'll ask them there.

**Comment by olleolleolle** [comment]
I think this would be a low-level thing to do via the other gem.

**Comment by iMacTia** [comment]
Hi @miyazakt, I agree with @olleolleolle this should probably be solved in `net_http_persistent` as we don't manage keepalive directly in Faraday, but delegate that to the adapter gems.
