### ISSUE TITLE
Wait until CodeClimate supports SimpleCov 0.18+, then re-add badge & code coverage collection

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#1139]
## Basic Info

* Faraday Version: master
* Ruby Version: 2.6

## Issue description

Our reporting of code coverage to Codeclimate always fails. That's due to them not supporting the 0.18+ format of SimpleCov output (branch coverage etc).

I recognized the error output in the codeclimate reporter's 2nd step: a Go failure to parse the newer SimpleCov format.

```
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-test-reporter after-build [flags]
```

~**Proposal**: Downgrade simplecov to a codeclimate-supported version, and keep a code comment there to remind us of that.~

**Proposal, update**: Disable coverage reporting and badge until Codeclimate supports all of SimpleCov. This Issue can be kept open as a tracking issue for this.

## Steps to reproduce

See this GH Actions failure: https://github.com/lostisland/faraday/runs/543272466?check_suite_focus=true#step:9:8

When CI runs past that step, only in Ruby 2.6 that program is run. Exit code is 255 on failure, and the output looks like the above.

**Comment by olleolleolle** [comment]
Thinking harder about this, I kind of want not to have CodeClimate's Go program hold SimpleCov back. I will opt to remove their coverage badge from the README instead. They can earn it back by supporting SimpleCov 0.18+.

**Comment by olleolleolle** [comment]
With any such removal would come "drop the CI stuff that transmits the coverage data as well".

**Comment by iMacTia** [comment]
Indeed we should not downgrade SimpleCov just because it's not supported by CodeClimate's test-reporter. Agree with disabling the test-reporter until a fix is pushed

**Comment by iMacTia** [comment]
Great news!
https://github.com/codeclimate/test-reporter/issues/413#issuecomment-749542129

**Comment by iMacTia** [comment]
We've removed codeclimate, closing this
