### ISSUE TITLE
Stubbing get and post requests with headers and body

### ISSUE THREAD

**Issue by andrewgwoodruff** [lostisland/faraday#1158]
Hey all! I'm working in a Ruby on Rails environment, and have the latest versions of Faraday and Ruby and Rails. I seem to be running up against a misunderstanding of how the parameters for stubbing get and post requests works in Faraday.

Here's the code in question:

```
let(:stubs) {
      ::Faraday::Adapter::Test::Stubs.new do |stub|
        stub.get("/test-service/v3/accounts",
                 "Authorization" => "Bearer expiredapikey") do |_request|
          [401, { "Content-Type" => "application/json" }, load_response_fixture("expired_or_invalid_token.json")]
        end
        stub.get("/test-service/v3/accounts",
                 "Authorization" => "Bearer access_token_string") do |_request|
          [200, { "Content-Type" => "application/json" }, load_response_fixture("accounts.json")]
        end
        stub.post("/token?grant_type=client_credentials&scope") do |_request|
          [200, { "Content-Type" => "application/json" }, load_response_fixture("token.json")]
        end
      end
    }
```

I want to mock out two separate endpoints for get requests to the path "/test-service/v3/accounts", with the difference being the headers (you see that I've tried to do that above, with different values for the "Authorization" header). But when I run my code as is, I get the following:

```
Failure/Error: super
     
     Faraday::Adapter::Test::Stubs::NotFound:
       no stubbed request for get /test-service/v3/accounts 
```

When I look at the Faraday API, it says that "headers" can be a parameter to the stub.get method, so I'm assuming there's some way to do it, and perhaps I'm not getting everything quite in place the way it should be for Faraday to play ball. Let me know if you have any ideas. :)

Also, if you're feeling adventurous, maybe you could help me understand why this code snippet is preferred over the next one:

```
stub.post("/token?grant_type=client_credentials&scope") do |_request|
          [200, { "Content-Type" => "application/json" }, load_response_fixture("token.json")]
        end
```

^Any ideas why that would be preferred over the next one?

```
stub.post("/token", "grant_type=client_credentials&scope") do |_request|
          [200, { "Content-Type" => "application/json" }, load_response_fixture("token.json")]
        end
```

Again, the API seems to suggest that I can have the body as a separate parameter, but for some reason it doesn't like the second option.

**Comment by andrewgwoodruff** [comment]
Hey all, another guy on my team ended up figuring out the issues. So we're good now. :)

**Comment by hxrxchang** [comment]
@andrewgwoodruff 
> When I look at the Faraday API, it says that "headers" can be a parameter to the stub.get method, so I'm assuming there's some way to do it, and perhaps I'm not getting everything quite in place the way it should be for Faraday to play ball. Let me know if you have any ideas. :)

I am also facing this problem. Could you please tell me how you solved it?

**Comment by hxrxchang** [comment]
Sorry.
This code was used as a reference.
https://github.com/lostisland/faraday/blob/b766d1f848fd3059cf4e9a671c0402f9b852c365/spec/faraday/adapter/test_spec.rb#L130

I fixed my code 
from
```ruby
stub_http_client = Faraday.new do |connection|
  connection.adapter :test, Faraday::Adapter::Test::Stubs.new do |stub|
    stub.get(end_point, {'Authorization' => "Bearer testing_token", 'clientId' => "testing_client_id"}) do
      [200, {}, stub_response.to_json]
    end
  end
end
```
to
```ruby
stub_http_client = Faraday.new do |connection|
  connection.adapter :test, Faraday::Adapter::Test::Stubs.new do |stub|
    stub.get(end_point, 'Authorization' => "Bearer testing_token", 'clientId' => "testing_client_id") do
      [200, {}, stub_response.to_json]
    end
  end
end
```

and it works !
