### ISSUE TITLE
Does faraday support Call timeout?

### ISSUE THREAD

**Issue by venki09** [lostisland/faraday#1161]
## Basic Info

* Faraday Version: 1.X
* Ruby Version: 2.7.X

## Issue description
I would like to configure faraday to have a timeout which is for the entire call, including retries. Example: a callTimeout of 10 seconds means that all retries should complete before 10 seconds. Square's [okhttp](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/call-timeout/) has support for that. Is it currently possible with Faraday?

**Comment by iMacTia** [comment]
Hi @venki09, you can set a timeout using the `request.timeout` connection config.
Please see [this page](https://lostisland.github.io/faraday/usage/customize) on how to set it in different ways and let me know if that answer your question

**Comment by venki09** [comment]
@iMacTia : Thanks. So does that timeout value apply across all retries. For example: If I set timeout to 5 seconds and max retries to 2 using the [retry request middleware](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb#L14), does the timeout kick-in for each retry (resulting in 5+5=10 seconds for the total call) or does the timeout  apply to all retries combined (meaning, both retries has to happen within the 5 second timeout or the total call will result in a timeout)?

**Comment by iMacTia** [comment]
Timeout setting is per-request, that means that each retried request will have the same timeout as per settings.
i.e. If the same request is retried 3 times with a timeout of 5 seconds (and the request times out all 3 times) the total time taken will be 15 seconds.

**Comment by venki09** [comment]
Yes, that's what I would have expected timeout settings to be. Would it be beneficial to have a callTimeout feature like the one OkHttp provides?

**Comment by iMacTia** [comment]
I personally don't think that's a useful use case for a back end gem, sounds more like a mobile app or front end sort of library. That said, we simply pass the timeout setting to the adapter gem, so unless the adapters support something like this, there's no way to do something like that via Faraday itself.

The only other option left, if you think this is something you really need, would be for a custom middleware that raises an error after the timeout has been exhausted. Placing this middleware BEFORE the retry middleware would allow you to have a timeout covering the whole call.

For now, I'm closing this issue as I believe the original question has been answered.
