### ISSUE TITLE
Sample domain in Faraday docs needs to be updated

### ISSUE THREAD

**Issue by mokolabs** [lostisland/faraday#1164]
## Basic Info

* Faraday Version: All
* Ruby Version: All

## Issue description

Faraday docs use `sushi.com` as a sample domain for code examples. However, it appears registration for the domain lapsed at some point, and it was grabbed by a domain name scalper.

As a result, many of the existing code examples either don't work at all or produce divergent output from the docs.

For instance, the very first code example:

> Make a simple GET request by requiring the Faraday gem and using Faraday.get:

```ruby
response = Faraday.get 'http://sushi.com/nigiri/sake.json'
```
> This returns a Faraday::Response object with the response status, headers, and body.

```ruby
response.status
# => 200
```

In fact, this returns a `301` because the new host for the `sushi.com` domain is redirecting http requests to https. If you follow the redirect via Faraday (with the extra required code), you'll eventually get a `404` because `sake.json` no longer exists on the domain.

## Steps to reproduce

See above.

**Comment by iMacTia** [comment]
Thanks @mokolabs for raising this.
Having those examples working is not really too important, they're mostly there for illustration purposes.
That said, I agree with you it would be even better if they actually worked 😃
I used `example.com` in the past but that also looks down at the moment!
Maybe we could use [Postman Echo](https://docs.postman-echo.com/?version=latest), or I'm open to other suggestions.

I'd also be glad if someone from the community would like to pick this up, I'll flag it as a good first issue 👍

**Comment by mokolabs** [comment]
Okay, cool. I can take this one on.

**Comment by gurgeous** [comment]
I use `httpbingo.org` extensively in both docs and tests. It's a go port of the old `httpbin.org` service. Great resource if you haven't seen it before. I even simulate it in my tests with webmock...

**Comment by JAugusto42** [comment]
Hi all, would like to start contributing trying to help with the doc for while, i attach a pull request suggesting an adjustment.

**Comment by olleolleolle** [comment]
@JAugusto42 Cool, thanks for fixing that - does that complete this ticket?

**Comment by JAugusto42** [comment]
I believe so, i'm going to go through the other pages...but i believe that's it.

**Comment by iMacTia** [comment]
There are still [occurrences](https://github.com/lostisland/faraday/search?q=sushi&type=) of `sushi.com` in some docs and even some tests, should we change those as well before closing this?
@JAugusto42 were you planning to open any follow-up PRs?

**Comment by JAugusto42** [comment]
sure i can work on that

**Comment by mokolabs** [comment]
Belatedly... thank you for fixing this, @JAugusto42!
