### ISSUE TITLE
"faraday.response :logger, nil, { headers: false, bodies: true }"  outputs tons of gibberish to console

### ISSUE THREAD

**Issue by la-ruby** [lostisland/faraday#1166]
## Basic Info

* Faraday Version: 0.12.1
* Ruby Version: 2.3.0

## Issue description

The "bodies: true" technique seems to work:

    faraday.response :logger, nil, { headers: false, bodies: true }

except sometimes I see pages and pages of gibberish in the logs:

    I, [2020-07-16T06:00:39.970668 #12650]  INFO -- : get https://api.hubapi.com/contacts/v1/properties
    I, [2020-07-16T06:00:40.363272 #12650]  INFO -- Status: 200
    ?lW?oǒ???Ą"a?m?T?b?jb#??׾?<?"P?KI~TY"????7$???/"<!/~y1???<ʼ??,?#g???!??6h?#n?~?'....

![image](https://user-images.githubusercontent.com/55279023/87674898-81988900-c72b-11ea-9f99-aa6fba14554a.png)

**Comment by iMacTia** [comment]
@la-ruby could it be that what you see is the response body?
Have you tried performing the same request with another tool (e.g. Postman) and if so, do you experience the same issue?
Could you share your connection full setup (all middleware)?

My guess is that the response may be encoded somehow (gzip?) and the logger is put in the wrong place on the middleware stack

**Comment by la-ruby** [comment]
I feel it's the response body im seeing, but i know that it's unencoded form is a json hash,
and the json hash is ideally what I like to see in the logs/

with curl/postman I don't recall having this problem.

    @client ||= Faraday.new(:url => "https://api.hubapi.com") do |faraday|
      faraday.use HubspotMiddleware, :token => @hubspot_site.access_token
      faraday.request :url_encoded
      faraday.use :gzip
      faraday.response :logger, nil, { headers: false, bodies: true }
      faraday.adapter *AppContainer.faraday_default_adapter
    end

**Comment by iMacTia** [comment]
There you go: `faraday.use :gzip`. This middleware parses a gzip response and makes it plain text.
I believe what you see is the response before being uncompressed. cURL/Postman most probably uncompress the response for you automatically, or tell the server they can't accept it, hence why you don't have this issue.

So for your knowledge: while the request is passed through middleware top-down, the response goes in the other direction (see [Middleware](https://lostisland.github.io/faraday/middleware/)).
That means, the response hits your `logger` middleware BEFORE it reaches the `gzip` one.
The solution in your case should then be as simple as swapping these two middleware order: this way the `gzip` middleware will uncompress the response body before it reaches the `logger` one.

```ruby
@client ||= Faraday.new(:url => "https://api.hubapi.com") do |faraday|
  faraday.use HubspotMiddleware, :token => @hubspot_site.access_token
  faraday.request :url_encoded
  faraday.response :logger, nil, { headers: false, bodies: true }
  faraday.use :gzip
  faraday.adapter *AppContainer.faraday_default_adapter
end
```

I hope the above helps and I'd love if you could leave an update once you check this is working for you 😃 
I'll leave this ticket open until then, so feel free to get back in touch if you're still having issues.

**Comment by la-ruby** [comment]
good solution! you can close this issue

by the way how to truncate bodies printed to stdout...

**Comment by iMacTia** [comment]
> by the way how to truncate bodies printed to stdout...

If you mean truncating the body when too long, I'd suggest sub-classing the Faraday logger formatter class: https://github.com/lostisland/faraday/blob/master/lib/faraday/logging/formatter.rb

```ruby
class MyFormatter < Faraday::Logging::Formatter
  # Overrides dump_body to truncate bodies that are too long
  def dump_body(body)
    long_body = super # This returns the body as is from Faraday::Logging::Formatter
    # do something to limit the body size ...
  end
end
```

You can then inject it to your logger middleware as an option (https://github.com/lostisland/faraday/blob/master/lib/faraday/response/logger.rb#L18):

```ruby
@client ||= Faraday.new(:url => "https://api.hubapi.com") do |faraday|
  ...
  faraday.response :logger, nil, { headers: false, bodies: true, formatter: MyFormatter }
  ...
end
```
