### ISSUE TITLE
"f.adapter :net_http_persistent, pool_size: 1  "not use same connction 

### ISSUE THREAD

**Issue by tablecell** [lostisland/faraday#1174]
## Basic Info

* Faraday Version: v1.0.1
* Ruby Version: ruby 2.5.8p224 (2020-03-31 revision 67882) [x64-mingw32]
    connection_pool-2.2.3.
   net-http-persistent-4.0.0.

## Issue description
Please provide a description of the issue you're experiencing.
Please also provide the exception message/stacktrace or any other useful detail.

"f.adapter :net_http_persistent, pool_size: 1  "not use same connection   every request return different thread.current that means 
not same keep alive connection 

## Steps to reproduce
If possible, please provide the steps to reproduce the issue.

theadserver.rb
```C
require "socket"
server = TCPServer.open("127.0.0.1", 80)
loop {
  Thread.start(server.accept) do |client| # new thread  if  conn  accepted
    puts "connected", client
    loop { #for establish cconn  loop gets/write
      lines = []
      while line = client.gets and line !~ /^\s*$/
       lines << line.chomp
      end
      puts lines
      puts Thread.current

      echo = "Your connection  is served  by thread %s" % Thread.current   # echo Thread.current to client
      headers = ["HTTP/1.0 200 OK",
                 "Server: ruby multi thread server",
                 "Content-Type: text/plain; charset=utf-8",
                 "Content-Length: #{echo.length}\r\n\r\n"].join("\r\n")
      puts "%d +  %d  = %d" % [headers.size , echo.size,headers.size + echo.size]
      client.write headers   #send to the client
      client.write echo
      # loop  client gets not close connection
    }
  end
}
```
client.rb
```C
require "faraday"

url = "http://localhost/query"
segs = url.split "/"
base = segs[0..2].join "/"
query = "/query"
conn = nil
10.times do
  if nil == conn
    conn = Faraday.new(url: base) do |f|
      f.adapter :net_http_persistent, pool_size: 1 do |http|
        http.idle_timeout = 100
        #  http.retry_change_requests = true
      end
    end

    puts "new conn ---------------"
  end
  resp = conn.get url
  puts resp.body
  sleep 2
end

```
new conn ---------------
Your conn is serve by thread #<Thread:0x0000000004efff48@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004efe418@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004efcb68@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f07630@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f05f10@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f04a48@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f0f7b8@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f0e278@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f0ce50@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004f17a58@accept-new-thread.rb:4 run>

**Comment by iMacTia** [comment]
Hi @tablecell, thanks for the details above.
I'm not entirely sure the above shows there's an issue with the connection itself.
For example, the server might be closing the connection, forcing `net_http_persistent` to reopen it.

Have you tried writing the client using `net_http_persistent` directly (without using Faraday) and successfully seeing the same server Thread being reused?

**Comment by tablecell** [comment]
@iMacTia 
1 the server  loop  read/write  forever  if  the connection established    , no  closing the connection surely 
2 client using net_http_persistent directly 
```C
require 'net/http/persistent'
# https://www.rubydoc.info/github/carlhuda/bundler/Net/HTTP/Persistent
uri = URI 'http://localhost/query'
http = Net::HTTP::Persistent.new  
10.times do 
        resp = http.request uri
	puts resp.body
	sleep 2
end

```
output is  similar as wrappbed by farady 

Your conn is serve by thread #<Thread:0x0000000004de6530@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004e174a0@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004e27b70@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004e32a70@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004e30338@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004ec25d0@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004ec0fa0@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004eb3d28@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004eb2a40@accept-new-thread.rb:4 run>
Your conn is serve by thread #<Thread:0x0000000004eb12f8@accept-new-thread.rb:4 run>

**Comment by iMacTia** [comment]
Thanks @tablecell, that's exactly what I suspected.
I'm no expert with `Net::HTTP::Persistent`, but Faraday is basically relying on its functionality, so in order to compare what we're doing wrong inside Faraday, I'd need to know what's the correct way to do it with the client itself.
I can see you opened https://github.com/drbrain/net-http-persistent/issues/121 already, which is great 👍
If the `Net::HTTP::Persistent` can point you to the issue with the code above and provide a solution, then I should be able to help on how to integrate that in Faraday 😃 
So for now, I'm afraid we'll have to wait for them to come back to us

**Comment by tablecell** [comment]
@iMacTia 

Server  add headers   'Connection: Keep-Alive' 
'net/http/persistent'  recieve  correct same  Trhead .currrent 

please close the issue

**Comment by iMacTia** [comment]
Thanks for getting back to us!
It will surely help people in future.

Closing
