### ISSUE TITLE
Need help : how can i fetch key and value from response header ?

### ISSUE THREAD

**Issue by shubhamjaincav** [lostisland/faraday#1177]
## i need to fetch custom header key and value from response hearder how fetch?

* Faraday Version: 0.17.0
* Ruby Version: 2.5

**Comment by iMacTia** [comment]
Hi @shubhamjaincav, once you get your `Faraday::Response`, you can simply use `.headers` to see all response headers.
Example below for Google (I'm using the `Faraday.get` shorthand):

```ruby
res = Faraday.get('https://google.co.uk')

res.headers
 => {"location"=>"https://www.google.co.uk/", "content-type"=>"text/html; charset=UTF-8", "date"=>"Tue, 08 Sep 2020 09:12:21 GMT", "expires"=>"Thu, 08 Oct 2020 09:12:21 GMT", "cache-control"=>"public, max-age=2592000", "server"=>"gws", "content-length"=>"222", "x-xss-protection"=>"0", "x-frame-options"=>"SAMEORIGIN"}

res.headers['x-xss-protection']
=> "0"
```

**Comment by shubhamjaincav** [comment]
Hi iMacTia,

i have already used same as mention above, but i am not getting my custom header using faraday 0.17.0 gem.

##response = Faraday.get 'http://localhost:9201'
##puts "response header #{response.headers}"



should i have to use cors rule apply on server level?

**Comment by iMacTia** [comment]
@shubhamjaincav Are you getting back any response at all (i.e. are you sure your server is being reached)? It's interesting that you mention CORS, but this usually doesn't apply against `localhost`. Is that because you see anything suspicious? What about response.body?
