### ISSUE TITLE
Faraday strips new lines from description field when creating CSV

### ISSUE THREAD

**Issue by gister9000** [lostisland/faraday#1178]
## Basic Info

* Faraday Version: v1.0.1
* Ruby Version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

## Issue description
Faraday CSV file strips new lines and stacked whitespaces from description field.

## Steps to reproduce
Write a vulnerability description that contains new lines such as:
![image](https://user-images.githubusercontent.com/55654477/92897029-262e0300-f41d-11ea-9fc7-2482b047a0e5.png)

Once a CSV is downloaded, that description lacks new lines and whitespaces, resulting in one line blob:
![image](https://user-images.githubusercontent.com/55654477/92897148-41007780-f41d-11ea-80a4-b74c3ac0df69.png)

If you agree to change this, I'm willing to make the changes in code myself. If anyone knows where this code is, please point me to it.

**Comment by iMacTia** [comment]
Hi @gister9000, I'm not really sure this is something Faraday does, as it shouldn't mess with the response body. Could you please share the Ruby code you use to make the call and setup your faraday connection so I can have a look?
Also, it would be useful to compare Faraday's behaviour with other standard libraries or cURL, just to ensure that it's not an issue on the server

**Comment by gister9000** [comment]
Sorry, I was meant to post this on infobyte/faraday repo (collaborative pentest faraday). Please delete this
