### ISSUE TITLE
Server Sent Event(a.k.a. SSE)

### ISSUE THREAD

**Issue by thiagotrentin** [lostisland/faraday#1184]
Is there some way to handle server sent events API with Faraday?

**Comment by iMacTia** [comment]
Hi @thiagotrentin, I'm afraid Faraday does not support that out of the box.

I'd also add that Faraday is probably not the right tool for adding this feature either, as SSE require to keep an open connection to the server and are more similar to websockets or the pub/sub patterns, where you usually keep listening on the socket waiting for a new message and then process that message. On the other side, Faraday focuses on facilitating single HTTP calls.

In my opinion, you're far better off using a specific solution for SSE provided by other gems.
A quick Google search returned [ruby-eventsource](https://github.com/launchdarkly/ruby-eventsource) as a possible alternative.
