### ISSUE TITLE
Retry documentation or implementation looks incorrect?

### ISSUE THREAD

**Issue by nbeyer** [lostisland/faraday#1197]
The retry documentation shows [an example](https://github.com/lostisland/faraday/blob/master/docs/middleware/request/retry.md#example-usage), which mentions that the retry delay range for the first retry is between 0.05 and 0.075, and the second retry is between 0.1 and 0.15. The second range is not correct, based on the [current implementation](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb#L227).

The implementation calculates a `current_interval` and a `random_interval`, then adds them. The example uses a configuration with config values of max at 2, backoff_factor at 2, interval at 0.05, and interval_randomness at 0.5. For the first retry, the `current_interval` will be 0.05 (`0.05 * 2 ** 0`) and the `random_interval` will be a maximum of 0.025 (`1 * 0.5 * 0.05`). For the second retry, the `current_interval` will be 0.1 (`0.05 * 2 ** 1`) and the `random_interval` will be a maximum of 0.025 (`1 * 0.5 * 0.05`), again. The `random_interval` calculation never changes -- it always uses the configured interval value, not the calculated interval value. As such, the documented example is incorrect -- the range for the second retry would be 0.1 and 0.125.

I can quickly submit a PR to correct the documentation but wanted to check that it's just the documentation that's incorrect and not the implementation. The documentation seems to indicate that perhaps the algorithm was supposed to calculate the random_interval based on the current_interval.

**Comment by olleolleolle** [comment]
@nbeyer My guess: Probably just the documentation that has not kept up, a PR would be appreciated.

@iMacTia Perhaps you have another view?

**Comment by iMacTia** [comment]
@olleolleolle @nbeyer yep, I can confirm the code has been like that since its introduction 7 years ago!
https://github.com/lostisland/faraday/commit/37bd330979708fc7fe770a00cf46034643748c64

Hence the doc must be wrong 😄
