### ISSUE TITLE
Zlib::DataError on Get request

### ISSUE THREAD

**Issue by scottwater** [lostisland/faraday#120]
I am seeing a couple of urls which when requested result in an error 'Zlib::DataError: unknown compression method'

  /faraday/adapter/net_http.rb:59:in `call'
  /faraday/request/url_encoded.rb:14:in`call'
  /faraday/connection.rb:215:in `run_request'
  /faraday/connection.rb:88:in`get'
  /faraday-a1c2dcf1c5c0/lib/faraday.rb:24:in `method_missing'

Example: 
Faraday.get('http://www.imaginativeuniversal.com/blog/post/2012/02/14/Why-the-Kinect-for-Windows-Sensor-Costs-2424999.aspx')

I have tested on 0.7.6 and 0.8.RC2 on Ruby 1.9.3. 

I also tested HTTParty on the same url and it appear to work...but I have not dug much further. 

Thanks,
Scott

**Comment by lacostenycoder** [comment]
@mislav setting "accept-encoding" => "none" fixed the zlib error for me too, thanks! 👍

**Comment by nicovanniekerk** [comment]
This worked for me too, Thanks guys!!
