### ISSUE TITLE
EM-HTTP SSL patch duplication

### ISSUE THREAD

**Issue by ayanko** [lostisland/faraday#1201]
This one is already merged https://github.com/igrigorik/em-http-request/pull/340

https://github.com/igrigorik/em-http-request/blob/v1.1.6/lib/em-http/http_connection.rb#L41

So instead of 
```
require 'faraday/adapter/em_http_ssl_patch'
```

in
* `lib/faraday/adapter/em_http.rb`
* `lib/faraday/adapter/em_synchrony.rb`

change to

```ruby
if EventMachine::HttpRequest::VERSION < '1.1.6'
  require 'faraday/adapter/em_http_ssl_patch'
end
```

Or remove patch completely...

**Comment by kylekeesling** [comment]
Happy to take a crack at it! Will submit a PR shortly.

**Comment by kylekeesling** [comment]
I'm a bit out of my element on this (haven't done much work on gems) but as I was digging around inside the 'em-http-request' gem, it doesn't seem as though `version.rb` is included anywhere, which in my mind would indicate that it would then not be accessible when we require `em-http`

When I change the `dependency` call to a block, and explicity include the version file, I can get the sepcs to pass:
```
dependency do
  require 'em-http'
  require 'em-http/version'
end 
```

If that's the case, would the long-term fix actually be to include the version file in the `em-http-request` bootstrap file? IE appending this to it: `require 'em-http/decoders'`

https://github.com/igrigorik/em-http-request/blob/master/lib/em-http.rb

If so I'm happy to open a PR on that library as well to get it fixed.
