### ISSUE TITLE
remove pre-GA expected builds

### ISSUE THREAD

**Issue by grosser** [lostisland/faraday#1210]
<img width="568" alt="Screen Shot 2020-11-27 at 4 38 24 PM" src="https://user-images.githubusercontent.com/11367/100490259-04b0ef00-30cf-11eb-91ae-bace22f4722b.png">
@iMacTia

**Comment by olleolleolle** [comment]
Yes that! Thanks, I removed all except one called linting, should that go, too?

**Comment by grosser** [comment]
all the builds in for example https://github.com/lostisland/faraday/pull/1211 should be marked as required, so missing 6 (maybe not head since that is new)

**Comment by grosser** [comment]
.... or I guess just leave it as it is since I hope nobody will merge on broken build
