### ISSUE TITLE
Breaking changes in 1.2.0

### ISSUE THREAD

**Issue by BobbyMcWho** [lostisland/faraday#1224]
## Basic Info

* Faraday Version: 1.2.0
* Ruby Version: 2.6

## Issue description
> Faraday 1.2.0 appears to break Octokit functionality, see https://github.com/octokit/octokit.rb/issues/1315 
 I experienced this in my own usage of dependabot because of the lack of NotFound error being raised, my exception handling did not catch `[:message, "Not Found"]:Array` that was returned, and led to me trying to call path on an object that was not there. `undefined method 'path' for [:message, "Not Found"]:Array (NoMethodError)`

## Steps to reproduce
Using OctoKit, try and query a resource that does not exist. Expect a NotFound to be raised, instead receive an array [:message, "Not Found"]

**Comment by tarebyte** [comment]
This was actually due to use listing `on_complete` as private. Which we resolved in https://github.com/octokit/octokit.rb/pull/1316
