### ISSUE TITLE
Retry and RaiseError Middleware are incompatible

### ISSUE THREAD

**Issue by eric-hemasystems** [lostisland/faraday#1242]
## Basic Info

* Faraday Version: v1.0.1
* Ruby Version: 2.7.1

## Issue description

The "retry" middleware allows you to specify a status code to retry on. But if you also use the "raise_error" middleware that status is never evaluated because the error is raised first.

## Steps to reproduce

```ruby
Faraday.new(url: "https://lostisland.github.io") do |f|
  f.request :retry, retry_statuses: 404
  f.response :raise_error
end.get('/not_found')
```
Running this I expect multiple requests to Github before giving up and raising an error. Instead there is just one before it raises an error. This uses a 404 as it's test. In my app I'm dealing with a 429 rate limiting response but the same principals apply.

There is a workaround of catching the `Faraday::ClientError` along with using the `retry_if` option (and clearing out the methods to make `retry_if` work) but this really removes the whole point of having the `retry_statuses` option:

```ruby
Faraday.new(url: "https://lostisland.github.io") do |f|
  f.request(:retry,
    exceptions: [Faraday::ClientError],
    retry_if: ->(env, ex) { ex.response[:status] == 404 },
    methods: []
  )
  f.response(:raise_error)
end.get('/not_found')
```

**Comment by iMacTia** [comment]
Hey @eric-hemasystems you might want to swap the two adapter so that the raise_error comes first in the stack.
Could you give that a try and let me know if that solves your issue 🙂?

**Comment by eric-hemasystems** [comment]
@iMacTia - You're a genius. Not sure why I didn't think of that but that solved the problem. Thanks!

**Comment by iMacTia** [comment]
Hahaha thanks @eric-hemasystems! But trust me this has nothing to do with genius 😂, I have simply been using it for a while longer 😄
Glad I could help 🙌!
