### ISSUE TITLE
searchick reindex returns "Faraday::TimeoutError","Net::ReadTimeout"

### ISSUE THREAD

**Issue by RohitVenturit** [lostisland/faraday#1251]
## Basic Info

* Faraday Version: 0.17.4
* Ruby Version: 2.6.1

## Issue description
Post.reindex return timeout error as shown here:
Post Import (30696.7ms)  {"count":135,"exception":["Faraday::TimeoutError","Net::ReadTimeout with #\u003cTCPSocket:(closed)\u003e"],"exception_object":"Net::ReadTimeout with #\u003cTCPSocket:(closed)\u003e"}
  
## Steps to reproduce
run Post.reindex  on console.

**Comment by RohitVenturit** [comment]
any solution for this timeout error? it happens mostly at end of record ie. Post.all.count is also 135. so its happening when we are at end of record.

**Comment by olleolleolle** [comment]
@RohitVenturit This issue seems to be unrelated to the Faraday library.

I suggest asking this searchkick question on a wider forum such as StackOverflow. People seem to talk about searchkick usage there: https://stackoverflow.com/search?q=searchkick&searchOn=3 

👋 Hope this helps!
