### ISSUE TITLE
Swapping Branch Name Broke GitHub Pages

### ISSUE THREAD

**Issue by sneaky-emily** [lostisland/faraday#1265]
## Basic Info

* Faraday Version: N/A
* Ruby Version: N/A

## Issue description
It appears that when the primary branch was renamed from 'master' to 'main' #1263, it broke GitHub pages for the project, as the homepage currently 404's when you try to reach it.

**Comment by olleolleolle** [comment]
I took a look at the Settings / Pages page and its settings show main and /docs being the chosen branch and directory. Perhaps it needs a build, a change in the docs directory, to take hold?

**Comment by sneaky-emily** [comment]
As you mentioned on Twitter, forcing the documentation to update seems to have fixed it. I really appreciate your swift response and fix!
