### ISSUE TITLE
CI : Can we drop "gem install bundler"?

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#1268]
## Basic Info

* Faraday Version: CI
* Ruby Version: this needs only happen for non-bundler-having Rubies

## Issue description

In CI, are we wasting time on "install bundler"?

**Comment by iMacTia** [comment]
Happy to try and remove it as it's now bundled with Ruby, but this may cause issues with older Rubies (e.g. 2.4)

**Comment by olleolleolle** [comment]
Guessing: Since we _have_ shell access, we could check either the running ruby -v OR use the matrix.version (CI YAML config value).

**Comment by olleolleolle** [comment]
This was fixed in 6333b73d13c17e6c771a2e78447a7b933298c1b0
