### ISSUE TITLE
Feature Request: a functionality to pass a logger instance via one Hash

### ISSUE THREAD

**Issue by ts-3156** [lostisland/faraday#1278]
Thank you for useful gem!

When passing logger options from a higher layer to Faraday, I may want to pass a logger and its options via a single Hash. The specific code is as follows. I would like to know your opinion on this feature request. If you agree with this idea, I will make a pull request. If you don't want it, please feel free to close this issue.

```ruby
# Current implementation
class ApiClient
  def initialize(options)
    @token = options[:token]

    Faraday.new(url: '...') do |faraday|
      logger_options = options[:logger_options] || {}
      faraday.response :logger, options[:logger], logger_options
    end
  end
end

ApiClient.new(token: '...', logger: MyLogger.new, logger_options: { headers: true, bodies: true })
```

```ruby
# Expected implementation
class ApiClient
  def initialize(options)
    @token = options[:token]

    Faraday.new(url: '...') do |faraday|
      faraday.response :logger, options[:logger_options]
    end
  end
end

ApiClient.new(token: '...', logger_options: { logger: MyLogger.new, headers: true, bodies: true })
```

[the code diff](https://github.com/ts-3156/faraday/commit/1b64ceea62fe7c35ebd67e3186b674365de5ebf6)

**Comment by iMacTia** [comment]
Hi @ts-3156 and thanks for using Faraday!
I don't have any strong feelings on the change in the logger middleware API, but the biggest issue with this change is that it wouldn't be backwards compatible, or if it was, it would make the code inside the middleware more complicated (as it would need to manage both cases).

Have you considered this implementation instead?

```ruby
# This implementation decouples the Faraday configuration from the ApiClient one
# relying on the latter to map the configuration values
class ApiClient
  def initialize(options)
    @token = options[:token]
    # .dup here is used so that the `options` hash provided from caller is not changed
    logger_options = options[:logger_options]&.dup || {}
    # uses Hash#delete to extract the logger
    logger = logger_options.delete(:logger)

    Faraday.new(url: '...') do |faraday|
      faraday.response :logger, logger, logger_options
    end
  end
end

# You can now use your preferred API for your ApiClient library
ApiClient.new(token: '...', logger_options: { logger: MyLogger.new, headers: true, bodies: true })
```

**Comment by ts-3156** [comment]
@iMacTia Thank you for taking the time to reply.

I am convinced of your opinion. I think the cons of losing backward compatibility and maintainability outweigh the pros of this change.

Thank you for the code sample. I will implement it that way.

**Comment by iMacTia** [comment]
Thanks @ts-3156, glad that was useful.
I'll close this but please feel free to reach out if you have any issue
