### ISSUE TITLE
Proxy silently ignored without `http:`

### ISSUE THREAD

**Issue by gurgeous** [lostisland/faraday#1282]
## Basic Info

* Faraday Version: 1.4.1
* Ruby Version: 2.7

## Issue description

Proxy silently ignored without `http:`. For example, if you set proxy to `something:1234` it will be silently ignored. The correct proxy setting would be `http://something:1234`. This is an important issue because it's undocumented, difficult to debug, and can have serious consequences for crawling projects.

I propose either:

1. In ProxyOptions.from, reject strings that lack a scheme.
or
1. In ProxyOptions.from, default to `http://` for strings that lack a scheme.

Let me know if you agree with one of these options and I'l put together a PR. Thanks!

## Steps to reproduce

```ruby
> Faraday::ProxyOptions.from("something:1234").host
# => nil

> Faraday::ProxyOptions.from("http://something:1234").host
# => "something"
```

**Comment by iMacTia** [comment]
Thanks @gurgeous option 2 sounds good to me, but I have to admit I'm no expert on proxies... are we sure there's no use case where one might want to omit the protocol?

We pass the string as is to [`URI`](https://ruby-doc.org/stdlib-2.5.1/libdoc/uri/rdoc/URI/Generic.html) for parsing. `something:1234` is a valid URI, although that will populate the `scheme` and `opaque` properties. It seems like a use case for `mailto` and similar links, which I guess would not apply to proxies.

**Comment by gurgeous** [comment]
I am not an expert either... as far as I know the only use cases are http(s) and socks? Not sure if socks is even supported yet. I'll put together a simple PR and we can see if anyone complains.

**Comment by iMacTia** [comment]
Sounds good, thanks!
I don't think we support SOCKS atm, but I remember there was some [work on that](https://github.com/lostisland/faraday/pull/992) in the past

**Comment by olleolleolle** [comment]
@iMacTia Reading that work, made me realize that "assume it's an HTTP proxy" is a pretty good assumption.
