### ISSUE TITLE
Connection url is shared between requests causing concurrency issues

### ISSUE THREAD

**Issue by alexeyds** [lostisland/faraday#1287]
## Basic Info

* Faraday Version: 1.3, 1.4
* Ruby Version: any

## Issue description
In a certain setup(provided below) requests made with the same connection are using shared URI instance which in my case had caused a race condition when two simultaneous requests with different query params were actually executed with the same query params resulting in very unexpected behavior.

Example:
```rb
conn = Faraday.new("http://google.com/users")

response1 = conn.get(nil, { id: 1 })
response2 = conn.get(nil, { id: 2 })

response1.env[:url] #=> "http://google.com/users?id=2"
response1.env[:url] === response2.env[:url] #=> true
```

**Comment by iMacTia** [comment]
Thanks for raising this and providing a fix. That has just been merged.
Out of curiosity... was this causing issues only for parallel requests? I can't see the race-condition happening unless you're running those requests in parallel

**Comment by alexeyds** [comment]
>Out of curiosity... was this causing issues only for parallel requests?

Yes, we detected it when some requests made from sidekiq jobs yielded inconsistent results and I could reproduce it every single time with code like this, but you'd have to inspect actual data received by the server to see it:

```rb
conn = Faraday.new("http://localhost:3000/users")

2.times do |i|
  Thread.new do
    conn.get(nil, { id: i })
  end
end
```
