### ISSUE TITLE
undefined method `absolute?' for "https://oauth2.googleapis.com/token":String

### ISSUE THREAD

**Issue by khanimdad** [lostisland/faraday#1295]
On Ruby 2.7

Gems which causes this issue
- Koala
- omniauth-google-oauth2

![image](https://user-images.githubusercontent.com/181245/125624922-8eab04e3-0dfd-43e5-b36b-0e75f126d694.png)

**Comment by olleolleolle** [comment]
Side note: Current Faraday release is 1.5.1. This refers to an older 0.17.4 release.

**Comment by olleolleolle** [comment]
I'm a bit curious about how the String was able to scoot through the "responds to the message `host`" check.

**Comment by iMacTia** [comment]
This is really strange, I also tried calling Utils.URI with the same string value and it successfully returns `#<URI::HTTPS https://oauth2.googleapis.com/token>`, so my guess is that there's something fishy going on here.

@khanimdad any chance you may have extended the Ruby String class with a `host` method?

**Comment by khanimdad** [comment]
Thanks @olleolleolle, yes i had extended Ruby String with `host`, removed that, now its working fine

**Comment by iMacTia** [comment]
Glad to hear that 🎉!
