### ISSUE TITLE
Supported ruby versions conflict

### ISSUE THREAD

**Issue by jedeleh** [lostisland/faraday#1304]
## Basic Info
The Faraday README.md states:  "Currently that means we support Ruby 2.6+"

Rubygems.org states that the required ruby version is >= 2.4 

This seems contradictory.

* Faraday Version: 1.7.0
* Ruby Version: 2.5.3

## Issue description
I need to use the most recent version of Faraday that supports 2.5.3. There's likely no code change for this--just documentation to explain why, and then how to find the the actual version that supported a specific ruby version. 

## Steps to reproduce
Read the README, visit Rubygems.org and check the required ruby version information on the right side of the view when you select a specific Faraday version.

**Comment by olleolleolle** [comment]
The code is linted with Ruby 2.4 rules, so that we can still install and use on that, but we are not extending the promise longer than that. Our support window is "the same as Ruby's", but we didn't see a reason to cut off earlier versions before we had a reason to.

https://github.com/lostisland/faraday/blob/main/.rubocop.yml#L11

**Comment by iMacTia** [comment]
Hi @jedeleh, thanks for raising this and apologies for the confusion.
The `main` branch represents our upcoming `2.0` release, which will track Ruby's support window, however v 1.x of Faraday (based off the `1.x` branch) still supports Ruby 2.4+ and is tested and linted against that.

Based on your feedback I suspect we should add a clear message in the README to explain that the `main` branch does not represent the latest Rubygems release, so I'll be doing that as soon as possible

**Comment by jedeleh** [comment]
Perfect! Thanks for the information, and for considering the issue.
