### ISSUE TITLE
Faraday raises different timeout errors depending on adapter

### ISSUE THREAD

**Issue by woarewe** [lostisland/faraday#1310]
## Basic Info

* Faraday Version: 1.7.0
* Ruby Version: 2.7.4

## Issue description

Hi, I'm working on the HTTP wrapper for my project and faced some strange behavior.
We want to use the default `net_http` adapter for simple requests and `typhoeus` for concurrent.
Covering this logic by tests I noticed that it raises different timeout errors depending on an adapter.

## Steps to reproduce

A fast run
```shell
 ruby -e "$(curl https://gist.githubusercontent.com/woarewe/16a33e3eecbd7e2af9622afb2898db28/raw/ecf662fb4d1739a0f3ad4261919b5d219cdaffd5/faraday_example.rb)"
```

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  ruby "2.7.4"

  gem "webmock", "~> 3.14.0"
  gem "faraday", "~> 1.7.0"
  gem "typhoeus", "~> 1.4.0"
end

require "webmock"
require "faraday"
require "typhoeus/adapters/faraday"

WebMock.enable!
include WebMock::API
URL = "https://www.example.com"

stub_request(:get, URL).to_timeout

def net_http
  conn = Faraday.new do |conn|
    conn.adapter :net_http
  end
  conn.get(URL)
end

def typhoeus
  conn = Faraday.new do |conn|
    conn.adapter :typhoeus
  end
  conn.get(URL)
end

def handle
  yield
rescue => e
  p e.class
end

handle { net_http } # => Faraday::ConnectionFailed
handle { typhoeus } # => Faraday::TimeoutError

```

Might this problem happen because of mocking and for real env it will raise the same error?

Thank you very much for your time and such an amazing tool!

**Comment by iMacTia** [comment]
Hi @woarewe, I'm really sorry for this unexpected behaviour, but we're actually aware of this.
This has been [discussed at length in the past](https://github.com/lostisland/faraday/issues/718#issuecomment-343957963), however until now we were unable to fix it without introducing breaking changes.
I'm afraid in the short term this behaviour, although incorrect, is to be expected, and what I'd suggest you to do is to catch both exceptions (or catch an exception based on the adapter).

The bottom line of that long discussion, which I encourage you to read and potentially participate into, was that the `net_http` behaviour is more correct (although we've been arguing on the correct exception name 😂).
The problem with `typhoeus` is that it makes it hard to distinguish open timeouts from read ones. `HTTPClient` suffers from the same issue.

The good news is that we're now closing in on a v2.0 release. That is our opportunity to set a new, breaking rule and force the adapters to comply. It's hard to say though if and when the adapters will be able to comply, so I won't be able to provide an estimate on that.
