### ISSUE TITLE
No release notes for 0.17.4

### ISSUE THREAD

**Issue by AndrewRayCode** [lostisland/faraday#1313]
Faraday 0.17.4 is a published gem version but there are no release notes for it.

https://rubygems.org/gems/faraday/versions/0.17.4

**Comment by iMacTia** [comment]
Hi @AndrewRayCode, I guess you're referring to the [CHANGELOG](https://github.com/lostisland/faraday/blob/main/CHANGELOG.md), and you're totally right.
We usually put the release notes in [Releases](https://github.com/lostisland/faraday/releases), and often forget to update the `CHANGELOG`. I wonder if there's a way to tell this to Rubygems 🤔

**Comment by AndrewRayCode** [comment]
Oh I didn't realize they were in the release tags, thanks!

**Comment by iMacTia** [comment]
No worries, and thanks for pointing out the outdated changelog 🙏 ! I’ll update it now
