### ISSUE TITLE
retry middleware, `exceptions` option as String does not match on exception sub-classes

### ISSUE THREAD

**Issue by jrochkind** [lostisland/faraday#1330]
## Basic Info

* Faraday Version: 1.7.0
* Ruby Version: 2.7.4

## Issue description

The `exceptions` option is [documented](https://github.com/lostisland/faraday/blob/main/lib/faraday/request/retry.rb#L18) to work as a module/class (eg `Faraday::Error`), _or_ as a string (eg `"Faraday::Error"`). 

If you pass it as the class object itself, it matches on all sub-classes. For instance, if you pass `Faraday::Error`, the retry will still happen if the exception raised were `Faraday::ConnectionFailed` or `Faraday::TimeoutError`, as these are both sub-classes of `Faraday::Error`. This is exactly what a rubyist would expect; it's how similar APIs (including ruby `rescue` itself) generally work. 

However, if you pass the argument instead as a string, `"Faraday::Error"`, it will only be considered matched if the exception raised is exactly a `Faraday::Error`, **not** a sub-class like `Faraday::ConnectionFailed` or `Faraday::TimeoutError`. 

This is unexpected, that passing a string changes semantics like this.  Either it's a bug that String argument works differently (I think it probably is?); _or_ it should be documented that it works differently. 

We can see why it works how it works in the implementation here: https://github.com/lostisland/faraday/blob/506e97afe606efcb24f7f007cb1885c04f56fb93/lib/faraday/request/retry.rb#L187

If it is to work as expected, either that would need to be changed to something like `error.class.ancestors.collect(&:to_s).include?(ex.to_s)`, _or_ the code would just have to turn the string into the actual class/module it represents before just using `is_a?` as normal. 

I could submit a PR if someone provides guidance as to preferred path.

**Comment by jrochkind** [comment]
OK thanks for the tips! I'll see what I can do. 

(I definitely avoid the one-liner `rescue nil` which rescues all StandardError, I'd only want to rescue NameError. But const_defined? seems preferable.)

**Comment by iMacTia** [comment]
@jrochkind just a quick note that your PR was successfully merged in `main`, but that's currently pointing to the next major 2.0 release. I just realised that in your issue description you mention v1.7. If you would like this change backported, you can cherry-pick your commit into a new PR against the `1.x` branch, so that I can merge that in and cut a new release.

**Comment by jrochkind** [comment]
Ah, ok, thanks for the note! I will see about that maybe. Is there any general estimate of when 2.0 might drop, like even just is it "almost done" at this point, or "just beginning"?
