### ISSUE TITLE
Ability to pass a callable to authorization middleware

### ISSUE THREAD

**Issue by sled** [lostisland/faraday#1344]
The authorization middleware currently checks for a `Proc`:
https://github.com/lostisland/faraday/blob/746ab737b5d5bf3bcd28f377044f7bec03f8286d/lib/faraday/request/authorization.rb#L40

Wouldn't it make sense to ease this restriction and just require a callable? 

Example use case:

```rb
class ComplexAuthorizer
  def call
     # do magic and return a token
  end
end

authorizer = ComplexAuthorizer.new(....)

Faraday.new(url: ....) do |conn|
  conn.request :authorization, 'Bearer', authorizer
end

```

**Comment by iMacTia** [comment]
That would make sense indeed, I'd happily review a PR that enhances the middleware to accept either a `proc` or a callable 👍

**Comment by sled** [comment]
> That would make sense indeed, I'd happily review a PR that enhances the middleware to accept either a `proc` or a callable 👍

Here you go: https://github.com/lostisland/faraday/pull/1345
