### ISSUE TITLE
Using mashify with faraday v2

### ISSUE THREAD

**Issue by sue445** [lostisland/faraday#1373]
## Basic Info

* Faraday Version: 2.0
* Ruby Version: 2.6+

## Issue description
I would like to support faraday v2 with my own API client.

So I want to use [mashify](https://github.com/lostisland/faraday_middleware/blob/v1.2.0/lib/faraday_middleware/response/mashify.rb) from faraday_middleware (This is deprecated in faraday v2), but I can't find any gem like faraday-mashify.
https://rubygems.org/search?query=faraday-mashify

Do you have any plans to release faraday-mashify?

Or is mashify deprecated in faraday v2?

**Comment by iMacTia** [comment]
@sue445 We'd love to see all middleware included in faraday_middleware re-released as standalone gems, however given the limited resources we don't have a clear timeline yet. We'll get to it at some point.

We welcome people who would like to create and maintain them though, it doesn't have to be us! And that can easily be achieved using the "faraday-middleware-template" repository.

**Comment by sue445** [comment]
> We welcome people who would like to create and maintain them though, it doesn't have to be us! 

@iMacTia I see. I'll create faraday-mashify gem 😄

**Comment by iMacTia** [comment]
Wonderful! In my last comment I forgot the link to the template repo: https://github.com/lostisland/faraday-middleware-template

That uses `gem_generator` so you don't need to clone it, just follow the instructions and it will create a new project following the middleware template.
Example of middleware gems (in case they're useful):
* https://github.com/lostisland/faraday-retry
* https://github.com/lostisland/faraday-rashify
* https://github.com/lostisland/faraday-multipart

And obviously, if you need assistance we're here!

**Comment by sue445** [comment]
I published faraday-mashify 🚀 

* https://github.com/sue445/faraday-mashify
* https://rubygems.org/gems/faraday-mashify

**Comment by iMacTia** [comment]
@sue445 that was super quick 🎉🥳👏!!
I hope the template helped! Feel free to share any issue you encountered so we can make it even better ❤️
