### ISSUE TITLE
POST/PUT form-data with duplicated keys? 😬 

### ISSUE THREAD

**Issue by midwire** [lostisland/faraday#1375]
## Basic Info

* Faraday Version: 1.8.0
* Ruby Version: 3.0.1

### More version info:

```
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
...
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
```

## Issue description
I need to be able to POST/PUT form-data with multiple duplicate keys.  For example:

```
curl --location \
  --request PUT 'https://someapi.net/v3/domains/33/webhooks/clicked' \
  --header 'Authorization: Basic ASDF...QWER' \
  --form 'id="clicked"' \
  --form 'url="https://bogus.com/mailgun/webhook"' \
  --form 'url="https://wonky.net/mailgun/webhooks/129"'
```

Notice that `url` is repeated twice with different values.

Here is the same raw HTTP request:

```
PUT /v3/domains/33/webhooks/clicked HTTP/1.1
Host: someapi.net
Authorization: Basic ASDF...QWER
Content-Length: 372
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

clicked
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="url"

https://bogus.com/mailgun/webhook
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="url"

https://wonky.net/mailgun/webhooks/129
----WebKitFormBoundary7MA4YWxkTrZu0gW
```
and here it is using raw "Net::HTTP":

```
require "uri"
require "net/http"

url = URI("https://someapi.net/v3/domains/33/webhooks/clicked")

https = Net::HTTP.new(url.host, url.port)
https.use_ssl = true

request = Net::HTTP::Put.new(url)
request["Authorization"] = "Basic ASDF...QWER"
form_data = [['id', 'clicked'],['url', 'https://bogus.com/mailgun/webhook'],['url', 'https://wonky.net/mailgun/webhooks/129']]
request.set_form form_data, 'multipart/form-data'
response = https.request(request)
puts response.read_body
```

I can do this with cURL, Net::HTTP and Postman.

However, I can't yet figure out how to translate that form data with duplicate `url` keys using Faraday.  It seems a strange practice for a hosted API not to accept a standard JSON array for things like this, but mailgun requires form-data and wants the `url` parameter repeated like this. 🤷🏼‍♂️ 

Here's how I instantiate my Faraday instance:

```
  def client
    @client ||= Faraday.new(url: base_uri) do |f|
      f.adapter :typhoeus
      f.request :multipart
      f.request :url_encoded
    end
  end
```

And the actual call looks like this:

```
payload = {
     :id => "clicked",
    :url => [
        [0] "https://bogus.com/mailgun/webhook",
        [1] "https://wonky.net/mailgun/webhooks/135"
    ]
}

client.put('https://someapi.net/v3/domains/33/webhooks/clicked', payload)
```

I've tried several variations on this code, experimenting with the payload using different types of arrays and strings. So far nothing that I've tried works.  Hoping someone has run into something like this before?

Any help would be greatly appreciated.

**Comment by iMacTia** [comment]
@midwire Hey, it's late here so I didn't have much team to look into this, but could you try using the flat encoder as I suggested [here](https://github.com/lostisland/faraday/issues/1169#issuecomment-662313948)?

Let me know if that works and if it doesn't we can try something else 👍

**Comment by midwire** [comment]
@iMacTia that worked!  I've spent many hours over many days trying to figure this out.  Thanks a ton mate!

**Comment by iMacTia** [comment]
Glad to hear it worked 🎉 !
Less glad to hear you had to spend so much time on it 😢.

If this was mentioned in the `faraday-multipart` gem README, would you have seen it?
Interesting to know which resources you checked as this is probably not explicitly documented (but it totally should)

**Comment by midwire** [comment]
Personally, I certainly would have seen it there as I always try to do my own due diligence, read the docs readme, etc. as well as try everything I can think of on my own before bothering anyone else.  It would have been prudent of me to just read the code and find that option there (as I did after you shared the info - I wanted to see if there were other nifty options that were not yet documented). Thanks again @iMacTia. 👍🏼

**Comment by iMacTia** [comment]
Thanks for the feedback @midwire, I've updated the `faraday-multipart` README to show the option 🙌 
Hopefully, this will save time for people in future!
