### ISSUE TITLE
NoMethodError:  undefined method `dependency` for `Faraday::Middleware:Class`

### ISSUE THREAD

**Issue by AlexWayfer** [lostisland/faraday#1397]
## Basic Info

* Faraday Version: `2.2.0`
* Ruby Version: `3.1.0p0`

## Issue description

I'm trying to update my [`faraday-encode_xml`](https://github.com/AlexWayfer/faraday-encode_xml) middleware to Faraday v2, but I've faced the issue which is not described in the [`UPGRADING.md`](https://github.com/lostisland/faraday/blob/main/UPGRADING.md).

## Steps to reproduce

```ruby
# frozen_string_literal: true

require 'faraday'

module Faraday
  module EncodeXML
    class Middleware < Faraday::Middleware
      dependency do
        require 'gyoku' unless defined?(::Gyoku)
      end
    end
  end
end
```

**Comment by olleolleolle** [comment]
The Faraday 2 variant does not do "optional, late-fetched dependencies". It uses a regular require at the top of the file.

**Comment by olleolleolle** [comment]
@AlexWayfer In order to have the information in the UPGRADING.md, I made a PR. Thanks for the inspiration!
