### ISSUE TITLE
Q: faraday_middleware is deprecated, what is the recommendation to have follow redirects?

### ISSUE THREAD

**Issue by tisba** [lostisland/faraday#1403]
I'm trying to prepare our application for faraday 2.x. Since `FaradayMiddleware` is deprecated and won't be updated and we are using `FaradayMiddleware::FollowRedirects`, I'm a bit lost what the recommendation is to substitute this middleware.

https://lostisland.github.io/faraday/middleware/ is mentioning "following redirects", https://lostisland.github.io/faraday/middleware/list does not mention redirects at all and https://github.com/lostisland/awesome-faraday/#middleware links to the deprecated `faraday_middleware` repository.

Can someone point me in the right direction? Thx :)

**Comment by iMacTia** [comment]
Hey @tisba, indeed `faraday_middleware` has been deprecated, but we're a bit resource-constrained at the moment, as I explained in this comment: https://github.com/lostisland/faraday/issues/1373#issuecomment-1007782780

Bottom line is that we'd love the `follow_redirect` and all the other middleware to be released as standalone gem for people to use with Faraday v2, but with the limited time we have we're progressing on a "community interest" base.

Since you're apparently the first one attempting to use `follow_redirects` with Faraday v2 (and thanks for upgrading, by the way ❤️!) would you consider making that gem yourself 🙏? Guidance on how to do that can be found [here](https://github.com/lostisland/faraday/issues/1373#issuecomment-1008002773)

**Comment by iMacTia** [comment]
Thanks 🙏!
I'm here if you have any doubt/issue, I just can't be on this 100%
Please also feel free to share any feedback on the process, as we're trying to make this as simple as possible 🙌

**Comment by iMacTia** [comment]
Fantastic work @tisba 👏 🎉 !!

> Are you collecting faraday middleware under the https://github.com/lostisland organisation?

No need, we're happy to have them hosted by others. Spread the love ❤️

> The process itself was pretty nice and straight forward, excellent preparation on your end!

Couldn't have made me happier than hearing this 😄, but huge shout to @AlexWayfer who setup that repository that way 👏 !

> Is there anything I should keep in mind? Or change?

Your solution makes sense, but if you want to be absolutely sure everything is working as expected, then you can setup a CI matrix that tests your gem against multiple Faraday versions. The reason this is not in the middleware template is that I recently came up with myself, probably a good addition 😄
You can see how that works in [this GitHub workflow](https://github.com/lostisland/sawyer/blob/master/.github/workflows/ci.yml#L16-L21). Feel free to copy it over and remember the `.gemfiles` folder as well.

**Comment by iMacTia** [comment]
@tisba I'm going to feature your new gem in `awesome-faraday` as well, thanks again 🙏 !

**Comment by tisba** [comment]
> Your solution makes sense, but if you want to be absolutely sure everything is working as expected, then you can setup a CI matrix that tests your gem against multiple Faraday versions. The reason this is not in the middleware template is that I recently came up with myself, probably a good addition 😄 You can see how that works in [this GitHub workflow](https://github.com/lostisland/sawyer/blob/master/.github/workflows/ci.yml?rgh-link-date=2022-02-24T16%3A36%3A42Z#L16-L21). Feel free to copy it over and remember the `.gemfiles` folder as well.

That's a neat approach, thx for the hint!

For starters I went with only supporting faraday 2.x and point to the deprecated `faraday_middleware` repository to keep things simple. But I really liked the faraday migration process offering gems before making the migration, so I might revisit this soonish :)

**Comment by AlexWayfer** [comment]
I'm happy that my work on middleware template helped somebody! Thank you for mention. And good work to separate and release a new middleware as a gem.
