### ISSUE TITLE
Wrong information on upgrade page

### ISSUE THREAD

**Issue by Piioo** [lostisland/faraday#1409]
## Basic Info

On the update page of faraday to version 2.0 https://github.com/lostisland/faraday/blob/main/UPGRADING.md it is written, that `net_http` is as default adapter leaved in the gem, but its not.

You have to install `faraday-net_http` before you can use `net_http`

So this update page is not correct.

**Comment by iMacTia** [comment]
Hi @Piioo, apologies for the confusion.
Faraday 2.0 did originally ship without `faraday-net_http`, but that decision was quickly reversed and the next day v2.0.1 was out re-introducing it (see https://github.com/lostisland/faraday/commit/5f88f8ff85c574e30e2cea46324b90c3ffa7ff53).

So you need to install `faraday-net_http` ONLY if you're explicitly using v2.0, but my suggestion would be to use 2.0.1 instead as it makes things much easier!

A solution to avoid confusion would be to yank the 2.0 version from rubygems, but I don't really like doing that as it may cause other issues, plus using 2.0.1 instead should be pretty straightforward.

I'll update the UPGRADING page with an additional note explaining that 2.0 does not include the `net_http` adapter and people should instead use 2.0.1+ 👍
