### ISSUE TITLE
`require 'faraday/retry'` is broken

### ISSUE THREAD

**Issue by grosser** [lostisland/faraday#1417]
## Basic Info

* Faraday Version: 2.3.0
* Ruby Version: 3.1.2

https://github.com/lostisland/faraday/blob/main/docs/middleware/index.md documents it but it does not work

```
cannot load such file -- faraday/retry (LoadError)
```

**Comment by olleolleolle** [comment]
Ah, perhaps we missed documenting
https://github.com/lostisland/faraday-retry
Being the home of that extracted gem?

**Comment by grosser** [comment]
yeah, just needs to link to the gem ... or replace the section with a link to the gem

**Comment by iMacTia** [comment]
Oh this is a documentation issue, I'm so glad to see that. For a moment I thought the import was broken 😅!
Thanks for pointing this out @grosser, will fix that immediately 👍
