### ISSUE TITLE
Support for Ubuntu 22.04, using OpenSSL 3.0.2 (i.e. Heroku 22)

### ISSUE THREAD

**Issue by calebhaye** [lostisland/faraday#1476]
## Basic Info
Long story short, this gem doesn't work on Heroku-22, Heroku's latest statck

## Issue description
Using Ubuntu 22.04, w/ OpenSSL 3.0.2 breaks this gem and causes an SSLError "SSL_CTX_load_verify_file: system lib"

**Comment by hayesr** [comment]
@calebhaye What was the fix? Was something changed in Faraday? I get the same error in Github Actions.

**Comment by neoxader** [comment]
@calebhaye  @hayesr I got this issue, what's the solution?

**Comment by iMacTia** [comment]
For future readers, this doesn't look like a Faraday issue, but rather a Ruby compatibility issue.
According to [this article](https://deanpcmad.com/2024/installing-older-ruby-versions-on-ubuntu-24-04-and-22-04/) the problem seems related to the Ruby and SSL versions installed in the system:

> Because Ubuntu 24.04 & 22.04 come with OpenSSL 3.0, Ruby 3.0 and below don’t support this so an older version is required for these versions to be installed.
