### ISSUE TITLE
Streaming Stop with Connection Close?

### ISSUE THREAD

**Issue by fearlessfrog** [lostisland/faraday#1501]
## Basic Info

* Faraday Version: 2.7.4
* Ruby Version: 3.2.0

## Issue description
Using connection close does not stop the req.options.on_data streaming proc callbacks for a stream. 

Another way to ask this one would be what would be the best way to stop/cancel a stream that is already running given access to the Faraday connection, env and req/resp objects?

## Steps to reproduce
1. Set up conn.post(uri(path) do |req| req.options.on_data call
2. In proc callback call conn.close
3. The req.options.on_data proc is still called as data streams in.

Thanks for any help/advice.

**Comment by fearlessfrog** [comment]
Thanks for taking a look. A custom exception raised in the on_data block does do the trick and works when caught by the calling job. The stop request is via a user cancel action, and I already use Redis etc to flag that within the running asynch bg jobs; it looks for that state as the on_data proc executes and raises the exception as needed. I just wasn't sure if there was a better way or something I missed or not. I do pass the request object to the proc (using ruby-openai with the new chat streaming for this), so in the future it could call a new 'close' or 'stream_close' on that, but I'm not familiar enough with Faraday to know if that fits the overall design. Thanks again, and happy for this to be closed if wanted.

**Comment by iMacTia** [comment]
Thank you for reporting back @fearlessfrog!
I'm glad to hear that worked, and appreciate raising exceptions doesn't feel "right".

Unfortunately, Faraday does not manage the underlying connection and is therefore unable to close the connection without this functionality being exposed by the underlying adapter(s).
I was unable to find anything like that for `Net::HTTP`, and I suspect this is mostly due Ruby's non-concurrent nature, which makes these things feel less necessary.

I'm gonna close the issue considering you were able to achieve what you wanted, but if anyone more knowledgeable would like to contribute in making this nicer I'd happily review a new issue/PR ❤️
