### ISSUE TITLE
Dead link to Faraday Team in README and docs

### ISSUE THREAD

**Issue by larouxn** [lostisland/faraday#1518]
👋 Non-user code facing, just a heads up that there's a link to `Faraday Team` in the README and docs that doesn't go anywhere. Should probably either update it or remove the link.

**README**

<img width="1920" alt="Screenshot 2023-07-25 at 14 39 51" src="https://github.com/lostisland/faraday/assets/1557529/25c8df3d-518a-4f7d-887a-339962537cf6">
<img width="1920" alt="Screenshot 2023-07-25 at 14 40 13" src="https://github.com/lostisland/faraday/assets/1557529/a3563604-58fa-4852-8cc4-02b04d8060c2">

https://github.com/lostisland/faraday/blob/0580f101ce58a3f0ab4b555af300fe2ccbb187f1/README.md?plain=1#L61

https://github.com/lostisland/faraday/blob/0580f101ce58a3f0ab4b555af300fe2ccbb187f1/README.md?plain=1#L65

**Docs**

<img width="1920" alt="Screenshot 2023-07-25 at 14 39 26" src="https://github.com/lostisland/faraday/assets/1557529/0b52875a-035c-4673-977d-8fe01a9f3df4">
<img width="1920" alt="Screenshot 2023-07-25 at 14 39 39" src="https://github.com/lostisland/faraday/assets/1557529/748a5bad-cce4-4e18-b42f-860141821901">

https://github.com/lostisland/faraday/blob/0580f101ce58a3f0ab4b555af300fe2ccbb187f1/docs/index.html#L77

**Comment by iMacTia** [comment]
Ah thank you for pointing this out @larouxn, the dead links are from the previous docs website, I'll get those removed 👍
