### ISSUE TITLE
Connecting to unix domain sockets

### ISSUE THREAD

**Issue by hadmut** [lostisland/faraday#1578]
* Faraday Version: 2.10.1
* Ruby Version: 3.2

Hi, 
as REST APIs are increasingly becoming a default standard, more and more REST APIs are offered locally not over TCP, but over unix domain sockets. 

Unfortunately, I could not find a hint in the Faraday docs about how to connect to unix domain sockets. Neither

Faraday.new('/var/snap/lxd/common/lxd/unix.socket').get("/")

nor 

Faraday.new('unix:///var/snap/lxd/common/lxd/unix.socket').get("/")

works. It therefore would be quite useful, if the docs mentioned an example. 

regards

**Comment by olleolleolle** [comment]
The  support depends on the library underneath.

The net_http gem does not support it. Here is an open Ruby feature request about it. https://bugs.ruby-lang.org/issues/17166

The linked https://github.com/puppetlabs/net_http_unix project could be a workaround for you, if you could do without Faraday.

Hope this helps!

**Comment by hadmut** [comment]
No, doesn't help .

And yes, I do know about the Ruby feature request, because I am the one who opened it.

**Comment by olleolleolle** [comment]
Ah, perhaps it'd be possible to author a Faraday adapter that'd wrap that gem, and to use that custom adapter to talk to one's `unix://` sockets?
