### ISSUE TITLE
Add ciphers to SSL options

### ISSUE THREAD

**Issue by womblep** [lostisland/faraday#1581]
I have hit a server where I needed to pin the ciphers to be able to connect. The server is most certainly badly configured but it is not something I can get changed.

I was able to work around this by monkey-patching Faraday and the Faraday Net::HTTP adapter (Net::HTTP supports ciphers) but I would like to submit patches to make it easier to do.

The Faraday change is just adding a "ciphers" member to the SSLOptions

Linked to https://github.com/lostisland/faraday-net_http/issues/44

**Comment by iMacTia** [comment]
As a general rule, we only add new `SSLOptions` if these are general HTTP concepts or supported by most of the Faraday adapters / Ruby HTTP clients.

In this case, we know `Net::HTTP` supports it, and I found evidence of [Typhoeus also supporting it](https://github.com/typhoeus/typhoeus/issues/464).

@womblep would you have time to go through the list of [Faraday adapters](https://github.com/lostisland/awesome-faraday?tab=readme-ov-file#adapters) and check how many of the others also support it?

**Comment by iMacTia** [comment]
async-http was a bit tricky, but I think I found support via the `SSLEndpoint` class: https://github.com/search?q=repo%3Asocketry%2Fasync-io%20cipher&type=code

**Comment by womblep** [comment]
**Excon** - supports
# @option params [String] :ciphers Only use the specified SSL/TLS cipher suites; use OpenSSL cipher spec format e.g. 'HIGH:!aNULL:!3DES' or 'AES256-SHA:DES-CBC3-SHA'
* It needs to be added to [OPTS_KEY ](https://github.com/excon/faraday-excon/blob/main/lib/faraday/adapter/excon.rb#L84)

**HTTPClient** - supports
    # A String of OpenSSL's cipher configuration.  Default value is
    # ALL:!ADH:!LOW:!EXP:!MD5:+SSLv2:@STRENGTH
    # See ciphers(1) man in OpenSSL for more detail.
    attr_config :ciphers
* It needs to be added to [configure_ssl(client, ssl)](https://github.com/lostisland/faraday-httpclient/blob/main/lib/faraday/adapter/httpclient.rb#L95) 

**[Net::HTTP::Persistent](https://github.com/lostisland/faraday-net_http_persistent)** - supports
https://github.com/drbrain/net-http-persistent/blob/master/lib/net/http/persistent.rb#L571
* It needs to be added to https://github.com/lostisland/faraday-net_http_persistent/blob/main/lib/faraday/adapter/net_http_persistent.rb#L180

**Patron** - the adapter doesnt look like it does any SSL options other than verify. The Patron gem doesnt look like it supports ciphers (or many SSL settings)

**HTTP.rb** adapter and gem use OpenSSL SSLContext which support ciphers
* It needs to be added to https://github.com/lostisland/faraday-http/blob/master/lib/faraday/adapter/http.rb#L80

**httpx** - I cant find the source code. I always seem to end up at the wiki so I am not sure if this supports it

**Comment by womblep** [comment]
**Typhoeus** - supported using ssl_cipher_list
* needs to be added to https://github.com/dleavitt/faraday-typhoeus/blob/main/lib/faraday/adapter/typhoeus.rb#L127

**Async::HTTP** - supported - should just work without change to adapter

**EM::HTTP** - supported using cipher_list
* needs to be added to https://github.com/lostisland/faraday-em_http/blob/main/lib/faraday/adapter/em_http.rb#L76 although there are a lot of the options missing it seems

**Comment by iMacTia** [comment]
This was great research, thank you ❤️!
I feel much more confident about adding this directly to Faraday now because it seems like we can get it supported by most adapters 💪

**Comment by iMacTia** [comment]
@womblep FYI – just released Faraday 2.11.0 with support for ciphers (and updated dependency on the `net_http` adapter v3.3 that contains your PR)

**Comment by womblep** [comment]
@iMacTia thanks for the speedy release! ❤️
