### ISSUE TITLE
Celluliod::IO TCPSocket adapter

### ISSUE THREAD

**Issue by rewritten** [lostisland/faraday#164]
I know that Celluloid:IO is still immature in many aspects (SSL support...), but it would be cool to have an adapter for it.

**Comment by dblock** [comment]
It would be nice to reopen this given the availability of EventMachine support in Faraday now, would love to see a Celluloid adapter. There's https://github.com/NOX73/celluloid-http that's fairly straightforward. Ref https://github.com/dblock/slack-ruby-client/issues/87.
