### ISSUE TITLE
Faraday handles repeated query parameters incorrectly

### ISSUE THREAD

**Issue by sporkmonger** [lostisland/faraday#182]
```
>> require 'faraday'
=> true
>> request = Faraday.default_connection.build_request(:get) do |req|
?>   req.url("http://www.example.com/?data=1&data=2")
>> end
=> #<struct Faraday::Request method=:get, path="http://www.example.com/", params={"data"=>["1", "2"]}, headers={}, body=nil, options={:proxy=>nil}>
>> request.to_env(Faraday.default_connection)[:url]
=> #<URI::HTTP:0x0000010287d018 URL:http://www.example.com/?data%5B%5D=1&data%5B%5D=2>
```

I miss the Addressable dependency already...

**Comment by pboling** [comment]
@mislav Is there an example of how to customize the params parser for a Faraday connection to allow for the `data=1&data=2` scenario?  It is a recurring issue in the `oauth2` issue tracker, and I'd like to provide some guidance on a solution, but I don't have much time to dig into Faraday source code.  If there is a handy example you know of please share!

**Comment by iMacTia** [comment]
@pboling did you try the example shown in this https://github.com/lostisland/faraday/issues/182#issuecomment-26064335 ?

**Comment by pboling** [comment]
I had missed it, that’s awesome!  Thank you!
