### ISSUE TITLE
What do you want in Faraday 1.0?

### ISSUE THREAD

**Issue by technoweenie** [lostisland/faraday#202]
- Parameter encoding tweaks. #199
- Use structs for the env, not nested hashes.  #136
- Pull out adapters as separate gems.  Faraday-Typheous, Faraday-Patron, etc.  
- Streaming?  #156  
- New Builder with separate request/response stacks.  Instead of having everything a single stack of modules, have a stack of request and response modules, and a swappable adapter.  This seems to hang people up.  Can we implement this without breaking everyone's code though?

**Comment by marshall-lee** [comment]
Maybe convenient method for constructing a connection pool using `connection_pool` gem?

**Comment by mnussbaumer** [comment]
A in-depth tutorial!

**Comment by iMacTia** [comment]
Closing in favour of #620
