### ISSUE TITLE
Test Faraday 0.9.0 against major libs.

### ISSUE THREAD

**Issue by technoweenie** [lostisland/faraday#229]
I'd love suggestions on other libraries to test against.  If you want to help manage your own Faraday-backed library, I can give you Organization access.  I created a `v0.3.7-faraday-v0.9.0.pre` branch to [test the latest version of Her](https://github.com/lostisland/her/commit/f7b0d88b51a8f3ce13e3846c03c305c2a59a74f5).

* [x] [Her](/remiprev/her) (See autoload issues #230)
* [x] [Octokit](/pengwynn/octokit)
* [x] [Twitter](/sferik/twitter)
* [x] [Sawyer](/lostisland/sawyer) ([diff](https://github.com/lostisland/sawyer/compare/v0.0.7-faraday-v0.9.0.pre))
* [x] [faraday-middleware](/pengwynn/faraday_middleware)
* [x] [faraday-http-cache](/plataformatec/faraday-http-cache)
* [x] [vcr](/vcr/vcr)
* [x] [github-services](/github/github-services)
* [x] [Tinder](https://github.com/collectiveidea/tinder/pull/57)

**Comment by mislav** [comment]
I checked off the remaining items. Closing this outdated issue. Faraday 0.9 is pretty stable now, yo!
