### ISSUE TITLE
Stubbing API Request

### ISSUE THREAD

**Issue by ghost** [lostisland/faraday#232]
Hey Rick,

Instead of having to create and pass in stubs, it would be nice if this was done automatically if none are given. For one, since autoload isn't being used, you have to require the Test adapter to do so. And in either case, having access to the stubs through the Connection would be nice too.

i.e. Instead of

``` ruby
require 'faraday/adapter/test'
@stubs = Faraday::Adapter::Test::Stubs.new
@conn = Faraday.new do |builder|
  builder.adapter :test, @stubs
end
@stubs.get('/foo') { [200, {}, ''] }
@resp = @conn.get('/foo')
```

You could just use

``` ruby
@conn = Faraday.new do |builder|
  builder.adapter :test
end
@conn.stubs.get('/foo') { [200, {}, ''] }
@resp = @conn.get('/foo')
```

The following changes probably better illustrate my point:
https://github.com/burns/faraday/compare/stubbing

I'm not sure this is the correct answer. But since RackBuilder::Handler doesn't instantiate the adapter until the request, I don't see any other option. In fact, the Test adapter creates an instance of Stubs if none are passed in, but I see no way this could be used.

I believe you mentioned you were planning on some changes to RackBuilder and/or the stubbing API, so you may have other ideas. But, thought I'd throw this out there.

**Comment by iMacTia** [comment]
Closing as alternative solution provided above
