### ISSUE TITLE
Faraday not logging POST request body

### ISSUE THREAD

**Issue by alfius** [lostisland/faraday#254]
I'm using the following code to create a connection:

``` ruby
@connection = Faraday.new(HOST, ssl: { verify: true }) do |faraday|
  faraday.request :url_encoded
  faraday.response :logger
  faraday.adapter Faraday.default_adapter
end
```

Then, I'm performing a post in this way:

``` ruby
@connection.post do |request|
  request.url "#{my_uri.path}?#{my_uri.query}"
  request.headers['Content-Type'] = 'application/json'
  request.body = my_object.to_json
end
```

The request works fine. The problem is that I'm not seeing the request body in the logs, only the request url.

**Comment by henrik** [comment]
Since I found this through Google: this is now supported:

```
require "logger"

Faraday.new do |faraday|
  faraday.response :logger, ::Logger.new(STDOUT), bodies: true
```

**Comment by vemv** [comment]
This doesn't seem to work for `url_encoded` requests?

**Comment by iMacTia** [comment]
Hi @vemv, the order of middlewares is extremely important in Faraday.
Can you please provide your conneciton initialization code and try to explain better why it "doesn't seem to work for `url_encoded` requests"?
What's the output that you get and what is the expected one?

**Comment by jpickwell** [comment]
I know this is old, but did it not occur to anyone that the OP is logging the response: `faraday.response :logger`.

**Comment by iMacTia** [comment]
@jpickwell you use `faraday.response` because the `logger` middleware is registered as a response middleware. In reality, it logs both requests and responses 😄

**Comment by davidalpert** [comment]
just came across this; by [this line](https://github.dm.nfl.com/api/v3/repos/NFL/nfl-jenkins-chef/pulls/103/comments) it appears that you need to pass two args to see the request body:
```
Faraday.new do |faraday|
  faraday.response :logger, ::Logger.new(STDOUT), body: true, bodies: { request: true, response: true }
end
```

**Comment by iMacTia** [comment]
@davidalpert that's not necessary, you can simply pass the `bodies: true` to enable them both, or use the separate values like in the example above to have more control.
I see there's a `body: true` option in that example, but that's not a valid option unfortunately (maybe they got the plural wrong?)
