### ISSUE TITLE
Ability to configure net http persistent client

### ISSUE THREAD

**Issue by ajsharp** [lostisland/faraday#262]
Currently, it's not possibly through the api to configure the `idle_timeout`, because the faraday net http persistent adapter instantiates a new `Net::HTTP::Persistent` instance on each request. The library is smart enough to use the same connection across instances for performing http requests, but it configuration options such as `idle_timeout` must be configured on a per-object basis. Has this been an issue with other adapters, that needed custom configuration passed to it? Thanks.

**Comment by iMacTia** [comment]
This is now implemented and released as of v0.11.0 😃 
See https://github.com/lostisland/faraday#ad-hoc-adapters-customization for details
