### ISSUE TITLE
v0.9.0 regressions

### ISSUE THREAD

**Issue by technoweenie** [lostisland/faraday#266]
Just jotting down some changes when upgrading [github/github-services](/github/github-services) to Faraday 0.9.  

* Various constant missing errors under `Faraday::Adapter`, `Faraday::Request`, `Faraday::Response`
  * Add `require 'faraday/autoload'` or use `Faraday::Adapter.load_middleware(:foo)`.
* Cannot pass unused options.
* Cannot add arbitrary keys to `Faraday::Env`
* URI validation is much more strict.
* Parsed URIs now have default ports (80 and 443), instead of nil.
* `Faraday::Utils.build_query` returns nil if passed nil.'

See [the actual diff](https://github.com/github/github-services/compare/faraday-0.9).

/cc #229

**Comment by mislav** [comment]
@technoweenie Now that significant time has passed, do you think any of the above items still need attention/fixing?
