### ISSUE TITLE
Patron file upload

### ISSUE THREAD

**Issue by arr-dev** [lostisland/faraday#281]
When using `:patron` as adapter, file upload to Paperclip-backed Rails application doesn't work.

It works fine when using `:net_http` adapter.

I've used the example from README, just changing the adapter.

**Comment by bombazook** [comment]
Same bug for put requests. Patron sends only metadata but no contents, so receiver drops connection by timeout.
ruby 2.1.1p76 
faraday 0.8.9
patron 0.4.19.beta.2

Maybe it is related to https://github.com/toland/patron/issues/12

**Comment by julik** [comment]
This has been fixed in Patron, so might be resolved in Faraday (we use Patron directly without Faraday in-between, so can't promise anything).

**Comment by iMacTia** [comment]
Thanks for the update @julik!

Either way this issue is very old. So given this was recognised as a Patron bug I would prefer to close the issue.

Of course if there's still any issue regarding Faraday, it can be reopened.
