### ISSUE TITLE
POST body is lost with Retry middleware

### ISSUE THREAD

**Issue by eric** [lostisland/faraday#297]
When retrying an HTTP POST the `env[:body]` of the request is overwritten by the failed response body.

This causes the retried operation to send a blank body.

This is one [workaround](https://github.com/librato/librato-metrics/blob/f18abf1f6e8a6a98f0908890308070e20d626431/lib/librato/metrics/middleware/retry.rb#L12-L18) for the issue.

**Comment by mislav** [comment]
Resolved in 1316f4c.
