### ISSUE TITLE
[NET::HTTP] Faraday Throws Error When Setting SSL Version

### ISSUE THREAD

**Issue by jzanutto** [lostisland/faraday#309]
Ruby Version 1.8.7

Net HTTP does not support ssl_version setting before ruby 1.9.3. Setting this in 1.8.7 throws errors.

`undefined method 'ssl_version=' for #<Net::HTTP [REDACTED] open=false>
~/gems/faraday-0.8.4/lib/faraday/adapter/net_http.rb:96:in 'configure_ssl'`

Note this is for Faraday version 0.8.4 however I still see this same line of code in master.

**Comment by iMacTia** [comment]
Closing as ruby <1.9.3 is not supported anymore
