### ISSUE TITLE
net_http_persistent Adapter Makes 2 Requests?

### ISSUE THREAD

**Issue by benhamill** [lostisland/faraday#314]
I've got a test script:

``` ruby
require 'faraday'
require 'net/http/persistent'
require 'webmock'
require 'webmock/rspec'
require 'rspec'

WebMock.disable_net_connect!

describe "WebMock" do
  let (:uri) { "http://example.com" }

  before do
    WebMock.stub_request(:get, uri).to_return(body: 'body')
  end

  context "and bare Net::HTTP::Persistent" do
    before do
      Net::HTTP::Persistent.new('example', URI.parse(uri)).request(URI(uri))
    end

    it "makes only one request" do
      expect(WebMock).to have_requested(:get, uri)
    end
  end

  context "and Faraday with the net_http_persistent adapter" do
    before do
      Faraday.new(uri).tap do |f|
        f.adapter :net_http_persistent
      end.get
    end

    it "makes only one request" do
      expect(WebMock).to have_requested(:get, uri)
    end
  end
end
```

When run, the Faraday-based test fails because it makes two requests, thusly:

```
GET http://example.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v0.8.8'} was made 1 time
GET http://example.com/ with body 'body' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Keep-Alive'=>'30', 'User-Agent'=>'Faraday v0.8.8'} was made 1 time
```

The request made in the first test (that just uses Net::HTTP::Persistent directly) looks like this:

```
GET http://example.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Keep-Alive'=>'30', 'User-Agent'=>'Ruby'} was made 1 time
```

This seems weird to me... I can't figure out what Faraday might be doing in that adapter that's significantly different from the above test. Can anyone point me in the right direction to further investigate? Why does the second request have the body from the _reponse_ I set in WebMock? Why doesn't the first request have the keep-alive stuff?

I will gladly write a Pull Request, if someone can help me figure out what's going wrong.

**Comment by litch** [comment]
This is pretty special.  This issue just bit us too.  If there is no conceivable use case for this, then it seems like maybe something that should be pulled?  Or something?  That's a pretty [astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) outcome for having an extra `tap` there

**Comment by mislav** [comment]
@litch I'm sorry that you had trouble and I can totally see how these issues are easy to fall into and hard to debug. We're aware that the API for Faraday is not perfect. This might improve in future major releases, where you will be warned if you didn't specify an adapter, or you specified more than one adapter, but the current versions of Faraday (0.8 and 0.9) will remain with the same behavior because we don't want to introduce potentially backwards-incompatible changes to them.
