### ISSUE TITLE
Help writing middleware

### ISSUE THREAD

**Issue by jwaldrip** [lostisland/faraday#334]
It seems to me from the documentation that the following should work. But it doesn't. The docs are poor for writing middleware. In lieu of that can someone lend some assistance.

``` ruby
# play.rb
require 'faraday'

class MyMiddleware

  attr_reader :options

  def initialize(app, options={})
    @app = app
    @options = options
  end

  def call(env)
    @app.call(env)
  end

end

# This doesn't seem to work either, removing for now.
# Faraday.register_middleware :request, my_middlware: lambda { MyMiddleware }

client = Faraday.new do |conn|
  # conn.request :my_middleware, foo: :bar
  conn.request MyMiddleware, foo: :bar
end

response = client.get('http://jasonwaldrip.com/')
```

```
$ ruby play.rb
/Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday.rb:64:in `lookup_middleware': MyMiddleware is not registered on Faraday::Request (RuntimeError)
    from /Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday/builder.rb:146:in `use_symbol'
    from /Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday/builder.rb:100:in `request'
    from play.rb:19:in `block in <main>'
    from /Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday/connection.rb:65:in `initialize'
    from /Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday.rb:11:in `new'
    from /Users/jwaldrip/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/faraday-0.8.9/lib/faraday.rb:11:in `new'
    from play.rb:18:in `<main>'
```

**Comment by nodox** [comment]
What did you final setup look like?

**Comment by iMacTia** [comment]
@stefansedich not sure if there was any direct follow up or improvement after this discussion, but we're planning to do some heavy work on the documentation together with the next major release (1.0) so hopefully this won't be a problem in future again.

**Comment by maxim** [comment]
Would be great if someone posted what exactly registering looks like in this issue for now.

**Comment by iMacTia** [comment]
@maxim We now have an official [website](https://lostisland.github.io/faraday/) with some documentation around [middleware](https://lostisland.github.io/faraday/middleware/), however it's still improving.

In short, `request` and `response` should only be used for registered middleware, if you need to inject a custom-built one is just easier to call `.use`.
So in the example above, the following would work:

```ruby
client = Faraday.new do |conn|
  conn.use MyMiddleware, foo: :bar
end
```

**Comment by dishcandanty** [comment]
A full simple example would go a long way for the documentation.

**Comment by wilsonsilva** [comment]
> @maxim We now have an official website with some documentation around middleware, however it's still improving.
>
> In short, request and response should only be used for registered middleware, if you need to inject a custom-built one is just easier to call .use.
>So in the example above, the following would work:
>```
> client = Faraday.new do |conn|
>   conn.use MyMiddleware, foo: :bar
> end
>```

@iMacTia That's not in the documentation but it is essential. Perhaps it could be in https://lostisland.github.io/faraday/middleware/custom

**Comment by iMacTia** [comment]
@wilsonsilva you're totally right, that would definitely be a good improvement 😅. I'm surprised it was missed to be fair
