### ISSUE TITLE
faraday 0.9.0 can't use in jruby mode 2.0

### ISSUE THREAD

**Issue by mimosa** [lostisland/faraday#348]
`gem install faraday` 

`jruby --2.0 -S pry`

``` ruby
require 'faraday'
conn = Faraday.new(url: 'http://open.shou65.com')
response = conn.get '/weather.json'
response.body # Nothing
```

replace adapter is work :100: 
`Faraday.default_adapter = :httpclient`

1.9 is ok :+1:

**Comment by iMacTia** [comment]
Closing as this should now be handled in 280f08a3b282ef571b113b688623fef35fb65bc7.
