### ISSUE TITLE
Adding :ssl options to an existing Faraday::Request

### ISSUE THREAD

**Issue by AnalogJ** [lostisland/faraday#351]
Hi,
I'm using a gem that generates `Faraday::Request` objects with all the proper headers and parameters to communicate with an OAuth1 API. However I'm now working with another OAuth1 API which requires a client ssl certificate to be specified, in addition to the OAuth options. 
I found a link on http://www.sitepoint.com/inter-service-communication-using-client-certificate-authentication/ that describes how to use Faraday with the `:ssl` option to specify client certificates  in the connection constructor, however the gem I'm using returns a `Faraday::Request` object already. 

Is there a way to set the :ssl options on an existing `Faraday::Request` ?
I've tried looking at http://rubydoc.info/gems/faraday/0.9.0/Faraday/Request and I haven't found any applicable methods.

**Comment by mislav** [comment]
@AnalogJ You should be able to do something like this:

```rb
request.env[:ssl][:client_cert] = ...
request.env[:ssl][:client_key] = ...
```

Sorry for the late response!
