### ISSUE TITLE
URL Parameters swap in .9.0

### ISSUE THREAD

**Issue by noahc** [lostisland/faraday#353]
When I run my code in .9 the url parameters are switched around, which causes all sorts of issue for the API I'm using. When I downgrade to version .8.8 it seems to work again.

9.0 gives me Outputformat=json&ReadViewEntries=%0D%0D

But, 8.8 gives me ReadViewEntries&Outputformat=json

Any thoughts on why this is occurring? The only change is that I'm changing the version number in gem file from .8.8 to .9 and running bundle update.

**Comment by nicknux** [comment]
I've added a sort_params= method to Faraday::Connection. The sort_params= method takes in a boolean which indicates whether to sort request parameters.

I've created a pull request https://github.com/lostisland/faraday/pull/469.

Sample use:
```ruby
@conn ||= Faraday.new do |c|
      c.request :url_encoded
      c.response :logger
      c.adapter Faraday.default_adapter
      c.sort_params = false
    end
```

**Comment by mislav** [comment]
Sorry for a late reply everyone.

If you need to tailor the params encoding style to the quirks of a particular server implementation, you can always use the `params_encoder` option to specify an object that will handle encoding of params. See https://github.com/lostisland/faraday/issues/433#issuecomment-61737350 for example.

**Comment by jessevdp** [comment]
If you land here far far in the future... there seems to be some solution:

https://lostisland.github.io/faraday/#/customization/index?id=order-of-parameters
