### ISSUE TITLE
uninitialized constant EventMachine::Connectify

### ISSUE THREAD

**Issue by blakedy** [lostisland/faraday#385]
Looks like em-connectify is not included in Faraday 0.9.0 release. It is referenced by lib/faraday/adapter/em_synchrony.rb and lib/faraday/adapter/em_http.rb. Should it be included as dependency in the gemspec?

**Comment by chagar** [comment]
Since EventMachine is one adapter among many, which is not required to use Faraday, the gem should not have a strict dependency on libraries required by the EM adapters.
