### ISSUE TITLE
Net::ReadTimeout while updating the users profile

### ISSUE THREAD

**Issue by YOUConsulting** [lostisland/faraday#387]
Dear,

A customer of ours has experienced random Faraday::Error::TimeoutError: Net::ReadTimeout while a user updates his profile to a remote webservice. 

Backtrace:

/usr/lib/ruby/2.0.0/net/protocol.rb:158→ rescue in rbuf_fill
/usr/lib/ruby/2.0.0/net/protocol.rb:152→ rbuf_fill
/usr/lib/ruby/2.0.0/net/protocol.rb:134→ readuntil
/usr/lib/ruby/2.0.0/net/protocol.rb:144→ readline
/usr/lib/ruby/2.0.0/net/http/response.rb:39→ read_status_line
/usr/lib/ruby/2.0.0/net/http/response.rb:28→ read_new
/usr/lib/ruby/2.0.0/net/http.rb:1406→ block in transport_request
/usr/lib/ruby/2.0.0/net/http.rb:1403→ catch
/usr/lib/ruby/2.0.0/net/http.rb:1403→ transport_request
/usr/lib/ruby/2.0.0/net/http.rb:1376→ request
newrelic_rpm-3.6.8.168/lib/new_relic/agent/instrumentation/net.rb:30→ block in request_with_newrelic_trace
newrelic_rpm-3.6.8.168/lib/new_relic/agent/cross_app_tracing.rb:43→ trace_http_request
newrelic_rpm-3.6.8.168/lib/new_relic/agent/instrumentation/net.rb:29→ request_with_newrelic_trace
/usr/lib/ruby/2.0.0/net/http.rb:1369→ block in request
/usr/lib/ruby/2.0.0/net/http.rb:852→ start
/usr/lib/ruby/2.0.0/net/http.rb:1367→ request
newrelic_rpm-3.6.8.168/lib/new_relic/agent/instrumentation/net.rb:33→ request_with_newrelic_trace
faraday-0.8.8/lib/faraday/adapter/net_http.rb:75→ perform_request
faraday-0.8.8/lib/faraday/adapter/net_http.rb:38→ call
faraday_middleware-0.8.8/lib/faraday_middleware/response_middleware.rb:30→ call
faraday-0.8.8/lib/faraday/response.rb:8→ call
faraday-0.8.8/lib/faraday/connection.rb:253→ run_request
faraday-0.8.8/lib/faraday/connection.rb:118→ post
lib/sap.rb:85→ perform_request
lib/sap.rb:103→ post
lib/sap.rb:336→ update_profile

Perform_request code

    def perform_request(verb, path, params = nil, body = nil)
      conn = connection.dup
      params ||= {}
      # If params contains a token, it will used the `named` routes and
      # set an authorization header
      if params[:token]
        path = ["named", path].join("/")
        conn.headers["Authorization"] = "Basic #{params.delete(:token)}"
      else
        path = ["anonymous", path].join("/")
      end

      # All requests need to specify their sap client.
      params = (params || {}).merge("sap-client" => sap_client_id)

      # Sap expects each body sent to it to be xml-encoded.
      conn.headers["Content-Type"] = "application/xml"
      conn.send(verb, path) do |request|
        log "Path   : #{verb.upcase} #{default_url}#{path}"
        log "Params : #{params.inspect}"
        # log "Body   : #{body.inspect[0..1000]}"

        request.params = params if params
        request.body = body if body
        request.options[:timeout] = 120          # open/read timeout in seconds
        # request.options[:open_timeout] = 15      # connection open timeout in seconds
      end
    end

More information:
If we watch the users params, all the content they supplied is valid and this error occured 10 times in 6700 users.

Versioning:
    faraday (0.8.8)
      multipart-post (~> 1.2.0)
    faraday_middleware (0.8.8)
      faraday (>= 0.7.4, < 0.9)
Rails 3.2.17

**Comment by kennethkalmer** [comment]
Maybe the SAP system took more than 120 seconds to respond...

Could you please clarify how this problem is related to Faraday? I understand you're using the library, but I fail to see how Faraday is at fault here...

**Comment by YOUConsulting** [comment]
We have indeed fixed this by setting the timeout to 200 seconds.

I will close this Topic.

**Comment by davidmukiibi** [comment]
am experiencing the same issue. this time am running seeds to a remote database and i 3 of my seeds keep timing out with the same error. Net::ReadTimeout, and i doubt if my database or my ruby code is at fault here.... how can i set the timeout for new relic?
additional error: /gems/ruby/2.4.0/gems/newrelic_rpm-4.0.0.332/lib/new_relic/agent/instrumentation/net.rb:33:in `block in request_with_newrelic_trace'
@DelawareConsulting
