### ISSUE TITLE
Question: is there a way to configure how params with multiple values are encoded in the URL?

### ISSUE THREAD

**Issue by gonzofy** [lostisland/faraday#398]
Use case is that there is a REST service I want to hit where they want multiple values for a param to be e.g.:

http://foo.com?param=foo&param=bar&param=baz

Using Faraday I have:

```
connection = Faraday.new do |faraday|
  faraday.adapter(Faraday.default_adapter) # make requests with Net::HTTP
end
connection.get do |request|
        request.url(url, params)
end
````

Thanks!
-Rob

**Comment by mislav** [comment]
Please see [this example in the README](https://github.com/lostisland/faraday/blob/257b9a82b801b487ec3dff4bf275ad2018d4fcc9/README.md#changing-how-parameters-are-serialized)

```rb
conn = Faraday.new :params_encoder => Faraday::FlatParamsEncoder
conn.get "http://example.com", :param => ["foo", "bar", baz"]
# GET http://example.com/?param=foo&param=bar&param=baz
```

**Comment by jasonwbarnett** [comment]
For anyone else who is finding this 7 years later, this has changed and is documented here: https://lostisland.github.io/faraday/#/customization/index?id=changing-how-parameters-are-serialized

I just searched for Faraday::FlatParamsEncoder in the git repo to find the docs.
