### ISSUE TITLE
`register_middleware` and namespaces

### ISSUE THREAD

**Issue by foca** [lostisland/faraday#410]
I spent a while figuring out a bug in our application, that came from two separate gems (https://github.com/diffbot/diffbot-ruby-client and https://github.com/sferik/twitter) registering the same response middleware.

I sent PRs to both projects to address the immediate issue by just prefixing their middleware with the library name, but I'm unsure what's the best way to fix this in library code, so I'm opening this issue for discussion :)

See https://github.com/sferik/twitter/pull/610 and https://github.com/diffbot/diffbot-ruby-client/pull/2

**Comment by mislav** [comment]
No, right now I'm not motivated to enchance any of the middleware registry functionality since it's already a bit convoluted. If users want simplicity, they can mount the middleware directly using fully qualified constants without referencing their names.
