### ISSUE TITLE
Default request timeout value?

### ISSUE THREAD

**Issue by subvertallchris** [lostisland/faraday#417]
Rather than setting a timeout per request, is it possible to set a default across all connections opened within a session?

**Comment by kylev** [comment]
Since I see very few correct mentions of this elsewhere, the builder version of this in 0.9.2 is this, with the options attribute being the request option defaults:

```ruby
 Faraday::Connection.new('https://api.something.io') do |builder|
      builder.options[:open_timeout] = 2
      builder.options[:timeout] = 2
      builder.adapter Faraday.default_adapter
    end
```

**Comment by neohunter** [comment]
Both examples explain how to set per request, How I can set globally?

**Comment by iMacTia** [comment]
@neohunter the [example](https://github.com/lostisland/faraday/issues/417#issuecomment-56569385) above will set it for each request done from that connection. Faraday doesn't currently support a global setting for all connections, but that shouldn't really be necessary as the number of connections you manage should be just a few (actually, only one in most cases).
