### ISSUE TITLE
Reason Phrases on the Response object

### ISSUE THREAD

**Issue by davidbiehl** [lostisland/faraday#418]
I'm working with an API that uses "descriptive" reason phrases in the status of the response. An example:

    HTTP/1.1 400 Wrong JSON format: A JSONObject text must begin with '{' at 1 [character 2 line 1]

There doesn't appear to be a way to obtain the reason phrase from the response object, just the status as a number (400 in the example above).

Looking at the [The HTTP/1.1 RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1) we see ...

> The reason phrases listed here are only recommendations -- they MAY be replaced by local equivalents without affecting the protocol.

It seems like it would be reasonable to make them available on the response object with a `#reason_phrase`, or similar, method.

**Comment by sbleon** [comment]
This is an old issue, and a fix is implemented in #547, so I'm closing it.
