### ISSUE TITLE
catch Errno::ETIMEDOUT and raise Faraday::Error::TimeoutError with net/http adapter

### ISSUE THREAD

**Issue by mcfiredrill** [lostisland/faraday#424]
In my code today I had to catch `Errno::ETIMEDOUT` exceptions even though I am already catching `Faraday::Error::TimeoutError` exceptions. Would it make sense to catch `Errno::ETIMEDOUT` in the net/http adapter and re-raise it as `Faraday::Error::TimeoutError` in the net/http adapter? I noticed the em_http adapter already does this:
https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/em_http.rb#L157

I would be willing to write a test to reproduce the issue.

**Comment by mislav** [comment]
Fixes in f73d13e
