### ISSUE TITLE
Faraday.get and basic auth

### ISSUE THREAD

**Issue by jordansissel** [lostisland/faraday#426]
I can't seem to get `Faraday.get` to accept the user:pass@host syntax from a url and respect it.

Reproducing with Faraday 0.9.0

```ruby
Faraday.get("http://foo:bar@localhost:3333/test")
```

The "server"

```
% nc -l localhost 3333
GET /test HTTP/1.1
User-Agent: Faraday v0.9.0
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: */*
Connection: close
Host: localhost:3333
```

I expected an Authentication header, or perhaps an error that auth wasn't supported.

I couldn't find docs on the `Faraday.get` method on rubydoc.info for the Faraday module: http://www.rubydoc.info/gems/faraday/Faraday - so I'm not sure what I'm doing wrong.

If you point me in the write direction, I am happy to write documentation for this method.

**Comment by O-I** [comment]
There are several ways you can set authentication headers with Faraday. One way is to initialize a `Faraday::Connection` instance and use the `basic_auth` helper method:

```ruby
conn = Faraday.new(url: 'http://example.com') # create a new Connection with base URL
conn.basic_auth('user', 'pass')               # set the Authentication header
conn.get('/foo')                              # GET http://example.com/foo
```

You could also use middleware:

```ruby
conn = Faraday.new(url: 'http://example.com') do |builder|
  builder.use Faraday::Request::Retry
  builder.use Faraday::Request::BasicAuthentication, 'user', 'pass'
  builder.use Faraday::Response::Logger
  builder.use Faraday::Adapter::NetHttp
end

conn.get('/foo')
```

or:

```ruby
Faraday.new(url: 'http://example.com') do |builder|
  builder.request  :retry
  builder.request  :basic_authentication, 'user', 'pass'
  builder.response :logger
  builder.adapter  :net_http
end

conn.get('/foo')
```

Intridea has a nice blog post on [basic Faraday usage](http://www.intridea.com/blog/2012/3/12/faraday-one-http-client-to-rule-them-all) that's a few years old but still relevant.

Hope it helps some,
O-I

**Comment by mislav** [comment]
Thanks @O-I for the helpful examples.

@jordansissel For now, please use this form:

```rb
conn = Faraday.new('http://example.com')
conn.basic_auth('user', 'pass')
conn.get('/foo')
```

Sorry for the trouble.

**Comment by jordansissel** [comment]
Thanks for the pointers, all! It helped me get things working. ❤️❤️❤️

**Comment by mislav** [comment]
This was also reported as #343.

**Comment by grosser** [comment]
`Faraday.get('http://localhost:3000', nil, authorization: "Bearer 1123")`

**Comment by simon1tan** [comment]
That did not work, try "Request::BasicAuth"
conn = Faraday.new(url: 'http://example.com') do |builder|
  builder.use Faraday::Request::Retry
  builder.use Faraday::Request::BasicAuth, 'user', 'pass'
  builder.use Faraday::Response::Logger
  builder.use Faraday::Adapter::NetHttp
end

**Comment by iMacTia** [comment]
@simon1tan the auth middleware recently changed, could you please report this in a separate new issue specifying which version of Faraday you're using and the error message you see, if any?

**Comment by jonesnc** [comment]
I think the `basic_auth` method has been renamed to [`set_basic_auth`](https://www.rubydoc.info/gems/faraday/Faraday%2FConnection:set_basic_auth) in more recent versions.
