### ISSUE TITLE
Faraday does not parse URLs correctly

### ISSUE THREAD

**Issue by comandeo** [lostisland/faraday#428]
Code example below:

```ruby
# Correct behaviour (Net::HTTP)
uri = URI.parse('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL')
response = Net::HTTP.get_response(uri)
puts response.code # 200
puts response.body # WSDL content

# Incorrect behaviour
connection = Faraday.new('http://www.webservicex.net')
faraday_response = connection.get('/CurrencyConvertor.asmx?WSDL')
puts faraday_response.status # 500
puts faraday_response.body # Error message
```

After some investigation I found that URL `http://www.webservicex.net/CurrencyConvertor.asmx?WSDL` is being converted into `URL:http://www.webservicex.net/CurrencyConvertor.asmx?WSDL=` with and additional symbol `=` at the end.

```ruby
puts faraday_response.env.url # http://www.webservicex.net/CurrencyConvertor.asmx?WSDL=
``` 

Seems that `Faraday::NestedParamsEncoder.decode` method considers query string `?WSDL` as a parameter with empty value.

```ruby
uri = URI.parse('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL')
decoded_query = Faraday::NestedParamsEncoder.decode(uri.query) # =>  {"WSDL"=>nil}
Faraday::NestedParamsEncoder.encode(decoded_query) # => "WSDL="
```

Since URLs of such kind a quite typical for WSDLs of web services, it would be great if we could find a solution for this issue.

**Comment by PadraigK** [comment]
Adding an `=` should certainly be considered a bug. Here is an example URL where the additional `=` causes an undesirable redirect: `http://jayu.universpodcast.com/feed/?lang`
