### ISSUE TITLE
picky server having problems with multipart form headers

### ISSUE THREAD

**Issue by vikstrous** [lostisland/faraday#436]
I'm having problems using Faraday to communicate with a picky server. The server requires a multipart form, but the form must be encoded in a very particular way and Faraday doesn't seem to have any way to let me do this if I don't encode the request myself.

The main issue is that I don't seem to have control over the headers sent inside a "part". I need these headers and no more:

```
Content-Disposition: form-data; name="fieldname"; filename="filename"
Content-Type: application/octet-stream
```

But by default when I use this:

```
c = Faraday.new(...) do |conn|
  conn.request :multipart
  conn.request :url_encoded
  conn.adapter :net_http
end
payload = { 'Filedata' => Faraday::UploadIO.new('filename', 'application/octet-stream') }
c.post '/url', payload
```

I get these headers inside the "part":

```
Content-Disposition: form-data; name="fieldname"; filename="filename"
Content-Length: <length>
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary
```

Is there any way for me to control what headers Faraday puts in there? If not, that would be a very useful feature. Right now I just have to manually construct the body.

**Comment by technoweenie** [comment]
As long as the `multipart-post` gem is creating valid multipart bodies, I don't see a reason to add complex options to disable valid headers in a mime part.  What's the specific problem?  Does your picky server have issues handling Content-Length or Content-Transfer-Encoding headers?  It can't be fixed with a compliant multipart parser?

**Comment by vikstrous** [comment]
I'm not working on that project any more, so I'm not interested in investigating this further. I worked around the problem by packing the multipart form myself, so it's not an issue for me any more. If you want to investigate this, the picky server is Nessus 5 (and maybe 6); more specifically, the upload API.
