### ISSUE TITLE
Adding HTTP_ to custom headers

### ISSUE THREAD

**Issue by awsmsrc** [lostisland/faraday#439]
I can see in the code it looks like this is intentional?

Any feedback as to why as this caught me out quite badly

**Comment by wallace** [comment]
:+1:

**Comment by technoweenie** [comment]
I think that came from Rack.  It's too big of a change to make to Faraday without breaking everything.  I'd look at using Hurley, which has a lot of the core mistakes from Faraday solved: https://github.com/lostisland/faraday/issues/454

**Comment by mislav** [comment]
I don't understand what the original question refers to. We don't change any header names in Faraday::Utils::Headers hash, and we forward `env[:request_headers]` that to adapters without changes. The only exception is Rack adapter, for obvious reasons: Rack expects most headers to be prefixed with `HTTP_`.
