### ISSUE TITLE
Issue with a string keys in Faraday::Connection options

### ISSUE THREAD

**Issue by aliaksandrb** [lostisland/faraday#444]
Hi!
Recently faced a bug which reproduces by the gem that uses Faraday as dependency ([elasticsearch-ruby](https://github.com/elasticsearch/elasticsearch-ruby) to be more precise).
Simplified situation and steps to reproduce:
According to docs `Faraday::Connection` [allows](https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L46) passing the `options` argument that should be "Hash or `Faraday::ConnectionOptions`"
Lets check this:

```
conn = Faraday::Connection.new 'http://sushi.com', { :request => { :timeout => 5 } }
# => Faraday::Connection
conn.get 'nigiri'
# => Faraday::Response
conn.options
# => <Faraday::RequestOptions timeout=5>
```

Everything fine!
But what if the keys in options hash are strings?

```
conn2 = Faraday::Connection.new 'http://sushi.com', { "request" => { "timeout" => 5} }
# => Faraday::Connection
conn2.get 'nigiri'
# => NoMethodError: undefined method `params_encoder' for {"timeout"=>5, :proxy=>nil}:Hash
    from ~/.rvm/gems/ruby-2.1.5@yocto/gems/faraday-0.9.0/lib/faraday/request.rb:58:in `url'
    from ~/.rvm/gems/ruby-2.1.5@yocto/gems/faraday-0.9.0/lib/faraday/connection.rb:371:in `block in run_request'
    from ~/.rvm/gems/ruby-2.1.5@yocto/gems/faraday-0.9.0/lib/faraday/connection.rb:388:in `block in build_request'
....
conn.options
# => {"timeout"=>5}
```

Fail! And Elasticsearch just can't connect to it's server and nothing is working :(

I believe that in [faraday/options.rb](https://github.com/lostisland/faraday/blob/d8b9eda2d2d156c8e088337900636aa1b319e8bc/lib/faraday/options.rb#L19) suboptions defined as symbols:

```
...
options :request => RequestOptions, :ssl => SSLOptions
...
```

so `#update` method just could not find it:

``` ruby
    def update(obj)
      obj.each do |key, value|
    ******if sub_options = self.class.options_for(key)******
          value = sub_options.from(value) if value
        elsif Hash === value
          hash = {}
          value.each do |hash_key, hash_value|
            hash[hash_key] = hash_value
          end
          value = hash
        end

        self.send("#{key}=", value) unless value.nil?
      end
      self
    end
```

I have send a [PR with small fix](https://github.com/lostisland/faraday/pull/445) an test that covers such situations.

**Comment by aliaksandrb** [comment]
@technoweenie yeah, but I believe that if the docs allows passing the options argument as Hash, and Ruby in turn allows String hash keys maybe it is a good idea to prevent unexpected behavior?

Anyway it's not my personal demand (I prefer symbol keys personally) but a detected issue while using another gem, dependent from Faraday.

**Comment by mislav** [comment]
@technoweenie I don't think we should support string keys. Instead, we could make the Env object raise exceptions if it encounters string keys. So that this sort of violation is more visible.

**Comment by Startouf** [comment]
I am parsing the configuration from a yml file and the hash comes out naturally with string keys. Would be nice to have either a better error explanation or to handle the conversion automatically.

**Comment by iMacTia** [comment]
As said before, Faraday only supports symbols as keys in this case.
Solution here is to either use directly symbols or, if you're in the same case as @Startouf, you can use `deep_symbolize_keys`.

The only contribution we would accept in this case would be a clearer error in case string keys are passed. Happy to eventually review a PR that address this.

Closing
