### ISSUE TITLE
Feature Request: Perform Requests Lazily

### ISSUE THREAD

**Issue by shaqq** [lostisland/faraday#449]
It looks like when you do:

```ruby

conn = Faraday.new
response = conn.get 'http://sushi.com'

# Request is made without me asking for data!
```

Similar to [Typhoeus](https://github.com/typhoeus/typhoeus), it'd be nice if we could distinguish building a request (via `Faraday.new`), and performing a request. It would add a more fine-tuned control over Faraday should we decide to use it, as well as potentially cleaning up code logic.

**Comment by technoweenie** [comment]
Faraday is in maintenance mode only.  See #454.

FWIW you can do this in [Hurley](/lostisland/hurley):

```ruby
client = Hurley::Client.new
req = client.request(:get, "http://sushi.com")

# actually make the request
res = client.call(req)
```

Does this work for you?  If you think Hurley should do this differently, can you file an issue there with details of how you'd like it to work?

**Comment by shaqq** [comment]
Ah, wasn't aware that it was in maintenance mode. That API with Hurley seems odd though.

I'll make an issue there.
