### ISSUE TITLE
Adding some privacy to adapters

### ISSUE THREAD

**Issue by Ben-M** [lostisland/faraday#453]
Hey,

I noticed that many adapter methods which look like implementation details are public, instead of private. This makes them implicitly part of your API.

As you move toward 1.0 this could lead to some serious Semantic Versioning headaches. For instance, if you wanted to refactor an adapter and remove/change/rename one of these methods you'll need a major version bump to show that you are making incompatible API changes.

Is there a reason for them to be public that I'm missing?

If not, two approaches come to mind:

1. Add deprecation notices to all the should-have-been private methods if they are used directly, and them make them private for the next big release. This will add some ugliness to the code.
2. Make them private in the next version and hope you don't get too many complaints. If people complain then have them use the old version or temporarily use :send. Yuck.

Would you be open to pull requests taking either of these approaches?

Ben

**Comment by technoweenie** [comment]
Hey Ben, see #454.  As far as Faraday goes, I'm not sure I'll ever push it to 1.0.  You're welcome to push access to Faraday to do what you feel is best.  If you like the direction [Hurley](/lostisland/hurley) is going, you're welcome to push access there too :)

**Comment by Ben-M** [comment]
Well... that wasn't the response I expected :)

If Faraday is moving into maintenance mode and the community adopts Hurley then I'd suggest leaving things as they are. If we don't expect to see many changes to Faraday going forward then this isn't worth the pain it would cause contributors or gem users.

Push access would be great (both for Faraday and Hurley), thanks! I can't promise how active I'll be at this point. Even with push access I'll probably send my own code as pull requests to get some outside input.

**Comment by technoweenie** [comment]
> Push access would be great (both for Faraday and Hurley), thanks! I can't promise how active I'll be at this point. Even with push access I'll probably send my own code as pull requests to get some outside input.

Sounds perfect.  I typically file PRs too once the project is out of the initial mad hacker stage.
