### ISSUE TITLE
FaradayMiddleware::FollowRedirects didn't work

### ISSUE THREAD

**Issue by roroco** [lostisland/faraday#456]
i try to follow redirect but it didn't work and response.body is nil

this is my code:

```
require 'faraday'
require 'faraday_middleware'

h = Faraday.new do |c|
  c.adapter :httpclient
  c.use FaradayMiddleware::FollowRedirects
end

r = h.get("https://www.google.com").body
puts "r.inspect:#{r.inspect} ---- #{::File.basename __FILE__}:#{__LINE__}"

```

following is my stdout:

```
r.inspect:nil ---- ex2.rb:10
```

this is my gem version:

```
roroco@roroco ~/Dropbox/rbs/ro_crawler $ bundle show|gr httpclient
  * httpclient (2.6.0.1)
roroco@roroco ~/Dropbox/rbs/ro_crawler $ bundle show|gr faraday
  * faraday (0.9.1)
  * faraday_middleware (0.9.1)
```

**Comment by roroco** [comment]
I fix it with reverse `use` and `adapter`

```
require 'faraday'
require 'faraday_middleware'

h = Faraday.new do |c|
  c.use FaradayMiddleware::FollowRedirects
  c.adapter :httpclient
end

r = h.get("https://www.google.com").body
puts "r.inspect:#{r.inspect} ---- #{::File.basename __FILE__}:#{__LINE__}"

```

**Comment by mislav** [comment]
Thanks for the update! Yes, the [order of middleware matters](https://github.com/lostisland/faraday/blob/f97f1874e4cd976f564870bb6151fb05e5f4c8b7/README.md#advanced-middleware-usage).

**Comment by collimarco** [comment]
Is there any way to follow redirects nowadays? 

That middleware is deprecated and I can't find any solution to follow the redirects

**Comment by iMacTia** [comment]
@collimarco you can use the new "gemified" middleware: https://github.com/tisba/faraday-follow-redirects
