### ISSUE TITLE
Cannot load such file -- net/http/persistent

### ISSUE THREAD

**Issue by araslanov-e** [lostisland/faraday#463]
```missing dependency for Faraday::Adapter::NetHttpPersistent: cannot load such file -- net/http/persistent```
Need install gem 'net-http-persistent' ?

**Comment by mislav** [comment]
Yeah. It's a separate library that builds on Ruby's net/http.

Let us know if installing the gem helps.

**Comment by araslanov-e** [comment]
installing the gem helps B)

**Comment by mislav** [comment]
You should close the issue then! ;)

**Comment by araslanov-e** [comment]
В)
