### ISSUE TITLE
Question about routes in Faraday.new constructor

### ISSUE THREAD

**Issue by zph** [lostisland/faraday#466]
[Platforms/Versions: Ruby 2.1.5, OSX 10.10, Chruby]

I have a question about faraday's expected behavior.

I expected to be able to define a base route like so:

`conn = Faraday.new(url: "https://restapi.surveygizmo.com/v3") do ... end`
and then have `conn.get('/survey')` result in a GET call to `https://restapi.surveygizmo.com/v3/survey`.

When I do that series of actions, the call that's executed is to `https://restapi.surveygizmo.com/survey`.

So the '/v3' is being swallowed in `faraday-0.9.1/lib/faraday/connection.rb @ line 406 Faraday::Connection#build_exclusive_url`

In the following pry session, the potential problem is just below the inserted `binding.pry`.

```
         399: def build_exclusive_url(url = nil, params = nil)
         400:   url = nil if url.respond_to?(:empty?) and url.empty?
         401:   base = url_prefix
         402:   if url and base.path and base.path !~ /\/$/
         403:     base = base.dup
         404:     base.path = base.path + '/'  # ensure trailing slash
         405:   end
         406:   require'pry';binding.pry
issue => 407:   uri = url ? base + url : base
         408:   uri.query = params.to_query(options.params_encoder) if params
         409:   uri.query = nil if uri.query and uri.query.empty?
         410:
         411:   uri
         412: end
```

When using `:+` to join a URI object and string, in the `base + url` branch of ternary, URI throws away the '/v3' part of url.

I found that both `File.join(base.to_s, url)` or raw `[].join('/')` preserve '/v3' in the route. Unfortunately,
the tailormade `URI.join(base.to_s, url)` swallows "/v3" also.

So I'm wondering if faraday isn't meant to be used this way, or if this is a bug?

If it's a bug, I have a preliminary PR that I can submit :).

Thanks for making the my favorite ruby http client. It's really a pleasure to work with the middlewares and good architecture :heart:.

**Comment by ldonnet** [comment]
+1 same question as @zph what is the way to include a path_prefix in Connection.new?

**Comment by technoweenie** [comment]
> I expected to be able to define a base route like so:

`conn = Faraday.new(url: "https://restapi.surveygizmo.com/v3") do ... end`
and then have `conn.get('/survey')` result in a GET call to `https://restapi.surveygizmo.com/v3/survey`.

Pass "survey" instead and it'll work as expected.  If you pass an absolute path, Faraday will use that absolute path.

> Thanks for making the my favorite ruby http client. It's really a pleasure to work with the middlewares and good architecture

Thanks :)  I've actually been hacking on [Hurley](https://github.com/lostisland/hurley), what Faraday v1.0 should have been.  It fixes my issues in Faraday's arch, but still feels very familiar.

**Comment by mislav** [comment]
Yes, `/survey` and `survey` are different routes to Faraday. It's like hyperlinks on web pages:

1. When you're on `/site/about` page, having a hyperlink with `href="survey"` will take you to `/site/survey`
2. When you're on `/site/about` page, having a hyperlink with `href="/survey"` will take you to `/survey`

We make a distinction between "relative" and "absolute" paths. This is so that you can break out of a path prefix you configured Faraday::Connection with if you need.

**Comment by zph** [comment]
@technoweenie @mislav Thank you both. I assumed the leading slash was necessary for path building, rather than faraday differentiating between relative and absolute.

Thanks for taking the time to point out how it works :smile: .

**Comment by ldonnet** [comment]
@technoweenie @mislav Thanks for taking time to explain us the way it works. 
If i understand the next upgrade of faraday will be to move on hurley?

**Comment by zph** [comment]
@technoweenie I'll keep an eye out for Hurley :heart_eyes_cat:.
