### ISSUE TITLE
Unexpected "Name or service not known" exceptions

### ISSUE THREAD

**Issue by duncan-bayne** [lostisland/faraday#475]
I am using Faraday to post to the Grove API:

```
url = 'https://grove.io/api/notice/MY_KEY_HERE'
client = Faraday.new(:url => url, ssl: { verify: false }).post do |req|
  req.body = {
    service: 'ServiceName',
    message: 'A message for IRC',
    url: 'https://grove.io/app',
    icon_url: 'https://grove.io/static/img/avatar.png'
  }
end
```

This fails with the following exception:

```
getaddrinfo: Name or service not known:
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'",
 "/home/duncan/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'"
```

This is very strange, because the hostname is definitely known:

```
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	grove.io
Address: 184.106.119.197
```

Some possibly relevant versions:

* Linux Mint 17.1 Rebecca, 64-bit Cinnamon
* ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
* faraday 0.9.1
* Linux my-hostname 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

The peculiar thing is that this code works fine on a very similar system:

* Linux Mint 17.1 Rebecca, 64-bit Cinnamon
* ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
* faraday 0.9.1
* Linux duncan-thinkpad-edge 3.19.4-031904-generic #201504131440 SMP Mon Apr 13 14:41:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

-----

![not sure if PEBKAC or subtle Faraday or Net/HTTP bug](http://cdn.meme.am/instances/500x/61691260.jpg)

**Comment by mislav** [comment]
The `getaddrinfo` in the exception definitely indicates a network or DNS resolution error. Sorry, but the error is likely not in Faraday. I am able to make HTTP requests to `grove.io`

**Comment by duncan-bayne** [comment]
I get that the exception indicated a DNS error, but the weird thing is that I could resolve the hostname normally on the same system.

**Comment by Jwan622** [comment]
Any other suggestions here?

**Comment by iMacTia** [comment]
Hi @Jwan622, as stated above this is usually not a Faraday issue but a DNS issue.
If you still think this is related to Faraday then please open your new issue and provide some code to reproduce
