### ISSUE TITLE
Is a retry expected automatically when request times out?

### ISSUE THREAD

**Issue by SavithaK** [lostisland/faraday#479]
We were looking into adding retries and it appears that our request is being retried once, even without explicitly specifying it. Am I missing something? 

In our rails app, the "test" endpoint just sleeps 10 seconds. When we run the following once, we receive 2 requests for the test endpoint in the app. This is run locally and no one else is calling the endpoint.

http_client =
  Faraday.new('http://localhost:3000/test') do |faraday|
    faraday.adapter  Faraday.default_adapter
    faraday.response :logger
  end

http_client.get do |req|
  req.options[:timeout] = 5
end

**Comment by technoweenie** [comment]
Not from Faraday AFAIK.  It could be something built into your adapter.

**Comment by SavithaK** [comment]
Our test doesn't use any custom adapters or middleware. The code I pasted in the issue is exactly what we ran.

**Comment by qinweiz** [comment]
It looks like net_http retries, which is the default_adapter. https://bugs.ruby-lang.org/issues/10674

**Comment by SavithaK** [comment]
That helps!
