### ISSUE TITLE
How to tell Faraday to preserve hashbang in site URL?

### ISSUE THREAD

**Issue by nickckaye** [lostisland/faraday#482]
I'm working on a fork of a library that implements Faraday to build URLs.

    site = "https://example.io/#/"
    path = "oauth/authorize"
    connection = Faraday.new(site)
    resource = Faraday::Utils.URI(path)
    URL = connection.build_url(resource)

Notice that my site URL ends with a hashbang. But when the above code is executed, Faraday strips out the hashbang entirely:

> **https://example.io/oauth/authorize**

But my application requires it to build this URL (with the hashbang):

> **https://example.io/#/oauth/authorize**

Now before I go ripping out Faraday and monkey-patching something terrible.. can I do this by setting an option on Faraday?

**Comment by nickckaye** [comment]
Posted http://stackoverflow.com/questions/30421058/how-to-tell-faraday-to-preserve-hashbang-in-site-url

**Comment by mislav** [comment]
Answered on SO: there are ways you could preserve the hashbang in URLs, but it's a moot point since hash portion of the URL is never sent to the server anyway. So you're trying to preserve a portion of URL that's ignored for HTTP requests.

**Comment by nickckaye** [comment]
Thanks @mislav for a solid pointer on using the right tool for the job.
