### ISSUE TITLE
Ssl options type mismatch between net/http adapter and excon adapter

### ISSUE THREAD

**Issue by aselder** [lostisland/faraday#486]
When using client_certs and client_keys, there is a difference in behavior between excon and net/http

Excon expects the file paths to the cert and key, while net/http expects actual Certificate and PSA objects

So if you change the adapter, you need to find every place you're using these options and change them. 

I'd expect Faraday to just work when swapping out adapters.

In this case, it probably makes sense to have faraday take the file paths, and then instantiate the objects in the adapters that need them. For backwards compatibility, the net/http adapter could check to see if it gets a Certificate object and just uses that, or loads the data from a file path if given a string.

This way we move to a single unified interface when usage of Faraday does not depend on the adapter in use. 

I'm happy to make the changes if people find this valuable. Let me know.

**Comment by mislav** [comment]
Hi, these are all good ideas. I'd welcome a pull request from you!

**Comment by iMacTia** [comment]
Closing as stale and because adapters have now moved, so if this is still an issue it should be opened against https://github.com/excon/faraday-excon
