### ISSUE TITLE
Faraday::SSLError on Yosemite

### ISSUE THREAD

**Issue by jasonm23** [lostisland/faraday#490]
Faraday will return an error on a vanilla Yosemite install, e.g.

```
Faraday::SSLError
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

This is due to the lack of SSL certificates for OpenSSL on Yosemite, due to Apple switching to a new SSL/TLS library.

OpenSSL is still installed, and so Ruby will be attempting to use it for SSL/TLS connections, but without certificates in it's path it will fail.

I wanted to make sure there was an issue and solution listed in the Faraday issues which could be considered definitive, and specific to Yosemite's unique SSL/TLS situation among other OSX versions and other OSes.

**Comment by jasonm23** [comment]
This seems like the best write up I can find

http://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html

**Comment by jasonm23** [comment]
Note, not all oauth targets will currently throw an error, as far as I know, only google's servers will reject the default certs.

**Comment by mislav** [comment]
These resources might help you:

* https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates
* http://mislav.uniqpath.com/2013/07/ruby-openssl/
* https://gist3.github.com/mislav/5026283

**Comment by jasonm23** [comment]
Thanks @mislav your ssl tools / doctor.rb is also very useful 

The article I linked above solved it for me.

I had to rebuild Ruby 2.2.1 from source

**Comment by Vanuan** [comment]
Worth linking: https://github.com/rvm/rvm/issues/3330
