### ISSUE TITLE
EventMachine adapters SSL server certificate verification error.

### ISSUE THREAD

**Issue by calonso** [lostisland/faraday#492]
Using other adapters the certificate is properly verified, but using any of the event machine based `em_synchrony` or `em_http` I always get this error: 
```
em_http_ssl_patch.rb:23:in `ssl_verify_peer': unable to verify the server certificate for "devapi.mydrivesolutions.net" (Faraday::SSLError)
```

I'm using rbenv's ruby 2.1.2 on a Mac OS X 10.10.3 and brew managed openssl 1.0.2.

I've tried uninstalling and reinstalling ruby several times with the same error. Any help please?

**Comment by calonso** [comment]
@mislav Any thought about this?

**Comment by mislav** [comment]
Sorry for the late reply. This might be a bug in the experimental feature I added in 63cf47c95b573539f047c729bd9ad67560bc83ff. Can you tell us which exact host is this failing for so that I can try as well? Does it happen to any host, like `google.com` and `github.com`? Thanks

**Comment by mislav** [comment]
Oh, I see now that the hostname is `devapi.mydrivesolutions.net`. Ignore my above request.

**Comment by mislav** [comment]
This works for me locally:

```
require 'faraday'

conn = Faraday.new "https://devapi.mydrivesolutions.net" do |f|
  f.adapter :em_http
end

conn.get '/'
```

I would then assume that your CA bundle isn't set up properly on your system. See http://mislav.uniqpath.com/2013/07/ruby-openssl/

**Comment by calonso** [comment]
Thanks @mislav. 

I'm still struggling with this, even after reading through your post. And I have a weird situation where:

```
require 'faraday'

conn = Faraday.new "https://devapi.mydrivesolutions.net" do |f|
  f.adapter :em_http
end

conn.get '/'
```
Crashes with the `unable to verify the server certificate` error, but this same code opening `https://github.com` works!!

Also, using your doctor.rb to devapi.mydrivesolutions.net works properly!! So it looks like something wrong with faraday?

Sorry, I'm a bit lost here.

Regards
