### ISSUE TITLE
JRuby 9000 SSL error

### ISSUE THREAD

**Issue by rezaf** [lostisland/faraday#503]
Certificate verify fail error with Faraday 0.9.1 and JRuby 9000:

```
Faraday::SSLError: certificate verify failed
block in call at .../jruby-9.0.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:43
with_net_http_connection at .../jruby-9.0.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87
call at .../jruby-9.0.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32
call at .../jruby-9.0.0.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15
```

The error is only present using JRuby 9k. No issues with MRI 2.2.2.
It appears that there is that some Travis tests are failing for Faraday in the JRuby-head + SSL=YES environment.
https://travis-ci.org/lostisland/faraday/jobs/73048424

**Comment by iMacTia** [comment]
Hi @rezaf,
unfortunately I know nearly nothing about JRuby. Can I suggest you try to execute the exact same call with Net::HTTP (without using Faraday) and see if that works as expected?

**Comment by rezaf** [comment]
Hi @iMacTia, I'm going to close this issue, since it was nearly a couple of years ago, and I haven't been working on this in a while. Thank you so much for looking into it!
