### ISSUE TITLE
APIAuth support

### ISSUE THREAD

**Issue by santiagodoldan** [lostisland/faraday#523]
Is it possible to use api-auth?

I'm not able to sign the request object, I already created a middleware but I don't have access to the request object which api-auth receives to create the hmac message.

Thanks

**Comment by santiagodoldan** [comment]
I created a pull request #524

**Comment by technoweenie** [comment]
Sorry, we're not accepting new adapters at this time. This [typhoeus adapter for Faraday](https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb) is a great model of how a another gem can add a Faraday adapter.

Some more info on Faraday, and its Hurley rewrite: https://github.com/lostisland/faraday/issues/454

**Comment by santiagodoldan** [comment]
cool, thanks for letting me know about that, will move that adapter to another gem

**Comment by technoweenie** [comment]
Sounds good :+1: I'll close the issues, then.
