### ISSUE TITLE
Does Faraday support --max-time flag?

### ISSUE THREAD

**Issue by dcarneiro** [lostisland/faraday#526]
I'm writing a function that is getting an .mp3 body, but I want it to fail after x seconds for very large mp3.

From what I understand the timeout option only works until the connection is established. As soon as I start receiving the response body, timeout don't work anymore.

Curl does have a **--max-time** flag for cases like these: http://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout

p.e. : This command will fail after 2 seconds 
`curl -o garbage.mp3 http://ia801509.us.archive.org/20/items/batida/batida.mp3 --max-time 2`

Does Faraday support anything like this?

**Comment by technoweenie** [comment]
Pretty sure the `read_timeout` is for the whole response. The `open_timeout` is for the connection only. This is for net/http though. Other adapters may handle this differently. All faraday does is passes the options through from the `Faraday::Connection` to the adapter itself.

**Comment by dcarneiro** [comment]
`Faraday::RequestOptions` don't seem to have a `read_timeout` method:

```
NoMethodError: undefined method `read_timeout=' for #<Faraday::RequestOptions (empty)>
```

but the `net_http` adapter is using the timeout to set the `read_timeout`: https://github.com/lostisland/faraday/blob/cc9772bfdf3e6b83b58706fd50cad5ea31a09c98/lib/faraday/adapter/net_http.rb#L36

Either way, this code should fail after one second, but it doesn't:

```ruby
  conn = Faraday.new(url: 'http://ia801509.us.archive.org/20/items/batida/batida.mp3') do |faraday|
    faraday.adapter :net_http
  end

  response = conn.get do |req|
    req.options.timeout = 1
  end
```

**Comment by technoweenie** [comment]
Maybe we both were misunderstanding how `read_timeout` works: 

> Number of seconds to wait for **one** block to be read

Faraday just passes options to the adapter. So no, it doesn't support what you're looking for. You may have to just use the stdlib timeout library. However, it's much better when this is built into the http adapter, so it can clean up any internal connections and objects it was using to make the request.

**Comment by dcarneiro** [comment]
In fact it appears to be a problem with ruby net/http. The following code also hangs:

```ruby
require 'net/http'
uri = URI('http://ia801509.us.archive.org/20/items/batida/batida.mp3')
http = Net::HTTP.new(uri.host, uri.port)
http.open_timeout = 5
http.read_timeout = 5
response = http.request(Net::HTTP::Get.new(uri.request_uri))
```

Since this is not a Faraday issue I'll close it. 
Thanks for the help :smiley:
