### ISSUE TITLE
Instead of request body, the response body is logged

### ISSUE THREAD

**Issue by texpert** [lostisland/faraday#537]
When bodies: true is set, I got no request bodies in the logs, but twice the response bodies.

**Comment by texpert** [comment]
Found a workaround here - https://github.com/intridea/oauth2/issues/214

**Comment by mislav** [comment]
Yes, the logger needs to be in the appropriate position in the middleware stack:

```rb
Faraday.new do |faraday|
  faraday.request :uri_encoded
  faraday.response :logger, nil, bodies: true
  faraday.adapter :net_http
end
```

Does using it like so solves the problem? If so, then please close the issue and sorry for the confusion.

**Comment by texpert** [comment]
Yes, the problem is solved, thank you!
