### ISSUE TITLE
why does Faraday change my header

### ISSUE THREAD

**Issue by bboylilshaw** [lostisland/faraday#548]
see below sample code:

```ruby
host = 'localhost'
options = { headers => {user_id: 000-000} }
@conn = Faraday.new(host, options) 
```

Faraday changed my header to "User-Id":"000-000", I want this header being included in every request and not changed, is there any way to do it?

**Comment by mislav** [comment]
This should do it:

```rb
Faraday.new(host, headers: { "user_id" => "000-000" })
```

**Comment by bboylilshaw** [comment]
@mislav thanks, it's working
