### ISSUE TITLE
POST with headers

### ISSUE THREAD

**Issue by samimb** [lostisland/faraday#549]
This is more of a question than an issue.

Not sure how to else get in touch with anyone.

How do I post with headers? I'm posting a json to an application that requires a login by looking in the header.

In curl I do it like so:
curl -sk -H "SEC:hash" "https://localhost/"

**Comment by mislav** [comment]
From this project's [very own README](https://github.com/lostisland/faraday/blob/3579225fd18c770dd2dc5d020d74b72701e4e647/README.md#usage):

```rb
conn.post do |req|
  req.url '/nigiri'
  req.headers['Content-Type'] = 'application/json'
  req.body = '{ "name": "Unagi" }'
end
```

**Comment by Zorbash** [comment]
@samimb has the above response resolved your issue? Can we close this?
