### ISSUE TITLE
First Time contributing

### ISSUE THREAD

**Issue by GustavoCaso** [lostisland/faraday#550]
@mislav Hi I really love Farady I use everyday. I would really like to contribute, are there any first issues to get use to the code ?

**Comment by mislav** [comment]
Hi @GustavoCaso, thanks for your interest. Some GitHub projects have helpful labels like "Help Wanted" or "beginner-friendly" on issues and pull requests to help identify work that new contributors could tackle. We don't have such labels, unfortunately, but the best way to start contributing to any project in general would still be to review its open issues and pull requests.

Most open source maintainers need help with triaging issues and pull requests. That involves looking at the recently opened ones, especially ones that still haven't been commented on or labeled by a maintainer such as @technoweenie or me, and adding your comments if you have any. For instance, you could look at a pull requests that is supposed to solve a bug, potentially try out the code, and say "this fixes the issue for me" or "the code for this doesn't look good/doesn't work in all cases".

There are many open issues that report a bug, but we haven't had time to look at those reports and decide how to solve an issue. If some of those bug reports are affecting features that you use, it could be a good starting point to contribute to Faraday by trying to fix them. Remember that most fixes should add or edit automated tests, which are run by Travis CI for every pull requests submitted.

Most projects, Faraday included, also need help with documentation. Faraday has usage documentation in its README, but not much more than that. A good contribution would be identifying weak points in the documentation and submitting new documentation, either in README, in code, or on the project wiki.

Finally, you may have a feature idea for Faraday. A good way to start with this is propose the idea as a new issue, to gather opinions on its viability. If you get a :+1: from maintainers (e.g. me), you can proceed by coding the idea up and submitting a pull request. Final version of the pull requests for a new feature should always have new tests and new documentation, at least in the code. You always need to keep in mind that a feature change should generally be backwards-compatible with current and, hopefully, previous version of Faraday (v0.8.x).

Sorry that I don't have concrete suggestions about what you could work on at the moment. I have some ideas of what I personally want changed in Faraday, but they are very tricky problems that I don't suggest you should be tackling as a newcomer to the project.

Let me know if you have any further questions.

**Comment by GustavoCaso** [comment]
Thanks @mislav for the words, really wise ones. I will start with your recommendations,and if I get stuck I will write either you or @technoweenie.

Again Thanks.
