### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by YayConnolly** [lostisland/faraday#551]
Suggest improving the documentation to clarify the connection options and middleware API. For example, it seems like there are at least 3 ways to change default parameter encoding: `conn.request :url_encoded`, `conn.options.params_encoder = CustomeEncoder` and inline `Faraday.new params_encoder: CustomEncoder`. As a new user I found this difficult to piece together.

**Comment by YayConnolly** [comment]
@GustavoCaso maybe you would be interested in helping on this one :)

**Comment by GustavoCaso** [comment]
Of course @YayConnolly I'll have a look

**Comment by mislav** [comment]
Thanks for the suggestion! It's important to distinguish that `conn.request :url_encoded` does not in fact change default parameter encoding, but mounts the UrlEncoded middleware that serializes raw hash POST data into `x-www-form-urlencoded`. The parameter encoder does affect the encoding that happens within, but primarily affects the handling of GET parameters throughout the request cycle.

**Comment by GustavoCaso** [comment]
Thanks @mislav I was looking around the code to understand it better, before writing any documentation, so I don't mess up the `README`

**Comment by iMacTia** [comment]
This should have been addressed in #659
