### ISSUE TITLE
Custom headers bug inside Part::FilePart

### ISSUE THREAD

**Issue by alexgarbarev** [lostisland/faraday#554]
Here is pieces of original code:

``` ruby
    def initialize(boundary, name, io, headers = {})
       # ....
      @head = build_head(boundary, name, io.original_filename, io.content_type, file_length,
                         io.respond_to?(:opts) ? io.opts.merge(headers) : headers)
       # ....
    end

    def build_head(boundary, name, filename, type, content_len, opts = {}, headers = {})
      # ....
    end
  end
```

I've noticed problem that `headers` are always empty inside `build_head`. The reason is that 7th argument is never passed from `initialize`.

**Comment by mislav** [comment]
There is no method `build_head` inside Faraday code. Did you want to report a bug with another project?

**Comment by iMacTia** [comment]
Closing this issue as it's not in Faraday but somewhere else (`multipart-post` gem if I'm not wrong).
