### ISSUE TITLE
net_http adapter doesn't retry on connection timeout

### ISSUE THREAD

**Issue by krallin** [lostisland/faraday#561]
As of https://github.com/lostisland/faraday/commit/9ad0fcd38a27e51fdbaaa034d00a54cb26d59a9c, it looks like `net_http` raises `Error::ConnectionFailed` instead of `Error::TimeoutError` when a connection times out.

However, [the retry middleware in its default configuration only retries for timeouts](https://github.com/lostisland/faraday/blob/80c0e66102168939df04682573bc267e089a43ae/lib/faraday/request/retry.rb#L57-L60), which means that connection timeouts won't be retried for `net_http` (unless you happen to run on a platform where `Net::OpenTimeout` isn't defined).

Is this intentional? It looks like other adapters don't behave that way.

**Comment by joevandyk** [comment]
https://github.com/lostisland/faraday/issues/582 might be related.

**Comment by dentarg** [comment]
> Is this intentional?

Seems so, from https://github.com/lostisland/faraday/pull/438

> This allows one to distinguish between `:open_timeout` connection timeouts and `:timeout` request timeouts.

but don't think the correct way to distinguish between is that one (`Net::ReadTimeout`) raises `Faraday::TimeoutError` and another (`Net::OpenTimeout`) raises `Faraday::ConnectionFailed`). `Faraday::ConnectionFailed` [covers a lot more cases](https://github.com/lostisland/faraday/blob/v0.10.1/lib/faraday/adapter/net_http.rb#L13-L25) than timeout.

**Comment by iMacTia** [comment]
Thanks for your input @dentarg.
I can confirm the behaviour is intentional as of #438. This is because it was decided that it's not worth to retry a connection that couldn't be opened at all (usually related to networking issues).
If the default behaviour is not what you want, then easiest thing to do in this case is to customise the retry middleware as shown in #582
