### ISSUE TITLE
CHANGELOG entry missing for 0.9.2

### ISSUE THREAD

**Issue by betelgeuse** [lostisland/faraday#562]
https://github.com/lostisland/faraday/blob/v0.9.2/CHANGELOG.md

There's a tag but no entry in the CHANGELOG file.

**Comment by mislav** [comment]
Changelog is unmaintained. I'm sorry for the confusion; I should delete the file. Instead, [see Releases](https://github.com/lostisland/faraday/releases/tag/v0.9.2)
