### ISSUE TITLE
Serialing Faraday::Response cause information missing of Faraday::Env.

### ISSUE THREAD

**Issue by okitan** [lostisland/faraday#569]
Because `@on_complete_callbacks` contains proc, marshalling `Faraday::Response` have its own way, but it does not copy other than status, body, and response_headers.
Request things are missing.

I think we can copy full `Faraday::Env` like this:

``` ruby
    def marshal_dump
      !finished? ? nil : @env.to_h
    end
```

What do you think about this change?
(Or do I also take care of `custom_members`?)

---

If it is admissible, I will send PR.
Thanks.

**Comment by iMacTia** [comment]
Unfortunately not all the request info are available after the request has been executed (e.g. request body is lost). If you want request info you need to serialise the request before that reaches the adapter (maybe a middleware can help in this case).
I don't really feel comfortable with this change as hashing and dumping a whole object might be insecure. I prefer the "whitelisting" approach we have currently in place. Which can always be extended to include more stuff, but not request-related, as the object represents a response
