### ISSUE TITLE
Response empty when using proxy

### ISSUE THREAD

**Issue by somya12** [lostisland/faraday#574]
I am making a faraday call like - 
`con = Faraday.new(url, ssl:{verify:false}) do |p|
   p.proxy "#{proxy}"
 end`

The call returns a response object with success = false and an empty body and response headers. Following is the response -

``#<Faraday::Connection:0x0056075dce7768 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x0056075dce7308 @handlers=[]>, @url_prefix=#<URI::HTTP:0x0056075dce7060 URL:url>, @proxy=#<Faraday::ProxyOptions uri=#<URI::HTTP:0x0056075dce69d0 URL:proxy>>>`

response -
`#<Faraday::Response:0x0056075db18b30 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @url=#<URI::HTTP:0x0056075dce7060 URL:url> @request=#<Faraday::RequestOptions proxy=#<Faraday::ProxyOptions uri=#<URI::HTTP:0x0056075dce69d0 URL:proxy>>> @request_headers={"User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x0056075db18b30 ...>>>``
How do I go about this problem?

**Comment by iMacTia** [comment]
Hi @somya12,

When you initialise a `Faraday::Connection` with the block syntax like you did in your example, you loose the default Adapter and you have to manually set it back.

Your code should work if you change it into:

```ruby
con = Faraday.new(url, ssl:{verify:false}) do |p|
  p.proxy "#{proxy}"
  p.adapter  Faraday.default_adapter
end
```

I'm sorry for the confusion, we're aware this is a common issue and we're trying to address it in the next releases.

Closing for the time being, but feel free to reopen if you need more help!
