### ISSUE TITLE
Serializing with YAML

### ISSUE THREAD

**Issue by AvaelKross** [lostisland/faraday#578]
I'm trying to serialize Faraday::Response object and then do YAML.load(serialized_response), but getting this error while loading from yaml:

```
NoMethodError: undefined method `[]' for nil:NilClass
from ..path_here/gems/faraday-0.9.2/lib/faraday/utils.rb:48:in `[]='
```

Everything is being serialized without any issues excepting Faraday::Utils::Headers objects inside Faraday::Response.

Easiest way to reproduce:
`YAML.load(Faraday::Utils::Headers.new("User-Agent" => "safari").to_yaml)`

**Comment by AvaelKross** [comment]
#579

**Comment by iMacTia** [comment]
PR merged, closing
