### ISSUE TITLE
Faraday's certificates hell!

### ISSUE THREAD

**Issue by jjgh** [lostisland/faraday#581]
```
[1] pry(main)> require 'reality' # https://github.com/molybdenum-99/reality
=> true

[2] pry(main)> Reality::Entity('U.S.A.').population
Faraday::ConnectionFailed: An existing connection was forcibly closed by the remote host. - SSL_connect from C:/Dev/ruby/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'

[3] pry(main)> Reality::Entity('U.S.A.').population # try once more
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by mislav** [comment]
Hello, sorry that you've having trouble. Faraday doesn't actually deal much with certificates itself. Instead, it uses OpenSSL mostly how it's already set up on the system and in this Ruby version, usually through Ruby's `net/http`. For more information about this problem in general, please read http://mislav.net/2013/07/ruby-openssl/, and let me know if anything became clearer and you were able to solve the issue.
