### ISSUE TITLE
Net::ReadTimeout is not rescued in retry block

### ISSUE THREAD

**Issue by why-el** [lostisland/faraday#582]
Hey, 

Perhaps I am misunderstanding the retry logic, but during a simulation of slow clients Faraday does not retry the request.

```
      conn = Faraday.new(url: Rails.application.secret.my_host) do |builder|
        builder.options.timeout           =  1
        builder.options.open_timeout  =  1

        builder.request :retry, max: 3, exceptions: [::Net::ReadTimeout, Timeout::Error]

        builder.adapter Faraday.default_adapter
      end
```

This is code from Service A, which makes a request to Service B. In Service B, I have a simple ruby `sleep 3`, which will force `net_http` (our current adapter) to raise `Net::ReadTimeout`. Shouldn't Faraday retry this? I have also tried a string version of the exception and a scoped one (without the leading double colon), and I still see the exception raised with no retries.

**Comment by krakatoa** [comment]
Which HTTP method are you using? Maybe you are using a non-idempotent POST, which by default is not covered by the retry middleware. If that's your case, add the `method` argument on the retry options like:

<code>builder.request :retry, max: 3, method: [:post], exceptions: [::Net::ReadTimeout, Timeout::Error]</code>

**Comment by joevandyk** [comment]
the retry functionality doesn't retry Faraday::ConnectionFailed I noticed... seems like it should?

**Comment by joevandyk** [comment]
I would think that it should retry all of these exceptions as well. 

https://github.com/lostisland/faraday/blob/f73d13ee09814fa68b37efa7bddafa47331948c2/lib/faraday/adapter/net_http.rb#L12-L28

**Comment by why-el** [comment]
@krakatoa thanks. I think your option should be`methods` not `method`?

**Comment by krakatoa** [comment]
Oh sorry, yes @why-el ! it's `methods`

**Comment by why-el** [comment]
Ok, great. I think that solves my issue.
