### ISSUE TITLE
Transforming UploadIO object into string while sending request.

### ISSUE THREAD

**Issue by Extazystas** [lostisland/faraday#593]
Hello. I'm sending file to Grape API with this code:

```
Faraday.new(endpoint) do |conn|
        conn.response :logger unless Rails.env.test?
        conn.response :json, content_type: /\bjson$/ unless response_type != :json
        conn.request :multipart
        conn.request :url_encoded
        conn.adapter :net_http
end
```

I'm setting file for connection this way:

```
...
Faraday::UploadIO.new(
          file.tempfile.path,
          file.content_type,
          file.original_filename
        )
...
```

And it works because I can see this object in params before sending a request:

```
#<UploadIO:0x007f87ac578d58 @content_type="image/jpeg", @original_filename="sQF5wS0qaV8.jpg", @local_path="/tmp/RackMultipart20160705-8019-18ryl1x.jpg", @io=#<File:/tmp/RackMultipart20160705-8019-18ryl1x.jpg>, @opts={}>
```

But on a client incoming params does not contain a File, its a plain string like that:
`"#<UploadIO:0x007f87ac578d58>"`

I tried to debug Grape from `Endpoint#run` method but `@params` already has a String instead of File here. I can successfully upload file with Swagger, but not with Faraday. 

Any ideas why its happening?

**Comment by syuanivy** [comment]
I have the same issue....

**Comment by iMacTia** [comment]
@Extazystas apologies if this went unnoticed till now. Did you ever fix this issue?
If not, then a full code snippet would help in this case (creating the connection and performing the request).
The code I see from you seems fine so it must be something else...

**Comment by iMacTia** [comment]
Closing as stale, will reopen if provided the code to reproduce
