### ISSUE TITLE
Send file through url instead of upload

### ISSUE THREAD

**Issue by JorgeDDW** [lostisland/faraday#595]
Hi there,

In my part of learn Ruby, JSON, and Telegram Bots I want to make a Pokedext, and here is what i need to send file through the url i get from the API instead of upload from the server:

`    bot.api.send_photo(chat_id: message.chat.id, photo: Faraday::UploadIO.new('~/Desktop/jennifer.jpg', 'image/jpeg'))
`

What do I need to change in order to use a url ?

**Comment by iMacTia** [comment]
Hi @JorgeDDW, can you please show us an example of URL you would like to use? Do you need to use it in place of the local file `'~/Desktop/jennifer.jpg'`?

**Comment by JorgeDDW** [comment]
Pokemon API: http://pokeapi.co
I noticed today that the url were removed.

**Comment by iMacTia** [comment]
Wow, this is a very specific use-case, so not sure I can help a lot, but here is a possibly useful link:
http://stackoverflow.com/a/264239/4194669

You should be able to "open" the url using the `open-uri` gem to get a `File` object.
You should then be able to pass it to `Faraday::UploadIO#new` as first parameter. Attention that in this case you'll need also a third param (I would suggest to try with a fantasy name and see what happens).

Here is the Doc for UploadIO:

```ruby
  # Create an upload IO suitable for including in the params hash of a
  # Net::HTTP::Post::Multipart.
  #
  # Can take two forms. The first accepts a filename and content type, and
  # opens the file for reading (to be closed by finalizer).
  #
  # The second accepts an already-open IO, but also requires a third argument,
  # the filename from which it was opened (particularly useful/recommended if
  # uploading directly from a form in a framework, which often save the file to
  # an arbitrarily named RackMultipart file in /tmp).
  #
  # Usage:
  #
  #     UploadIO.new("file.txt", "text/plain")
  #     UploadIO.new(file_io, "text/plain", "file.txt")
```

Apologies if this doesn't help, I hope at least it will put you on the correct tracks 😄 
`Faraday::UploadIO` simply extends this class, so it's the type of issue that falls in the "middle earth".

**Comment by sbleon** [comment]
Since this is more of a support request than a suggestion of a change to faraday, I'm going to close it.

Jorge, if you need more help with this issue I recommend posting on StackOverflow. That will probably get a lot more eyeballs on it!
