### ISSUE TITLE
Custom Params Encoder does not work as documented on per-connection basis

### ISSUE THREAD

**Issue by 7sun** [lostisland/faraday#598]
Per the docs, you should be able to pass a hash with `:params_encoder` when initializing a new Faraday connection:
```
# per-connection setting
conn = Faraday.new :params_encoder => Faraday::FlatParamsEncoder
```

However, this does not work and will throw a NoMethodError:
```
NoMethodError: undefined method `params_encoder='
```

I've traced the problem to when ConnectionOptions.from is called, inside of the Connection initialization. When passed an argument, ConnectionOptions.from creates a new instance and then calls update on it. Since params_encoder isn't an attribute of ConnectionOptions, it fails.

To correctly set a params_encoder, it must be sent inside of a request hash, like so:
```
Faraday.new :request => {:params_encoder => TwitterAds::CustomParamsEncoder}
```

If this is the intended functionality, the docs should be updated. If not ConnectionOptions would need to be changed. I can send up a pull request for either.

**Comment by iMacTia** [comment]
Hi @7sun, thanks for highlighting this.
I've reviewed the code and you're definitely right.
My assumption is that this is a simple error in writing the documentation (or a missing update after some code changes).
`:params_encoder` is definitely something related to the request, thus it should be related to it.
I would suggest you send a PR to fix the documentation :)

Thanks!

**Comment by 7sun** [comment]
@iMacTia Added a pull request for the docs here: https://github.com/lostisland/faraday/pull/607

**Comment by iMacTia** [comment]
Closing as #607 has just been merged :)!
Thanks @7sun !
