### ISSUE TITLE
Inconsistent documentation for `run_request`

### ISSUE THREAD

**Issue by djds23** [lostisland/faraday#599]
[The rubydoc for `Connection#run_request` say the signature is:](http://www.rubydoc.info/gems/faraday/0.9.0/Faraday/Connection#run_request-instance_method)

* method => Symbol 
* url => String|URI
* **body => String**
* headers => Hash

```ruby
    # Builds and runs the Faraday::Request.
    #
    # method  - The Symbol HTTP method.
    # url     - The String or URI to access.
    # body    - The String body
    # headers - Hash of unencoded HTTP header key/value pairs.
    #
    # Returns a Faraday::Response.
```

However, the README examples demonstrate should be a hash:
https://github.com/lostisland/faraday#usage

I am using strings like the docs demonstrate, but it would be helpful to know which the correct/supported way.

Thanks for your time & your work on Faraday!

**Comment by iMacTia** [comment]
Hi @djds23, you raised a good point.
Looking in details to it, I found the following in `Faraday::RackBuilder#build_env`:

```ruby
    # ENV Keys
    # :method - a symbolized request method (:get, :post)
    # :body   - the request body that will eventually be converted to a string.
    # :url    - URI instance for the current request.
    # :status           - HTTP response status code
    # :request_headers  - hash of HTTP Headers to be sent to the server
    # :response_headers - Hash of HTTP headers from the server
    # :parallel_manager - sent if the connection is in parallel mode
    # :request - Hash of options for configuring the request.
    #   :timeout      - open/read timeout Integer in seconds
    #   :open_timeout - read timeout Integer in seconds
    #   :proxy        - Hash of proxy options
    #     :uri        - Proxy Server URI
    #     :user       - Proxy server username
    #     :password   - Proxy server password
    # :ssl - Hash of options for configuring SSL requests.
```

As you can see, at this point the body have not been touched yet, but in this case it's clearly stated that it will be converted to a string later (ideally based on the selected middleware).

I would suggest we update the rubydoc on top of `Connection#run_request` to reflect the one on `Faraday::RackBuilder#build_env`.
Would you be able to issue a PR?

Thanks for taking the time to highlight this!

**Comment by djds23** [comment]
Happy to help! Made the PR, feel free to let me know if there is anything else I can do.
