### ISSUE TITLE
Timeouts don't work on streaming

### ISSUE THREAD

**Issue by jaimeiniesta** [lostisland/faraday#602]
Hi, I know that streaming is not supported in Faraday yet, but I wonder if there is a way to make the connection and read timeouts work in the following scenario, where Faraday 0.9.2 gets stuck, in Ruby 2.0.0:

``` ruby
conn = Faraday.new(url: 'http://streaming.radionomy.com/ABC-Lounge?lang=es-ES%2ces%3bq%3d0.8%2cen%3bq%3d0.6%2cpt%3bq%3d0.4%2cgl%3bq%3d0.2')

conn.get
```

In this case, Faraday just sits there wating forever, no timeouts are raised.

**Comment by iMacTia** [comment]
Hi @jaimeiniesta and thanks for opening this Issue.

I think there's a little misunderstanding here.
The two timeouts you can set with Faraday are `open_timeout` and `read_timeout`.
The former is the max time you can wait before the connection is open (handshake, low level stuff)
The latter is the max time you can wait until the first data packet is received.

Given this is a streaming endpoint, there will just be an endless flow of packets coming down, but after the first packet is received, the timeout will not apply anymore.
As far as I know, the timeout is not counting the time "between" packets.

I hope this is clear.
I can see you did some work on your side to limit the timeout for the streaming request, and I think that's the only reasonable solution until Faraday will officially support Streaming.

I'm closing as it seems you solved the issue, but please feel free to reopen if you need any help.
