### ISSUE TITLE
timeout is always doubled

### ISSUE THREAD

**Issue by grosser** [lostisland/faraday#612]
I guess this happens because it sets open and read timeout to the same value ... but it's kind of irritating :(

```
Benchmark.realtime { begin; Faraday.new("https://fake-response.appspot.com", request: {timeout: 1}).get("/api/?sleep=5"); rescue;end }

-> 2.0
```

**Comment by iMacTia** [comment]
Hi @grosser, each adapter has is own implementation of the timeout, can I ask you which one are you using in this case?

**Comment by grosser** [comment]
Net::Http

**Comment by iMacTia** [comment]
Hi @grosser, sorry for the late reply but it was harder than expected to find the issue.
I spent some time investigating this in the past days and I think I found the issue inside the Net::HTTP library.
If the call is performed and a ReadTimeout exception occurs (together with many others), and the method used is idempotent (like GET), then the connection is retried once.
You can see this [here](https://github.com/ruby/ruby/blob/ruby_2_3/lib/net/http.rb#L1459).

So the only thing you can do at this point is to point this out on the ruby project.
I'm closing this for the time being but can reopen anytime in the future if needed.

**Comment by grosser** [comment]
Thanks for digging in ... was hoping it is some simple bug :(

**Comment by philsturgeon** [comment]
Here's an issue that highlights things a little more 

https://bugs.ruby-lang.org/issues/10674

I cannot believe this is default functionality. 

Could Faraday jump in there and override this anyhow? Is there any amount of hacking that could be added to the adapter to make it respect the rules?

**Comment by grosser** [comment]
thx for tracking that down!
fix is coming in ruby 2.5 or 2.6 ?
https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/60035
I'd say don't add any hacks if it's fixed in trunk ... but maybe set retry
to false if available or so ...

**Comment by iMacTia** [comment]
I agree with @grosser, we should definitely not add any patch if an official fix is coming from the Ruby team directly. I can see the work has already been done so it's just a matter of release.
I'm happy to review a PR as soon as this functionality is ready that sets the new flag to false (if available) when setting the timeout for `Net::HTTP` adapter

**Comment by grosser** [comment]
should be able to make a PR and test it agains ruby-head
