### ISSUE TITLE
Net::HTTP::Persistent SSL ConnectionFailed issue on second SSL connection request

### ISSUE THREAD

**Issue by mikefogg** [lostisland/faraday#614]
Hey guys,

I posted a similar issue over at https://github.com/drbrain/net-http-persistent/issues/77 because I'm not exactly sure where the issue lies.

I'm running into an issue where **when I fire off a request the first time to an SSL endpoint it works great.**

After pausing for a few seconds and firing a request again to the same url... I'm getting:

```
Faraday::Error::ConnectionFailed: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert internal error
    from /Users/me/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
    from /Users/me/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `block in connect'
```

@drbrain mentioned that I may want to try setting `http.reuse_ssl_sessions = false` but it doesn't seem like that's possible using Faraday?
---
- **Ruby 1.9.3** (I know, I can't upgrade to 2.x yet :) )
- **Faraday 0.8.9**
  - **adapter:** :net_http_persistence
---

**Comment by iMacTia** [comment]
Hi @mikefogg 
Unfortunately I'm not aware of a way to do this at the moment on Faraday.
If you end up needing this setting, you'll probably need to submit a PR to change how ssl is configured for that adapter.
Here is the method that manage ssl configuration:

https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http_persistent.rb#L38
