### ISSUE TITLE
Faraday 0.9.2 and net-http-persistent 3.0.0

### ISSUE THREAD

**Issue by ThomasBJones2** [lostisland/faraday#617]
Hi when trying to run faraday 0.9.2 with net-http-persistent 3.0.0 I found that rails would crash on start up. The error output is posted below. Rails was able to start up on http-persistent 2.9.4 so this looks to be a problem with the new http-persistent. Thanks!

~/.rvm/gems/ruby-2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize': wrong number of arguments (given 2, expected 0) (ArgumentError)
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:21:in`new'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:21:in `with_net_http_connection'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in`call'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/request/encode_json.rb:23:in`call'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in`run_request'
        from ~/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'

**Comment by iMacTia** [comment]
Hi @ThomasBJones2 
Unfortunately it looks like `net-http-persisten` introduced some breaking changes in its 3.0.0 release, making Faraday incompatible.
#616 is fixing the maximum version to 2.9.x, you will need to do the same in your project's Gemfile as a short term fix.

The long term fix would be instead to update the adapter and make it compatible with v3.0.0 of the gem, but that will also require to drop support for ruby 1.9.3.

**Comment by ThomasBJones2** [comment]
Cool, thanks --- Just wanted to make sure the community was aware.

**Comment by iMacTia** [comment]
Something is moving #619 !
Closing.
