### ISSUE TITLE
HTTPClient adapter with SSL enabled should not reset sessions on every request

### ISSUE THREAD

**Issue by dgolombek** [lostisland/faraday#624]
There is a very bad interplay between Faraday and HTTPClient that causes HTTPClient to flush its session store on every request, causing SSL re-negotiation each request. This kills performance, obviously. Part of this is a bug in HTTPClient but part is hard to work-around there and hence I'm opening an issue here to discuss the best fix.

On every Faraday request the adapter calls configure_ssl, which in turn calls httpclient.ssl_config.verify_mode= and httpclient.ssl_config.cert_store= which have the horrible side effect of calling reset_all on the httpclient object, which closes all open SSL sessions.

In HTTPClient, verify_mode= should only reset all sessions if the verify mode is changed, which I'll submit a patch to HTTPClient to fix. But for cert_store= it's much harder, since the cert store is a OpenSSL::X509::Store object which doesn't have a comparator and writing one would be challenging (it's a C struct). I assume that Faraday sets the cert store so that it can ensure that set_default_paths is called on it, since HTTPClient.ssl_config.cert_store is already a OpenSSL::X509::Store. 

The caller can work around this by providing it's own cert_store, but it's not reasonable to require that of the caller to get decent performance. So I'm trying to figure out best fix here. My first thoughts:

1. Store the cert_store inside the request ssl options, provide the same one to HTTPClient each time, allowing a simple comparator in HTTPClient to determine when it has changed
2. Call set_default_paths on HTTPClient.ssl_config.cert_store directly
3. Figure out how to write a comparator on OpenSSL::X509::Store
4. Add some intelligence to the HTTPClient adapter to only do SSL configuration the first time a call is made to a given URL.

Option 1 is the easiest and safest, since we could basically just do
ssl[:cert_store] ||= OpenSSL::X509::Store.new
but I wanted to see if there were other thoughts before I submitted a patch doing so.

**Comment by iMacTia** [comment]
Hi @dgolombek and thanks for pointing this out.
I had a look at the code and I can confirm that `configure_ssl` method is called for every request. This is causing the behaviour you described.

I agree with you this is not the smartest way to manage it, I can only suppose this was a design issue for the adapter.
Point 4 is out of discussion, as this is a request option and thus could change on every request.
Point 3 is probably overkilling 😅 
Point 2 I'm not really sure about the consequences

As you said point 1 appears to be the fastest and easiest.
I can see the issue you point out [starting from here](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/httpclient.rb#L101).

Would it be a working solution if we lazy load that cert_store and reuse it in the future calls?
This would prevent calling `OpenSSL::X509::Store.new` every time and HTTPClient would be able to do an object match on it.

**Comment by dgolombek** [comment]
Yeah, lazily loading the cert_store and reusing it would certainly work.

**Comment by iMacTia** [comment]
I think that makes sense also from a solution point of view.
It's just a waste of resources to create a new `OpenSSL::X509::Store` everytime.
Happy to review a PR with the lazy evaluation fix, but only if we have the confirm on the HTTPClient side that it will be enough for them and they'll implement the object-match on their side

**Comment by dgolombek** [comment]
The maintainer of httpclient just agreed that nahi/httpclient#343 was a problem and merged the fix I provided, which implemented the object-match inside httpclient. I'll submit a patch for this now.
