### ISSUE TITLE
Get a DENY if I am requesting a Redmine server

### ISSUE THREAD

**Issue by choallin** [lostisland/faraday#627]
I want to create a Redmine issue with the RESTful service from Redmine with the help of Faraday. I have configured the request this way:  
```  
      request = {
        "project_id" => PROJECT_ID,
        "tracker_id" => TRACKER_ID,
        "status_id" => INITIAL_STATE_ID,
        "subject" => "#{title} in query #{query_id}",
        "description" => params.get('error.detail'),
        "addigned_to_id" => EDV_USER_ID,
      }

      con = ::Faraday.new(url: "http://" + REDMINE_URL + "/issues.json") do |faraday|
        # faraday.response :logger
      end
      con.post do |req|
        req.headers['Content-Type'] = 'application/json'
        req.headers['X-Redmine-API-Key'] = ENV["REDMINE_API_KEY"]
        req.body = request.to_json
      end
```
When I take a look in the redmine logs I don't see that the request hits the server, and the response seems to be an array that looks like this:
```
p response ==>
[
    [0] 200,
    [1] {
                "X-Frame-Options" => "DENY",
        "Content-Security-Policy" => "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'"
    },
    [2] []
]
```
Do I have a wrong configuration?

**Comment by iMacTia** [comment]
Hi @choallin, you're simply missing the adapter in your middlewares list.

This is a pretty common issue (and we're discussing on how to address it once and for all), but as soon as you pass a block to `Faraday.new`, you're clearing the default middlewares stack and you have to build it from scratch.

Just add the adapter to your block and it will start working:

```ruby
con = ::Faraday.new(url: "http://" + REDMINE_URL + "/issues.json") do |faraday|
  # faraday.response :logger
  faraday.adapter Faraday.default_adapter
end
```

**Comment by iMacTia** [comment]
Closing as I suppose this is fixed, but feel free to reopen if that's not the case 👍 !

**Comment by choallin** [comment]
Thanks! That solved it.

Maybe you can make it more explicit in the docu that you have to set the adapter if you are using the block style setup. At least for now.
