### ISSUE TITLE
Faraday::Adapter::NetHttp Does Not Handle IOError

### ISSUE THREAD

**Issue by sshaw** [lostisland/faraday#630]
`Net:HTTP` [calls write](https://github.com/ruby/ruby/blob/8e3838707642a8209ec8deed32ac52f11007040b/lib/net/protocol.rb#L229), which can raise an `IOError`

Note that [the exception list](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http.rb#L12) has `EOFError`, which is an `IOError`

**Comment by iMacTia** [comment]
Hi @sshaw and thanks for your PR.

Indeed `IOError` is a generic exception that could be risen while using `Net::HTTP`, we'll discuss internally to decide if this should be included in the exceptions list or not.
