### ISSUE TITLE
Providing external data to faraday middleware

### ISSUE THREAD

**Issue by guyisra** [lostisland/faraday#639]
Is there a way to access app information (like cookies, rack env data, or any other variables) from within the faraday middleware?

Seem all it has is env, how can I give it more data?

**Comment by iMacTia** [comment]
Hi @guyisra.

Middlewares should be simple classes (ideally implementing the `call` method only) that simply transform the request or the response. For this reason, the context should be the request or the response, any external context (like the controller, the action that is being executed, and so on) should not be part of it.

That said, I understand there could be some exceptions and edge cases, so if you need to pass informations to the middlewares, you can:

1. If you instantiate the Faraday connection everytime, pass the context (controller, cookies, whatever) to the middleware as an additional constructor parameter (see example 1)
2. If you instantiate the connector once, you will need to pass to it some shared memory storage where he'll find the context you need to perform the call.

Example 1:

```ruby
class MyCustomMiddleware < Faraday::Middleware
  def initialize(app = nil, cookies = nil)
    @cookies = cookies
    super(app)
  end

  def call(env)
    # Do something using @cookies
  end
end

# Then in the controller
Faraday.new(...) do |req|
   request MyCustomMiddleware, self.cookies
end
```

An implementation for point 2 is much more difficult to provide as it depends on the nature of the information you need to share between the middleware and the controller.
I'm happy to try helping you if you'll provide a more practical example of what you're trying to achieve.

**Comment by jondot** [comment]
@iMacTia in the case of shared memory on thread local variables, when requests run in another thread it'll disappear. In general, do Faraday run requests on a different thread?

**Comment by iMacTia** [comment]
@jondot that completely depends on the Adapter you use.
The default adapter, based on Ruby standard `Net::HTTP` is definitely synchronous and don't use any additional thread.
There are however other adapters that perform asynchronous requests using threads or fibres (e.g. EM adapters) that could thus not have access to the thread shared memory.

Another possible solution, a bit more complex, would be to put the information you need in the request body when creating the request, accessing and removing it in the middleware
