### ISSUE TITLE
is Request::Retry safe to use with Connection#in_parallel

### ISSUE THREAD

**Issue by ericcj** [lostisland/faraday#641]
what is the behavior of retries within in_parallel?  it would be great to document this on https://github.com/lostisland/faraday/wiki/Parallel-requests

**Comment by iMacTia** [comment]
Hi @ericcj, this is indeed a good question and not obvious at all.

Here is the code for the `Request::Retry` middleware:

```ruby
def call(env)
      retries = @options.max
      request_body = env[:body]
      begin
        env[:body] = request_body # after failure env[:body] is set to the response body
        @app.call(env)
      rescue @errmatch => exception
        if retries > 0 && retry_request?(env, exception)
          retries -= 1
          sleep sleep_amount(retries + 1)
          retry
        end
        raise
      end
    end
```

So as you can see, all it does is wrapping the @app.call into a begin/rescue block.
`@errmatch` will be substituted with the exceptions you specify in your middleware initializer.

When you use `in_parallel`, you're delegating `EventMachine` to perform all the requests for you and block/run your application execution based on that.

The two things are thus unrelated and the "result" of their combination really depends on which adapter you use.

If the adapter you use is asynchronous, then the retry middleware will be mainly useless, as `@app.call` won't rise any exception (I'm not 100% sure about this one, it's worth a test).
But if you use a synchronous adapter then the exception will be rescued and the request retried. This means that the overall parallel requests will take longer to be executed as you have to wait ALL of them to be completed.
