### ISSUE TITLE
net_http adapter keeps using the proxy from system env

### ISSUE THREAD

**Issue by shawzt** [lostisland/faraday#643]
+ lib/net/http.rb: Net::HTTP now automatically detects and uses proxies from the environment, see https://github.com/ruby/ruby/commit/9416becda4592f7884460a054fe12b7761f6f055

+ >Net::HTTP use proxy from env as default, so even though we set '' to faraday proxy and use net_http as the adapter, in the end, Net::HTTP will still use the proxy from system env.
    >
    >And Net::HTTP.Proxy is obsolete, so move to use Net::HTTP

Here is the PR: #642

**Comment by iMacTia** [comment]
Hi @shawzt, the proxy management have just been refactored using `URI#find_proxy` method.
This is included in release 0.12.0.
Could you please let me know if you still have this issue?
Thanks

**Comment by iMacTia** [comment]
Proxy management has been completely refactored now (0.12.2) so this issue should be solved
