### ISSUE TITLE
Should we permit custom members on RequestOptions?

### ISSUE THREAD

**Issue by hobodave** [lostisland/faraday#660]
I'm looking to start a discussion around permitting custom members on `RequestOptions` identical to how it's implemented for `Env`.

We have need to inject contextual data for a request via the request options, such that it can be used by the Faraday middleware stack. 

For example:

```ruby
module RemoteClient
  module BaseClient
    def initialize(request_context = nil)
      @request_context = request_context || RequestContext.new
    end

    def get(url, options={})
      run_request(:get, url, options)
    end

    def post(url, options={})
      run_request(:post, url, options)
    end

    def put(url, options={})
      run_request(:put, url, options)
    end

    private

    def run_request(method, url, options={})
      options[:context] ||= {}
      options[:context][:transaction_id] = @request_context.transaction_id
      options[:context][:parent_span_id] = @request_context.span_id

      options[:headers] ||= {}
      options[:headers][Request::REQUEST_ID_HEADER] ||= @request_context.transaction_id
      options[:headers][Request::PARENT_SPAN_ID_HEADER] ||= @request_context.span_id

      Global.faraday.run_request(method, url, options[:body], options[:headers]) do |request|
        request.params.merge!(options[:params]) unless options[:params].nil?
        request.options[:context] = options[:context]
        request.options.open_timeout = options.fetch(:open_timeout, DEFAULT_OPEN_TIMEOUT_S)
        request.options.timeout = options.fetch(:timeout, DEFAULT_TIMEOUT_S)
      end
    end
  end
end
```

By injecting our "request context" data into the RequestOptions this permits our logging middleware to do things like:

```ruby
class Logging < Faraday::Middleware
    def initialize(app, options = {})
      super(app)

      @logger = StenoLogger.new(options.fetch(:filename, 'faraday_steno.log'))
    end

    def call(env)
      start_time = Time.now
      context = env[:context]

      logger.add_context!(context)
      logger.debug('http.out.start', http_out_start_data(env))

      @app.call(env).on_complete do |response_env|
        context[:response_time] = Time.now - start_time
        logger.add_context!(context)
        logger.info('http.out', http_out_data(response_env))
      end
    end
end
```

Please keep in mind the above pastes are significantly simplified from a full cut n paste of our code. So if there is an obvious typo, it's from my hack-job here in the Github markdown editor.

Unless I'm missing something huge, there is simply no way to do this without monkey-patching `RequestOptions`. We do this:

```ruby
module Faraday
  class RequestOptions
    def []=(key, value)
      if in_member_set?(key)
        super(key, value)
      else
        custom_members[key] = value
      end
    end

    def inspect
      attrs = [nil]
      members.each do |mem|
        if value = send(mem)
          attrs << "@#{mem}=#{value.inspect}"
        end
      end
      if !custom_members.empty?
        attrs << "@custom=#{custom_members.inspect}"
      end
      %(#<#{self.class}#{attrs.join(" ")}>)
    end

    # Internal
    if members.first.is_a?(Symbol)
      def in_member_set?(key)
        self.class.member_set.include?(key.to_sym)
      end
    else
      def in_member_set?(key)
        self.class.member_set.include?(key.to_s)
      end
    end

    # Internal
    def custom_members
      @custom_members ||= {}
    end

    # Public
    def [](key)
      if in_member_set?(key)
        super(key)
      else
        custom_members[key]
      end
    end

    # Internal
    def self.member_set
      @member_set ||= Set.new(members)
    end
  end
end
```

Should this be something that is moved upstream into Faraday proper? I'm happy to toss up the PR w/ tests if that is reasonable. 

If not, why? Is there a "blessed" way to do what I want? Thanks!

**Comment by iMacTia** [comment]
Hi @hobodave and thanks for your input.
I understand what you're trying to achieve here as I found myself in the same situation.
Every time, the solutions was not the most elegant one and I would love to get this properly addressed in Faraday.

I think your proposed solution is powerful, but maybe a bit overkilling as it's overriding a lot of methods from the superclass `Faraday::Options`.

What I think could be an easier yet still powerful solution would be to add an additional member to `Faraday::RequestOptions` which is not internally used and allows you to store arbitrary data into the request.
Something like:

```ruby
# Adds :context to the list of RequestOptions members
class RequestOptions < Options.new(:params_encoder, :proxy, :bind,
    :timeout, :open_timeout, :boundary, :oauth, :context)
```

This way, backward-compatibility should be safely ensured.
What do you think? If that's ok with you, I would include this small change in the next release, no need for a PR 😄

**Comment by hobodave** [comment]
@iMacTia Sure, is this what the usage would look like?

```ruby
faraday.run_request(method, url, body, headers) do |request|
request.options.context = {
  foo: 'foo',
  bar: 'bar'
}
end
```

**Comment by iMacTia** [comment]
Yes, that's the idea!
you should then be able to access those information in all middlewares through the `env`

**Comment by hobodave** [comment]
@iMacTia Yep, I agree. I just tested it with a monkey-patch and it looks far cleaner than my current solution.

**Comment by CyborgMaster** [comment]
This idea sounds awesome.  @hobodave, do you have a fork I can test, or can I see your monkey-patch?

**Comment by iMacTia** [comment]
Hi @CyborgMaster, I've just pushed this change into mater (https://github.com/lostisland/faraday/commit/617c909c9c1bd5955537b4e4646744fc9bd8bfe1).
Feel free to give it a try and let me know your feedbacks

**Comment by CyborgMaster** [comment]
@iMacTia, I just tested it on master and it works great thanks!  I'm using this inside of ActiveRecord to allow a Faraday middleware to hang API errors on the instance's errors hash so they can be processed by our standard error handling pipeline.  

Would you consider a cutting a new RubyGem's release? If you've got more planned before you release a new version, that's fine, I can continue to use it off of a commit hash, but it would be nice to use a official release.

**Comment by CyborgMaster** [comment]
I motion that this issue be closed.

**Comment by iMacTia** [comment]
Indeed, @hobodave was happy as well with this change so I'm now closing this issue.
@CyborgMaster, a new release (v0.12.0) was scheduled for last week and have been delayed to give us some more time to test a new feature (no_proxy support).
As soon as that is sorted, I'll proceed with the release

**Comment by hobodave** [comment]
👍  thanks!

**Comment by activeliang** [comment]
```ruby
module CustomRequestExtension
  attr_accessor :retry_if
end
Faraday::RequestOptions.prepend(CustomRequestExtension)
conn = Faraday.new do |f|
  f.request :retry, {
    max: 3,
    interval: 0.15,
    interval_randomness: 0.5,
    backoff_factor: 2,
    methods: [],
    exceptions: [Faraday::SSLError, Faraday::RetriableResponse],
    retry_statuses: [
      # 2xx 成功
      200, 201, 202, 203, 204, 205, 206,
      # 3xx 重定向
      300, 301, 302, 303, 304, 305, 306, 307,
      # 4xx 客户端错误
      400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 
      412, 413, 414, 415, 416, 417, 428, 429, 431, 451
    ],
    retry_if: -> (env, _exc) {
      if env[:request].retry_if
        env[:request].retry_if.call(env)
      end
    },
    retry_block: -> (env, options, retry_count, exception) { puts "retry block..." }
  }
end

conn.get('http://localhost:3001/api/v1/test') {|req| req.options.retry_if = -> (res) { !res['success'] }}
```
