### ISSUE TITLE
Infinite recursion getting default_adapter

### ISSUE THREAD

**Issue by dmitchell** [lostisland/faraday#663]
I noticed this on my local env and then also when I pushed to koala. If I reinstall the gem it goes away, but I don't have control to reinstall the gem on koala's travis server. I'm wondering if the gem was changed to fix this wo changing the version number?

example failure: https://travis-ci.org/arsduo/koala/jobs/197762805 which has this in the stack trace
```
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/connection.rb:74:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:112:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:112:in `default_connection'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:100:in `method_missing'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:59:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/options.rb:257:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/options.rb:257:in `new_builder'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/connection.rb:74:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:112:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:112:in `default_connection'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday.rb:100:in `method_missing'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:59:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/options.rb:257:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/options.rb:257:in `new_builder'
     # ./vendor/bundle/ruby/2.2.0/gems/faraday-0.11.0/lib/faraday/connection.rb:74:in `initialize'
```

**Comment by iMacTia** [comment]
Hi @dmitchell,

version 0.11.0 was not released multiple times, so we could be assisting a bug in the Faraday connection initialiser.
Are you able to debug the failing code to see in detail what's going on and what is causing the recursion? Or would you be able to give us a code snippet that reproduces the issue?

Thanks

**Comment by dmitchell** [comment]
It's coming from https://github.com/dmitchell/koala/blob/master/spec/cases/http_service_spec.rb#L197
but you can see it in the Travis log whose url I put in the original request. That line above is rather indirect. It's purely in the Faraday instantiation that it fails with that cycle of going to `options -> rack_builder -> method_missing` where the last step should just be Faraday L29 `attr_reader :default_adapter` set via L106 (`self.default_adapter = :net_http`) instead of `method_missing`. Of course, looking at the history, none of those lines have changed in years.

**Comment by iMacTia** [comment]
Hi @dmitchell,
I had a look at Travis log, and the first failure seems related to:

> Koala::HTTPService DEFAULT_MIDDLEWARE uses the default adapter
Failure/Error: allow(Faraday).to receive(:default_adapter).and_return(adapter)

I think this is somehow causing `Faraday.default_adapter` to disappear, which then causes the infinite loop because of the `method_missing`

**Comment by dmitchell** [comment]
Aha, yeah that makes sense. I'll look at that. Although the error went away
for me when I re-installed the gem. Very very odd :-) But, I agree that now
that you say that, it looks like that expression is some sort of mock
installer.

**Comment by iMacTia** [comment]
Hi @dmitchell did you have a chance to look at this any further 😃 ?
I would really like to close the Issue if we can exclude a Faraday bug

**Comment by dmitchell** [comment]
Can no longer reproduce. I think it was a set of incompatible gems.

**Comment by rful011** [comment]
One way to reproduce this easily is to use ruby -r debug.

**Comment by iMacTia** [comment]
Hi @rful011 if you're still experiencing this please open a new issue and add as much information as possible so that we can help
