### ISSUE TITLE
Bypass proxy using no_proxy not working 

### ISSUE THREAD

**Issue by nisharanij-cuelogic** [lostisland/faraday#667]
I have http_proxy, no_proxy set in my environment.
When I have mentioned my host inside no_proxy faraday unable to bypass that host, it routes through http_proxy which should not
I am using Faraday version 0.11.0. I observed that changes related to proxy are there in master branch but not there in latest faraday version. Is it possible to merge  latest code with version or is there any work around in current 0.11.0 version?

**Comment by iMacTia** [comment]
Hi @nisharanij-cuelogic,

you're right, `no_proxy` option was just recently merged in and I initially planned to release it last Friday but I was delayed.
I will try to release it as soon as possible, until then I suggest you to use the master branch from Github as a temporary solution!
If you could give us a feedback on the `no_proxy` feature before I release it, that would be very appreciated!

In case you don't know how to do it, this is how you you use a gem from Github on bundler:

```ruby
gem 'faraday', github: 'lostisland/faraday'
```

**Comment by nisharanij-cuelogic** [comment]
Added gem 'faraday', github: 'lostisland/faraday' to Gemfile and performed bundle, Still request goes to proxy

**Comment by iMacTia** [comment]
Can I ask you the exact values of your `http_proxy` and `no_proxy` ENV variables?
Is this configuration working in any other application?

**Comment by nisharanij-cuelogic** [comment]
export http_proxy=http://username:password@ip:port
export no_proxy=myhost, myhost:port

when I tried to request my host using curl http://myhost:port/ it's working fine but when tried using faraday it's not

**Comment by iMacTia** [comment]
Ok thanks @nisharanij-cuelogic, I'll ask you to do a couple of additional tests:

1. Try to remove all the spaces from the `no_proxy` ENV variable, especially after each coma
2. Try to open the rails console and check what you see under `ENV['http_proxy']` and `ENV['no_proxy']` before running `Faraday.new(:url => 'http://api:81')`.

**Comment by nisharanij-cuelogic** [comment]
In rails console
irb(main):003:0> ENV['http_proxy']   
=> "http://username:password@ip:port"
irb(main):004:0> ENV['no_proxy']  
=> "127.0.0.1,localhost,127.0.0.1:9506,api:81,api"

Still no luck

**Comment by iMacTia** [comment]
Thanks for the details @nisharanij-cuelogic.
I'm on holiday until mid next week so not sure I can help before then.
Maybe @somethingnew2-0 can help you out in the meantime as he have done the PR to support the `no_proxy`.

Please leave an update here if you find anything useful.
Thanks

**Comment by somethingnew2-0** [comment]
Taking a look and messing around with tests I can't seem to make it fail.

The relevant tests are https://github.com/lostisland/faraday/blob/master/test/connection_test.rb#L379-L450
which you can run with `bundle exec script/test test/connection_test.rb`

and
https://github.com/lostisland/faraday/blob/master/test/adapters/integration.rb#L207-L214
which you can run with `bundle exec script/test test/adapters/default_test.rb`

Let me know if you can narrow down a failure case!

**Comment by iMacTia** [comment]
Thanks @somethingnew2-0. It seems strange to me as well, maybe an issue with the server configuration? But environment variables look fine...

@nisharanij-cuelogic do you have any useful update for us? Are you still having this issue?

**Comment by jadhavnisha25** [comment]
I removed spaces from no_proxy, mentioned host in no_proxy for bypass  and did changes in connection.rb [here](https://github.com/lostisland/faraday/pull/675). It worked for me

**Comment by iMacTia** [comment]
Hi @jadhavnisha25 (are you @nisharanij-cuelogic or another person??), I can see your PR is based on branch 0.9!
The support for `no_proxy` is only available on version 0.11.0 or above of Faraday.
If you're using version 0.9 of the gem then unfortunately this feature is not available and I hope you'll understand we are not releasing any update for that branch anymore.

**Comment by iMacTia** [comment]
Closing as stale.
