### ISSUE TITLE
How use %20 instead of using + in GET query string

### ISSUE THREAD

**Issue by Edison-Hsu** [lostisland/faraday#676]
I have a param_v2 parameter in GET query, like
```
param_v2=(windcode:600004.SH OR researcherid:170969)
```

but in Faraday,
query will be:
```
param_v2=%28windcode%3A600004.SH+OR+researcherid%3A170969%29
```
Faraday replaces ' ' with '+' so that server will parse incorrectly.

My question is:

how to parse the query so that the result will be:
```
param_v2=%28windcode%3A600004.SH%20OR%20researcherid%3A170969%29
```

Just replaces ' ' with '%20' so that server will parse correctly ?

**Comment by iMacTia** [comment]
Hi @Edison-Hsu,
If you want to use a different parameter encoding from Faraday's default one, you can define your own params encoder and use it when initialising the Faraday connection:

```ruby
class CustomParamsEncoder
  def self.encode(params)
    Faraday::NestedParamsEncoder.encode(params).gsub(/\+/, '%20')
  end

  def self.decode(query)
    Faraday::NestedParamsEncoder.decode(query)
  end
end

conn = Faraday.new('http://yourapi.com', request: { :params_encoder => CustomParamsEncoder })
conn.get('/something?param_v2=(windcode:600004.SH OR researcherid:170969)')
```
