### ISSUE TITLE
checksum does not match for faraday 0.12.0 gem

### ISSUE THREAD

**Issue by jasnow** [lostisland/faraday#679]
Getting this for new 0.12.0 version of faraday gem.
```
Bundler cannot continue installing faraday (0.12.0).
The checksum for the downloaded `faraday-0.12.0.gem` does not 
match the checksum given by the server. This means the contents of 
the downloaded gem is different from what was uploaded to the
server, and could be a potential security issue.
```

**Comment by iMacTia** [comment]
Hi @jasnow,
I'm really sorry about that, the same happened with `faraday_middleware` some time ago.
An issue is already open on Rubygems (https://github.com/rubygems/rubygems.org/issues/1551#issuecomment-290918613) to investigate this.
I'll probably re-release it in the next days, you can temporarily solve the issue forcing the version on your Gemfile.

**Comment by coderanger** [comment]
Could you yank the broken gem in the meantime since it can't be installed?

**Comment by domcleal** [comment]
I opened #680 with a change to the Travis CI config to hopefully avoid it, per the comment on the Rubygems issue (indicating it's a race with multiple uploads).

**Comment by shizza** [comment]
Can the gem be yanked till it gets resolved please.

**Comment by tibbon** [comment]
I encountered this as well.

**Comment by fly3110** [comment]
so as I

**Comment by amunro** [comment]
+1

**Comment by iMacTia** [comment]
Faraday 0.12.0.1 released with fix checksum fix 👍 
https://rubygems.org/gems/faraday

**Comment by jasnow** [comment]
Verified fixed. THANKS!
