### ISSUE TITLE
The place of the `connection.request :multipart` change the result of the file upload

### ISSUE THREAD

**Issue by ForelaxX** [lostisland/faraday#688]
The version I'm using is:
faraday (0.9.2)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.11.0.1)

Here is my code:

```
    @connection ||= Faraday.new(url: 'xxx') do |connection|
      connection.request :multipart
      connection.adapter Faraday.default_adapter
      connection.request :url_encoded
    end
    payload = { :file => Faraday::UploadIO.new(file_path, 'image/png') }
    response = @connection.post 'xxx', payload do |request|
      request.headers = get_headers('POST', 'xxx')
      request.params = {filename: upload_name}
    end
```

If I put the `connection.request :multipart` on the first line of the initialize block, the content of the http request body is file content like other file upload http request.

But when I put  `connection.request :multipart` to other line, the content of the http request body is a string like this: `file=%23%3CUploadIO%3A0x007fa53508ff70%3E`.I don't know if it is a bug?

**Comment by iMacTia** [comment]
Hi @ForelaxX,

as a general rule, `connection.adapter` should always be the last one in the block, so that the adapter will be the innermost middleware in the stack.

Try again with this setup and see if it works:

```ruby
@connection ||= Faraday.new(url: 'xxx') do |connection|
  connection.request :multipart
  connection.adapter Faraday.default_adapter
  connection.request :url_encoded
end
```

**Comment by ForelaxX** [comment]
Thanks，it works!
