### ISSUE TITLE
Deletes with bodies

### ISSUE THREAD

**Issue by Carlbc18** [lostisland/faraday#693]
HTTP spec has changed in 2014 and allows for deletes to have bodies.  Is there a plan in place to resolve your delegator method in connection.rb to allow for a body with the delete method and not nil'ing it out?

**Comment by Carlbc18** [comment]
A PR will be up shortly for your review.

**Comment by iMacTia** [comment]
Hi @Carlbc18,

could you please provide a link to the above changes?
I guess that's only true for HTTP 2.0 specs, so we might need to consider this feature carefully.

**Comment by Carlbc18** [comment]
https://tools.ietf.org/html/rfc7231#section-4.3.5

**Comment by Carlbc18** [comment]
i have a code change with test that works (not sure if you want it). how do i create a pr for this project?

**Comment by Carlbc18** [comment]
> I guess that's only true for HTTP 2.0 specs, so we might need to consider this feature carefully.

this is actually part of HTTP 1.1

**Comment by iMacTia** [comment]
I would definitely consider it if you want to create a PR.
You can do it as with any other repo, simply fork `faraday` and apply the changes on your fork, then create a PR to our master branch.

**Comment by Carlbc18** [comment]
Thanks @iMacTia. I'll put it up.  Whats your views on changing the version finally have a major version number with this?  This change could be breaking for many.  I'd like to follow semver pattern, and version faraday to be 1.0.0 at this point.  Let me know your thoughts.

**Comment by iMacTia** [comment]
We're definitely trying to stick to semver and we've v1.0 scheduled with some breaking changes.
If this change is gonna break backward compatibility, then it will be released only in version 1.0 (which currently doesn't have a fixed release date).
However, my understanding is that you should now be able to OPTIONALLY add a body to GET, HEAD and DELETE requests, so shouldn't that be backward compatible? Am I missing something?

**Comment by Carlbc18** [comment]
@iMacTia i versioned to 0.13.0 and the PR is up.  We can take any other conversation around this to the PR as i'm sure there will be comments.  Thanks again!

**Comment by iMacTia** [comment]
There's an issue though, this might only work with ruby >= 2 as ruby 1.9 doesn't support keyword params 😞

**Comment by Carlbc18** [comment]
I think in regards to this not working on ruby 1.9 I feel like that is ok. Ruby 1.9 is many years old. I'd advocate we version bump to at least 2.0 for minimum ruby version, which would go inline with a v1.0 release of Faraday.  Also option 2 more closely follows http 1.1 spec in my opinion as you'd have the option to pass parms and or a optional body.

 I feel like attempting to maintain backwards compatibility with a http spec feature that does work with ruby 1.9 is going to cause problems. I think this feature would be better suited for V1 of Faraday. I feel like there are too many variables were needing to support for this change (ruby v, params passing). Maybe I'm overthinking....

**Comment by iMacTia** [comment]
> I think in regards to this not working on ruby 1.9 I feel like that is ok. Ruby 1.9 is many years old. I'd advocate we version bump to at least 2.0 for minimum ruby version, which would go inline with a v1.0 release of Faraday. Also option 2 more closely follows http 1.1 spec in my opinion as you'd have the option to pass parms and or a optional body.

I totally agree with al the above. That's indeed the best course of action, even though this means we'll still have to wait for v1.0

**Comment by iMacTia** [comment]
So to define a v1.0 backward compatible API, we could attempt the following:

## GET, HEAD, DELETE REQUESTS

```ruby
conn = Faraday.new(...) # note no special config here
conn.get(path, url_params, body: {...})
# second parameter is URL PARAMS, optionally accept a named parameter for request body
# works the same for head and delete
```

## POST, PUT, PATCH REQUESTS

```ruby
conn = Faraday.new(...) # note no special config here
conn.post(path, url_params, url_params: {...})
# second parameter is REQUEST BODY, optionally accept a named parameter for url_params
# works the same for put and patch
```

I think this way we're covering every possible combination and extending post/put/patch requests as well!

**Comment by Carlbc18** [comment]
Definitely agree. Do we want to decline my PR and open a new one for this? Is there a V1 branch cut we can work off of?

**Comment by iMacTia** [comment]
Happy to close that one and start from scratch as it will be completely different. Sorry for that!

I'll create a V1 branch before merging in so feel free to start from master and I'll redirect the PR :)

**Comment by iMacTia** [comment]
Hi @Carlbc18 just wanted to let you know that branch `1.0` is now available for you 😃.

**Comment by Carlbc18** [comment]
Thank you, thank you! 😀

**Comment by HusseinElMotayam** [comment]
For anyone still waiting on this, I found the following workaround which seems to work in my case:

```
conn = Faraday.new
body = {
some_key: 'some value'
}
conn.run_request(:delete, url, body, headers)
```

I hope this helps someone until delete no longer nils the body by default

**Comment by thaiden** [comment]
So is there any update on when this will be available?

**Comment by iMacTia** [comment]
I haven't seen any PR yet, but works on v1 are slowly progressing.
I might be able to work on this myself but I can't give an estimate at the moment.
The updated API on how requests should work is explained on my [comment](https://github.com/lostisland/faraday/issues/693#issuecomment-305429333) above, so if anyone wants to have a shot at it before me, a PR is very welcome.

For a fully backwards compatible solution, the PR can be branched out of master, and I can make another 0.x release.
If the change is going to break backwards compatibility then it's better to branch out of `1.0` branch

**Comment by technoweenie** [comment]
https://github.com/lostisland/faraday/pull/855 is a draft PR to support this.

**Comment by technoweenie** [comment]
I'm rejecting this feature. You can use the block form in Faraday to make a request with a body:

```ruby
conn.delete(url) do |req|
  req.body = { some_key: 'some value' }
end
```

This idea would have made simple deletes with bodies a single one liner, but the implementation adds more complexity and surprising behavior than I'd like. This block form works great in Faraday already. I prefer modifying properties on a class to adding more arguments to a method:

```ruby
conn.delete('/foo/1') do |req|
  req.headers["X-Men"] = "marvel"
  req.params[:confirm] = 1
  req.body = { some_key: 'some value' }
end
```
