### ISSUE TITLE
Error undefined method `each' for String

### ISSUE THREAD

**Issue by jonnyparris** [lostisland/faraday#697]
I get an error when trying to send a delete request like below:
`@response = Faraday.send(http_method, "#{API_URL}#{path}", params.to_json)`

The error is: 
`NoMethodError:
       undefined method 'each' for #<String:0x0000000594b7b8>`
and the top few lines from the trace are:
`  /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/utils.rb:149:in 'update'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:150:in 'block in delete'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:383:in 'block in run_request'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:397:in 'block in build_request'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/request.rb:26:in 'block in create'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/request.rb:25:in 'tap'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/request.rb:25:in 'create'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:393:in 'build_request'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:379:in 'run_request'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in 'delete'
     /var/lib/gems/2.3.0/gems/faraday-0.12.1/lib/faraday.rb:100:in 'method_missing'
`
Have I missed something?
It runs fine for post requests with the same arguments.

**Comment by iMacTia** [comment]
Hi @jonnyparris,

DELETE requests don't accept a Body like POST, therefore passing `params.to_json` as the last parameter is not the correct thing to do in this case (but it works for POST as that will be set on the body of the request). The third parameter, in fact, will be used to populate the query string in the URL.

You can try passing `params` simply (I suppose that's an hash?). That should put them in the URL.
If you're objective is to make a DELETE request with a body, I'm afraid but that's currently not possible with Faraday. Good news however is that we're working on it (#693)

**Comment by jonnyparris** [comment]
Ok! Thanks a lot for the quick reply. I am trying to make a DELETE request with a body so will code a workaround for now.

**Comment by iMacTia** [comment]
Keep an eye on #693 then because that's exactly what we're going to add in the next release 😉 
I'll close this one for now.
