### ISSUE TITLE
undefined method `path' for "https://accounts.google.com":String

### ISSUE THREAD

**Issue by khanimdad** [lostisland/faraday#699]
Am getting this error when using "koala" / "omniauth-google-oauth2",

And here is the top few lines of stack trace.

faraday (0.11.0) lib/faraday/connection.rb:310:in `url_prefix='
faraday (0.11.0) lib/faraday/connection.rb:77:in `initialize'
faraday (0.11.0) lib/faraday.rb:67:in `new'
faraday (0.11.0) lib/faraday.rb:67:in `new'
oauth2 (1.3.1) lib/oauth2/client.rb:57:in `connection'
oauth2 (1.3.1) lib/oauth2/client.rb:72:in `authorize_url'
oauth2 (1.3.1) lib/oauth2/strategy/auth_code.rb:18:in `authorize_url'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:48:in `request_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:218:in `request_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
bullet (5.5.1) lib/bullet/rack.rb:10:in `call'
hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'

**Comment by iMacTia** [comment]
Hi @khanimdad,

I'm trying to reproduce this using Faraday but unfortunately I'm not able to.
Did you open an issue on `koala` Github Repo?

**Comment by khanimdad** [comment]
Hi @iMacTia , actually the issue is with Faraday but not with Koala or other gem, i did a monkey patch for it and its working now.

```
##
# Faraday monkey patch for 
# ERROR - NoMethodError (undefined method `path' for "https://accounts.google.com":String): 
#


module Faraday

  class Connection
    
    # Returns the parsed URI from teh given input..
    def url_prefix=(url, encoder = nil)
      uri = @url_prefix = URI(url) # was Utils.URI(url)
      self.path_prefix = uri.path

      params.merge_query(uri.query, encoder)
      uri.query = nil

      with_uri_credentials(uri) do |user, password|
        basic_auth user, password
        uri.user = uri.password = nil
      end

      uri
    end

  end
end
```

**Comment by iMacTia** [comment]
As you can see from [here](https://github.com/lostisland/faraday/blob/v0.11.0/lib/faraday/utils.rb#L262) the Utils.URI method returns a URI object. The only exception is that `String` responds_to `host`, which is not the case in plain Ruby.
I suspect something in your project (a gem, a dependency, whatever) is changing this behaviour causing the issue.
If it's a rails project, you can try opening the console and executing the following:

```ruby
Faraday.new('https://accounts.google.com')
```

This works fine for me but might fail for you.

**Comment by khanimdad** [comment]
@iMacTia ,  below worked for me as well

```
Faraday.new('https://accounts.google.com')
=> #<Faraday::Connection:0x0000000a226398 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.11.0"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x0000000a2262d0 @handlers=[Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://accounts.google.com/>, @proxy=nil>
```

**Comment by iMacTia** [comment]
Then I don't really understand what's going on with that Gem...
Glad you found a workaround anyway 👍 !
I'll make some other tests to see if I can reproduce, but for the time being I'll close this one.
