### ISSUE TITLE
Getting Faraday::Connection using Sufia

### ISSUE THREAD

**Issue by prasanthrubyist** [lostisland/faraday#704]
Faraday::ConnectionFailed: Failed to open TCP connection to 127.0.0.1:8984 (Connection refused - connect(2) for "127.0.0.1" port 8984)

Kindly let me know, whats wrong in my side

**Comment by iMacTia** [comment]
Hi @prasanthrubyist, I suppose you simply don't have a server listening on 127.0.0.1:8984.
I'm sorry but this has probably nothing to do with faraday.
Whatever server application you're trying to run, please double-check configuration there is ok
