### ISSUE TITLE
What are the default timeouts?

### ISSUE THREAD

**Issue by stevepm** [lostisland/faraday#708]
Having trouble finding it in the code.

**Comment by iMacTia** [comment]
Hi @stevepm,
Short answer: There are no default timeouts, or put in another way, default timeouts are infinite.


Detailed explanation: This might actually change based on the adapter you choose. Faraday doesn't set the adapter timeout unless you enforce it, so the "adapter default" is the one used. In most cases (if not all) this means no timeout. I haven't used all the adapter so I can't tell you te default for each of them, however the default one (Net::HTTP) has no timeout by default

**Comment by spuyet** [comment]
FTR, `Net::HTTP` default `open_timeout` and `read_timeout` is 60 seconds since ruby 2.3.

**Comment by connorshea** [comment]
The Request Options in the docs says this defaults to `nil`, does that override the 60 second default of Net::HTTP or does Faraday end up deferring to the default Net::HTTP timeout if none is set explicitly by the user when configuring a Faraday request? https://lostisland.github.io/faraday/#/customization/request-options?id=request-options

**Comment by iMacTia** [comment]
As the docs say, `nil` will keep the adapter default. You can see the exact implementation for the Net::HTTP adapter [here](https://github.com/lostisland/faraday-net_http/blob/main/lib/faraday/adapter/net_http.rb#L152-L170) (the `request_timeout` method is defined [here](https://github.com/lostisland/faraday/blob/main/lib/faraday/adapter.rb#L85)) and confirm that if `nil` is provided then `http.read_timeout`, `http.write_timeout` and `http.open_timeout` are not set.

**Comment by iMacTia** [comment]
I've also updated my comment at the top of the thread based on feedback. I'm sorry I didn't mean to provide misleading information.
