### ISSUE TITLE
"no_proxy is unsupported" floods my logs

### ISSUE THREAD

**Issue by maksimf** [lostisland/faraday#713]
I'm running Rails app which makes around 1 request per 2-3 seconds using Faraday, I have `ENV['no_proxy']` var defined, which makes Faraday to write `no_proxy is unsupported` inside my logfile every 2-3 seconds:

https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L447

Do you think this warn is really necessary?

**Comment by iMacTia** [comment]
Hi @maksimf, I'm sorry this is annoying you.
The warning should get displayed if the `no_proxy` env variable is set and you use faraday in such a way that it won't be supported. We added that warning because most of the times people assume Faraday will use the `no_proxy` but that doesn't happen. So the warning is there to tell them something is wrong with the setup.
So let me understand:

* How are you instantiating your Faraday connection?
* Are you actually OK with Faraday not picking the `no_proxy` setting? Or would you like it to use it?

**Comment by maksimf** [comment]
> How are you instantiating your Faraday connection?

I'm using memoization, like:
```
def client
  @client ||= Faraday.new
end
```
Whereas this `client` gets called from the infinite loop from the separate thread.

> Are you actually OK with Faraday not picking the no_proxy setting? Or would you like it to use it?

Yep, I'm using Docker, which presets `no_proxy` env variable. Of course I can get rid of that variable and the issue would be solved, but since it's the default behaviour I thought I might report it.

**Comment by iMacTia** [comment]
Mmmmh if that's the case, then you should see the warning only once, not every time you run a request, as the method gets called only at initialisation.
Do you mind sharing some more code on how you use your `client`?

**Comment by maksimf** [comment]
Like this:
```ruby
client.get(url, params) do |req|
  req.headers = # headers here

  req.options[:timeout] = config.read_timeout
  req.options[:open_timeout] = config.connection_timeout
end
```

I also use `builder.adapter :net_http_persistent`

**Comment by iMacTia** [comment]
I support `url` is an absolute url?
Do you know that if the first part of the url is always the same then you can pass it to the initializer and save it for next time?

Example:

```ruby
client = Faraday.new
client.get('https://my_api.com/resource1/path', params)
client.get('https://my_api.com/resource2/path', params)
...
```
can be written as:

```ruby
client = Faraday.new('https://my_api.com')
client.get('/resource1/path', params)
client.get('/resource2/path', params)
...
```

You can also specify `timeout` and `open_timeout` as connection options, so you don't need to set them for each request.
I understand it doesn't change much for you, but if you use the first version then that will trigger the warning every time.

**Comment by maksimf** [comment]
That's awesome, thank you!
