### ISSUE TITLE
`:test adapter` and "Unexpected middleware set after the adapter."

### ISSUE THREAD

**Issue by cimnine** [lostisland/faraday#717]
In my specs I heavily rely on faraday's `:test` adapter.

Since #685 was merged and released in 0.12.2, I get a lot of warnings like the following:

    WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.

Here's a short excerpt on how I initialised [Faraday in my code](https://github.com/ninech/netbox-client-ruby/blob/master/spec/shared_contexts/faraday.rb#L13) until now:

```ruby
RSpec.shared_context 'faraday connection', faraday_stub: true do
  # ...

  let(:faraday_logger) { nil }
  let(:faraday_stubs) { Faraday::Adapter::Test::Stubs.new }
  let(:faraday) do
    Faraday.new(url: NetboxClientRuby.config.netbox.api_base_url,
                headers: NetboxClientRuby::Connection.headers) do |faraday|
      faraday.adapter :test, faraday_stubs
      faraday.request :json
      faraday.response :json, content_type: /\bjson$/
      faraday.request faraday_logger if faraday_logger
    end
  end
  
  # ...
end
```

When I now follow the suggestion in #685 and [rearrange the code](https://github.com/ninech/netbox-client-ruby/commit/7b8fe61dcf85e0d5af8bb036a2c3b788630240a1) as follows, [I get tons of failed tests](https://travis-ci.org/ninech/netbox-client-ruby/builds/262293728):

```ruby
RSpec.shared_context 'faraday connection', faraday_stub: true do
  # ...

  let(:faraday_logger) { nil }
  let(:faraday_stubs) { Faraday::Adapter::Test::Stubs.new }
  let(:faraday) do
    Faraday.new(url: NetboxClientRuby.config.netbox.api_base_url,
                headers: NetboxClientRuby::Connection.headers) do |faraday|
      faraday.request :json
      faraday.response :json, content_type: /\bjson$/
      faraday.request faraday_logger if faraday_logger
      faraday.adapter :test, faraday_stubs # moved to the last position
    end
  end
  
  # ...
end
```

The error's always `no stubbed request for #{METHOD} #{URL} #{ARGS}`.

My specs don't fail when `faraday.request :json` is after `faraday.adapater :test`, but of course then I get the warnings again:

```ruby
RSpec.shared_context 'faraday connection', faraday_stub: true do
  # ...

  let(:faraday_logger) { nil }
  let(:faraday_stubs) { Faraday::Adapter::Test::Stubs.new }
  let(:faraday) do
    Faraday.new(url: NetboxClientRuby.config.netbox.api_base_url,
                headers: NetboxClientRuby::Connection.headers) do |faraday|
      faraday.response :json, content_type: /\bjson$/
      faraday.request faraday_logger if faraday_logger
      faraday.adapter :test, faraday_stubs
      faraday.request :json # like this, tests don't fail
    end
  end
  
  # ...
end
```

Any idea why this behaves like it does? Does the `:test` adapter perhaps infer something from `.request :json`?

**Comment by cimnine** [comment]
So I think I figured it out. As I understand it,

* when `faraday.request :json` is after `faraday.adapter :test`, then the `EncodeJson` adapter is applied when creating the *stub request* and naturally also applied to the *actual request* (the one, that later ends up in the `:test` adapter).
  The comparison of the *actual request's body* with the *stubbed request's body* is then `'{"serialized":"body"}'.eql?('{"serialized":"body"}')`. These values are equal and the tests therefore succeeds.
* when `faraday.request :json` is before `faraday.adapter :test`, then the `EncodeJson` adapter is **not applied when creating the stub request**, but *still applied to the actual request*.
  The comparison of the *actual request's body* with the *stubbed request's body* is then `'{"serialized":"body"}'.eql?( { serialized: "body" } )`. As one is a `String` and the other one is a `Hash`, the comparison fails.

Because no *stubbed request* known to the `:test` adapter matched the *actual request* made, it will tell that `no stubbed request [...]` was defined.

For now, commenting out `faraday.request :json` makes all tests pass again. This workaround is alright for this case.

But in general I would expect that all `request` adapters are applied to the *stubbed requests* before comparing the *actual requests* to the *stubbed requests*.

**Comment by iMacTia** [comment]
@cimnine I'm not really sure if this differs for the test adapter, but if a middleware is loaded AFTER the adapter then that middleware (especially if it's a request middleware) is basically ignored. I'm not really sure I understand what you mean by "that middleware is applied also to all stubbed requests" as the middleware should only change the request and not affect the stubs (this might be clear if you provide some additional code showing your stubbed requests as well). 

I think that the JSON middleware in your connection setup has always been ignored so far. 
My guess is that your stubs are expecting the body to be a Hash, so when you move the `faraday.request :json` middleware in the correct place, they start failing.

This is my explanation for the behaviour you're getting, let me know if it makes sense 😄

**Comment by cimnine** [comment]
> My guess is that your stubs are expecting the body to be a Hash, so when you move the faraday.request :json middleware in the correct place, they start failing.

Oh, I never looked at it from that perspective. I think you're right on that. Then all is well I guess and I learned a bit about Faraday's internals in the process.
