### ISSUE TITLE
default_uri_parser stops working

### ISSUE THREAD

**Issue by shlima** [lostisland/faraday#721]
For the faraday-0.13.0 `Faraday::Utils.default_uri_parser` is not properly working

**Comment by iMacTia** [comment]
Hi @shlima,
Can you please provide more details on the issue?
Do you have any code example that is working with 0.12 but failing with 0.13?

That would really help investigating!
Thanks

**Comment by shlima** [comment]
I am using `Addressable::URI` as my URLS contains UTF-8 characters and standard ruby URI library raises an error in this case. 

Faraday v.0.13.0 parses URL using standard ruby URI class in `run_request ` method https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L377

**Comment by iMacTia** [comment]
Mmmmh I wasn't aware of this, but I'm quite sure we use URI in other parts of the application as well.
The only difference I see is that I did `URI(url)` instead of the usual `URI.parse(url)`.
Can you show me and example of your URLs so I can make some tests?

**Comment by shlima** [comment]
```ruby
Faraday::Utils.default_uri_parser = ->(value) do
  Addressable::URI.parse(value)
end

# Faraday v.0.12.2
Faraday.new.get('http://example.com/üäë') #=> OK

# Faraday v.0.13
Faraday.new.get('http://example.com/üäë') #=> URI::InvalidURIError: URI must be ascii only "http://example.com/\u00FC\u00E4\u00EB"
```

**Comment by iMacTia** [comment]
Thanks @shlima, now I have a better understanding of the issue.
I wasn't aware of these specific use cases, but I'll try to get this fixed soon with v0.13.1.
For the time being, I can only suggest you to fix your Faraday version to "~> 0.12.2"

**Comment by iMacTia** [comment]
@shlima I have created a PR to address this issue #722.
I've done some quick tests on my console and it seems working with your examples.
Can you please use that PR branch in your project to run some tests and let me know if it fixes your issues as well? Thanks

**Comment by shlima** [comment]
@iMacTia yes, it works perfectly, thanks

**Comment by iMacTia** [comment]
Great, I'll merge this in and release 0.13.1 If I can get the tests green again 😅
