### ISSUE TITLE
Manually setting a proxy without using the environment is broken after 0.13.0

### ISSUE THREAD

**Issue by klieth** [lostisland/faraday#723]
Hello,

In commit d18cc04be5c179b1b22b9dd1004030dd43b0ca58, this line was added to the `run_request` method:
```
+      @temp_proxy = proxy_from_env(url) if url && URI(url).absolute?
```

If there is no proxy in the environment, the proxy passed to the connection is set to `nil` whether or not `conn.proxy` was set to something.

To reproduce:
```
ENV.delete_if { |k| k =~ /http(s)?_proxy/i }

c = Faraday::Connection.new
c.proxy = "http://proxy.url"
p c.get("https://google.com")
```

This throws the following exception:
```
<project>/ruby/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to google.com:443 (Address family not supported by protocol - socket(2) for "google.com" port 443) (Errno::EAFNOSUPPORT)
```

After digging in with the gem, printing out the value of `@temp_proxy` before and after the line I mentioned above shows this:

```
      # Resets temp_proxy
      @temp_proxy = self.proxy

      # Set temporary proxy if request url is absolute
      p @temp_proxy
      @temp_proxy = proxy_from_env(url) if url && Utils.URI(url).absolute?
      p @temp_proxy
```
```
#<Faraday::ProxyOptions uri=#<URI::HTTP http://proxy.url>>
nil
```

When I monkey-patch out the offending line, the connection starts working again.

**Comment by klieth** [comment]
Oh, also, that is a confusing error thrown--it's just because I don't have an IPv6 address configured. It also fails with this when I'm not trying to hit a destination with a AAAA record:

```
<project>/ruby/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to espn.com:80 (Connection refused - connect(2) for "espn.com" port 80) (Faraday::ConnectionFailed)
```

**Comment by iMacTia** [comment]
Hi @klieth I understand your issue and I've prepared a PR to address that (#724).
However, I'm going to go on holiday for a couple of weeks so I'll merge this is once I'm back 😄.
I would appreciate if you could give it a shot using my branch in the meantime.

Thanks

**Comment by klieth** [comment]
Thanks so much for the quick turnaround! The PR looks good to me. I'll give the fix a try in my project.

**Comment by iMacTia** [comment]
Hi @klieth sorry I completely forgot about this one.
Were you able to test the fix?
