### ISSUE TITLE
Changing in headers (problem with case-sensitivity in some API)

### ISSUE THREAD

**Issue by golovlevviktor** [lostisland/faraday#732]
I`ve tried to work with some API and i was need to add header ['API-KEY']. After request i was sent 401 message 'unauthorised', so what a surprise was where i  found in request my ['API-KEY'] became an ['Api-Key']. I think that it`s better have to NOT change values, am i right? Thank you.

**Comment by iMacTia** [comment]
Hi @golovlevviktor, any reason why you closed this?

**Comment by golovlevviktor** [comment]
I was not attentive enough, the problem is in Net::Http, not in Faraday. I
should not have written without having studied the problem to the end.

On Sep 13, 2017 19:08, "Mattia" <notifications@github.com> wrote:

Hi @golovlevviktor <https://github.com/golovlevviktor>, any reason why you
closed this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lostisland/faraday/issues/732#issuecomment-329217166>,
or mute the thread

**Comment by iMacTia** [comment]
No worries at all, I'm glad you were able to find and fix the issue 👍
Thanks for letting me know
