### ISSUE TITLE
How to rescue SSL error with em_synchrony

### ISSUE THREAD

**Issue by joanniclaborde** [lostisland/faraday#737]
Hi,

When I try to get a URL with a bad certificate, using Synchrony, an SSL error is raised somewhere in Faraday. Is there any way to rescue this exception, before it breaks the whole even loop?

Here's a test case:

```ruby
require 'em-synchrony'
require 'faraday'

EM.synchrony do
  begin
    conn = Faraday.new 'https://expired.badssl.com' do |f|
      f.adapter :em_synchrony
    end
    conn.get '/'
  rescue StandardError => e
    puts "Rescued: #{e.message}"
    puts e.backtrace
  end

  puts 'End of block'
end

puts 'End of test'
```

And its output, notice the unhandled `OpenSSL::SSL::SSLError` at the end, instead of the expected `End of test`:

```
$ ruby test.rb 
Rescued: connection closed by server
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/em_synchrony.rb:55:in `call'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
test.rb:9:in `block in <main>'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/em-synchrony-1.0.6/lib/em-synchrony.rb:39:in `block (2 levels) in synchrony'
End of block
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/em_http_ssl_patch.rb:23:in `ssl_verify_peer': unable to verify the server certificate for "expired.badssl.com" (OpenSSL::SSL::SSLError)
	from /home/vagrant/.rvm/gems/ruby-2.3.5/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	from /home/vagrant/.rvm/gems/ruby-2.3.5/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.3.5/gems/em-synchrony-1.0.6/lib/em-synchrony.rb:39:in `synchrony'
	from test.rb:4:in `<main>'
```

Thanks!

**Comment by iMacTia** [comment]
Hi! You can disable SSL check passing an option to Faraday.new 
Unfortunately I don’t remember the exact syntax and it’s a bit hard on mobile to look through the code, I’ll try to provide more info later if you can’t find them

**Comment by joanniclaborde** [comment]
We will probably go for a workaround instead: use the `net_http` adapter and do the async call manually:

```ruby
require 'em-synchrony'
require 'faraday'

EM.synchrony do
  EM::Synchrony.defer do
    begin
      conn = Faraday.new 'https://expired.badssl.com' do |f|
        f.adapter :net_http
      end
      conn.get '/'
    rescue StandardError => e
      puts "Rescued: #{e.message}"
      puts e.backtrace
    end
    puts 'End of block'
    EM.stop
  end
end

puts 'End of test'
```

```
$ ruby test.rb 
Rescued: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/protocol.rb:44:in `connect_nonblock'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/protocol.rb:44:in `ssl_socket_connect'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/http.rb:928:in `connect'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/http.rb:852:in `start'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/http.rb:1384:in `request'
/home/vagrant/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/net/http.rb:1142:in `get'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
test.rb:25:in `block (2 levels) in <main>'
/home/vagrant/.rvm/gems/ruby-2.3.5/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
End of block
End of test
```

**Comment by iMacTia** [comment]
Hey!
No need to switch to another adapter, here is the code you're interested in:

```ruby
# https://github.com/lostisland/faraday/blob/29feeb92e3413d38ffc1fd3a3479bb48a0915730/lib/faraday/adapter/em_http_ssl_patch.rb#L37
def verify_peer?
  parent.connopts.tls[:verify_peer]
end
```

So in theory you should be able to do something like this:

```ruby
conn = Faraday.new('https://expired.badssl.com', tsl: { verify_peer: false }) do |f|
  f.adapter :net_http
end
```

**Comment by joanniclaborde** [comment]
We'd rather not turn off verification. It looks like it's been a [known issue for a while](https://github.com/lostisland/faraday/issues/112#issuecomment-47043005), we'll use our workaround for now.

**Comment by iMacTia** [comment]
Totally agree, turning off verification is simply a potential TEMPORARY solution.
If you’re happy with your fix then better to use that. I’m sorry I’m not that expert on EM to help in this case.

Closing the issue :)

**Comment by Siva454** [comment]
@iMacTia  Could you please help on this issue ? I am trying to install wbench for client /browser performance .....

DevTools listening on ws://127.0.0.1:12114/devtools/browser/ec8bf90a-f504-4905-a
f25-e401a51dac5a
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_conne
ct returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLE
rror)
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_conn
ect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:948:in `connect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:876:in `start'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/timi
ngs/app_server.rb:9:in `result'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:28:in `app_server_results'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in `block (3 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/brow
ser.rb:34:in `visit'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:20:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:18:in `times'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:18:in `block in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:17:in `tap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:17:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/lib/wbench/benc
hmark.rb:4:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/wbench-1.1.1/bin/wbench:43:i
n `<top (required)>'
        from C:/Ruby24-x64/bin/wbench:23:in `load'
        from C:/Ruby24-x64/bin/wbench:23:in `<main>'

Kindly help me to move forward on this issue

**Comment by iMacTia** [comment]
Hi @Siva454, I can see you joined GitHub only hours ago so I suppose you're confusing things a little.
This repository is about a gem called `faraday`. The gem you're using is called `wbench`.

If you have an issue with `wbench` you should open a new Issue in their repository.
To do that, simply follow [this link](https://github.com/desktoppr/wbench/issues/new), put a title and a description, then finally click on "Submit new issue".

WBench maintainers will be notified of your issue and will help you solving it.
I didn't develop that gem so unfortunately I'm unable to help you.

**Comment by Siva454** [comment]
Thank you @iMacTia
