### ISSUE TITLE
Passing custom metadata to middlewares

### ISSUE THREAD

**Issue by dantethegrey** [lostisland/faraday#742]
Hi, 

we've written a simple latency logging middleware. It measures the time the request takes and logs it. Now we'd like to be able to tag the log message with additional metadata (like 'fetching asset data from CMS'). That means we need to be able to pass the metadata to the middleware together with the request. Obviously I could use some form of global variable, but that's ugly.

I was thinking about sth in lines of adding `userdata` attribute to `RequestOptions`. What do you think?

Dan

**Comment by iMacTia** [comment]
Hi @dantethegrey,

I'm happy to say this feature was recently introduced, you just need to use the `context` option.
You can read more about it at the end of the [Basic Use](https://github.com/lostisland/faraday#basic-use) section in the README.

**Comment by dantethegrey** [comment]
thanks, love it! and sorry for not checking latest releases first.

**Comment by iMacTia** [comment]
No worries! It’s quite easy to miss :)
Glad you love it!
