### ISSUE TITLE
[Feature request] multipart/form-data with duplicate names

### ISSUE THREAD

**Issue by tylerlong** [lostisland/faraday#755]
## Basic Info

* Faraday Version: 0.13.1
* Ruby Version: 2.3.0

It is a real world requirement: https://developer.ringcentral.com/api-docs/latest/index.html#!#SendFaxMessageRequest

![image](https://user-images.githubusercontent.com/733544/34351669-241a7876-ea59-11e7-80db-6891be478fc9.png)

You can see that there are three files with the same file name: `attachment`.

But I can only specify one of them `payload[:attachment] = Faraday::UploadIO.new('./spec/test.png', 'image/png')` Specifying more will override existing ones.

I know it is possible with query parameters: https://github.com/lostisland/faraday#changing-how-parameters-are-serialized

Now I request the similar feature for multipart/form-data request body.

One option is to make `payload[:attachment]` support an array as value.

**Comment by Tongboy** [comment]
I think you can pass them in as multiple values in the hash

something like
```ruby
payload = { :attachment[0] => Faraday::UploadIO.new(...), :attachment[1] => Faraday::UploadIO.new(...) }

**Comment by tylerlong** [comment]
@Tongboy. Nope,  it doesn't work. I've tested. The server side doesn't recognize the attachments if I copy your sample.

**Comment by iMacTia** [comment]
Hi @tylerlong, apologies I'm not a `multipart/form-data` expert as I rarely use them.
However I had a quick look at the middleware ([here](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/multipart.rb#L52)) and I noticed that it might be able to manage an Arrays and Hashes as well (`case` at line 56).
My suggestion would be to try something like:

```ruby
payload[:attachment] = [Faraday::UploadIO.new(...), Faraday::UploadIO.new(...)]
```

**Comment by iMacTia** [comment]
Hi @tylerlong, how did the test go?
Did it work? Or maybe you found another solution?

**Comment by iMacTia** [comment]
Closing assuming the middleware did his job, happy to reopen if that's not the case

**Comment by tylerlong** [comment]
Yes, it works!

```ruby
payload[:attachment] = files.map{ |file| Faraday::UploadIO.new(file[0], file[1]) }
```

Many thanks!

**Comment by iMacTia** [comment]
Thanks for the feedback!
Glad it works :)

**Comment by adrian-netapay** [comment]
@iMacTia I am trying somethig like this but does not work. 

`def attachment
if @transaction.product_id == ViewTransaction::MINI

  return [Faraday::FilePart.new(File.open(CreatePdfAction.new(@transaction,'tickets').execute),
                                       'application/pdf',
                                       File.basename("Ticket")),
           Faraday::FilePart.new(File.open(CreatePdfAction.new(@transaction,'vouchers').execute),
                                               'application/pdf',
                                               File.basename("Voucher"))]
else
  return Faraday::FilePart.new(File.open(File.open(CreatePdfAction.new(@transaction,'vouchers').execute),
                        'application/pdf',
                        File.basename(template))
end`

whith one file works fine, but with array not.

**Comment by iMacTia** [comment]
@adrian-netapay I'm afraid I'll need more information to help.
Please open a new issue and provide as much details as possible, including:
* Ruby and Faraday versions
* Faraday connection setup (middleware list)
* Request example
