### ISSUE TITLE
How to keep spaces between params?

### ISSUE THREAD

**Issue by j-jackson** [lostisland/faraday#757]
I'm making a request to an api that requires space between the params:

`api.domain.com/v1/books?q='Book Title'`

But by default the prams are encoded as:

`api.domain.com/v1/books?q=%27Book+Title%27`

I have tried `api.domain.com/v1/books?q=Book%20Title` using the `params_encoder` but it still doesn't work.

I have also tried:

```ruby
  def self.encode(params)
    Faraday::NestedParamsEncoder.encode(params).gsub(/\+/, " ")
  end
```

But it reverts back to `api.domain.com/v1/books?q=%27Book+Title%27`

Does anyone have any suggestions on how I can get around this?

**Comment by iMacTia** [comment]
Hi @j-jackson, yeah the `+` is a Rails convention and it usually works for most people. Of course it doesn't work if you have a different backend.
The easiest way for me to help is to see exactly what the API is expecting (I'm still not sure, for example, about those quotes around the query).
Are you able to successfully call the API using CURL? If yes, what's the exact path you use?
Once we get that working, it should be much easier to replicate the same using Faraday

**Comment by iMacTia** [comment]
Hi @j-jackson, are you still having issues with this?

**Comment by iMacTia** [comment]
Closing as stale, happy to reopen if still an issue for someone

**Comment by Karthik-M-L** [comment]
Hi,

We are also facing same issue, do u have any work around for this.

Regards,
Karthik M L

**Comment by iMacTia** [comment]
As I explained in my comment,
