### ISSUE TITLE
Convert tests to RSpec

### ISSUE THREAD

**Issue by iMacTia** [lostisland/faraday#762]
We currently use MiniTest to test Faraday, but I'm personally not used to it and maintenance is becoming an issue.
Moreover, world seems to have moved to RSpec so I'd like to try rewriting tests with that and reach 100% coverage.

**Comment by markfrst** [comment]
@iMacTia Hi, this issue is actual at the moment?

**Comment by iMacTia** [comment]
Hi @markfrst, yes I’ve been working on it for a while now, although slowly on my spare time 😅.
You can see the progress on the `feature/#762-rspec` branch

**Comment by markfrst** [comment]
@iMacTia thx, i can help with it 🤓

**Comment by iMacTia** [comment]
That would be very welcome!
Feel free to branch out of the `feature/#762-rspec` and open a PR against it.
Since we might be working on it at the same time, I'd suggest small PRs focused on few files 👍

**Comment by markfrst** [comment]
@iMacTia okay

**Comment by iMacTia** [comment]
@markfrst If you're still willing to help, I'd suggest you joining us on [gitter](
https://gitter.im/lostisland/faraday) so we can avoid working on the same files/features concurrently 😃 
Please note I've been working on tests over the weekend and merged latest master changes, so you might need to pull.

**Comment by markfrst** [comment]
@iMacTia okay, i joined to gitter. i will try find time for help, maybe i will be have time on the next weekend ⏳

**Comment by iMacTia** [comment]
This is now completed as of #832 🎉
