### ISSUE TITLE
RubyMultipartPost boundaries aren't idempotent

### ISSUE THREAD

**Issue by kwasimensah** [lostisland/faraday#772]
https://github.com/lostisland/faraday/pull/673 made multipart posts use SecureRandom.hex for boundaries. However, that means my VCRs (https://github.com/vcr/vcr) now think things are changing when they're really not.

Is there an option for the old behavior? Or to at least specify what I want for my boundary so I can make it static?

**Comment by iMacTia** [comment]
Hi @kwasimensah and thanks for pointing this out.
I'm sorry but we didn't add an option for that so the only solution atm is to override the `unique_boundary` method when running tests.

I agree it would be a good idea to add an option that removes the security part of the boundary.
Will try to get some time to work on it, but a PR is also welcome

**Comment by kwasimensah** [comment]
I worked around it by adding: 

```
default_connection_options = Faraday::ConnectionOptions.new
default_connection_options.request.boundary = "------------------RubyMultiPartPost".freeze
Faraday.default_connection_options = default_connection_options
```

to config/environments/test.rb

**Comment by iMacTia** [comment]
Thanks @kwasimensah, you're right, the boundary is only set if not specified already.
You should be able to do the same with a single line:

```ruby
Faraday.default_connection_options.request.boundary = "------------------RubyMultiPartPost".freeze
```
