### ISSUE TITLE
Incomplete testing documentation

### ISSUE THREAD

**Issue by Nondv** [lostisland/faraday#779]
Hi!
I really like that faraday has adapter for testing (actually, I'm rewriting one of our apps business logic to use faraday instead of active resource, because it's a lot more convinient to write specs with).

But README section on testing describes basically only adapter initialization.
E.g. I had to open source code just to know that I can provide regexp as stubbed path and I still don't know if there's a "proper way" to get post params as hash in request handler (im using CGI.parse for that).

So it would be really nice to have a definitive testing guide.

**Comment by iMacTia** [comment]
Hi @Nondv, you raised a very good point.
Faraday falls quite short when it gets to documentation.
It's one of the main point for v1.0, so I'm not planning to do much work about this on master for the simple reason that most of the time would be "wasted" writing documentation that would change for v1.0 anyway. In the meantime of course feel free to ask any particular question you may have. I understand this is not ideal but I hope you'll understand the situation 😄

I've added your issue to the corresponding card in the v1.0 project to be sure I won't forget: https://github.com/lostisland/faraday/projects/1#card-6991198

Also, I strongly suggest you to checkout [Her](https://github.com/remiprev/her). It's the spiritual successor of the now dead ActiveResource and is entirely based on Faraday. I used it in the past and it worked pretty well for RESTful APIs.
