### ISSUE TITLE
Set array parameters from a Ruby array

### ISSUE THREAD

**Issue by sferik** [lostisland/faraday#78]
Faraday should allow you to set array parameters using the following syntax:

``` ruby
Faraday.new(:url => 'http://localhost:1234').get do |request|
  request.url('foo', 'bar' => ['baz', 'qux'])
end
```

Currently, doing this makes the following request:

```
GET /foo?bar=baz&bar=qux
```

I propose it should make this request instead, in keeping with Rack:

```
GET /foo?bar[]=baz&bar[]=qux
```

Currently, to get this result, you must construct your request like this, which is a bit ugly ugly:

``` ruby
Faraday.new(:url => 'http://localhost:1234').get do |request|
  request.url('foo', 'bar[]' => ['baz', 'qux'])
  #                      ^ eww, gross
end
```

Discuss.

**Comment by iMacTia** [comment]
Given that pull request #199 was merged, this can probably be closed.

**Comment by kofronpi** [comment]
The pull-request is a bit vague, would be good to add a quick example when closing such an issue :+1:

**Comment by iMacTia** [comment]
Sorry I was a bit in a rush and couldn't provide an example here, but you can see a good example from the tests in #199:

```ruby
def test_build_url_bracketizes_repeated_params_in_query
  conn = Faraday::Connection.new
  uri = conn.build_url("http://sushi.com/sake.html", 'a' => [1, 2])
  assert_equal "a%5B%5D=1&a%5B%5D=2", uri.query
end

def test_build_url_without_braketizing_repeated_params_in_query
  conn = Faraday::Connection.new
  conn.options[:params_encoder] = Faraday::FlatParamsEncoder
  uri = conn.build_url("http://sushi.com/sake.html", 'a' => [1, 2])
  assert_equal "a=1&a=2", uri.query
end
```

In short, Faraday now by default serialises array "the rack way" with the "[]" after the variable name.
However, you can set `Faraday::FlatParamsEncoder` as `params_encoder` to get them serialise without brackets.

**Comment by anushamummina** [comment]
Hi I am facing the same issue when I am sending parameters with array to  faraday request. It is appending extra `[]` brackets to the key. I tried appending `params_encoder` attribute to faraday request but getting error like undefined method `params_encoder`

I am using faraday 0.9.2 version with rails 5. 

Can you please help to fix on this

**Comment by iMacTia** [comment]
Hi @anushamummina, version 0.9.2 should already contain all the changes to let you set `params_encoder`. Are you able to provide a code snippet to show the error you're getting?
