### ISSUE TITLE
Redirections are not respecting proxy settings

### ISSUE THREAD

**Issue by vdvcardoso** [lostisland/faraday#790]
## Basic Info

* Faraday Version: 0.14.0
* Ruby Version: 2.4.0

## Issue description
If a redirected request points to a domain in the "no_proxy" list, the connection will be made via proxy.

Consider the following:
no_proxy='amazonaws.com'
Request chef.io --Returns 302--> s3.amazonaws.com

A cURL request to the above will respect the no_proxy, sending "chef.io" to the proxy, and "s3.amazonaws.com" through the normal gateway.

However, through Faraday, the connection to s3.amazonaws.com will also be sent through the proxy.

This does not happen if the initial connection is part of no_proxy (for example: no_proxy='chef.io'), as it will correctly route the redirected request through the proxy.

## Steps to reproduce
The steps I took to reproduce this involve setting up a Squid proxy (for logging) and using Berkshelf to actually preform the connection to "https://supermarket.chef.io/api/v1/cookbooks/s3_file/versions/2.8.5/download", however a simple http connection that follows redirects should provide the same results.

I have included the squid and faraday logs that show the redirected request being sent to the proxy and the end result of a 403 (the proxy is denying access to amazonaws.com). If required I can also send the instructions I used to install chefDK and squid if you want to replicate like that.
[faraday_redirect.txt](https://github.com/lostisland/faraday/files/1927796/faraday_redirect.txt)

**Comment by iMacTia** [comment]
@vdvcardoso thanks for raising this issue.

As I mentioned on Gitter, the current implementation for `proxy/no_proxy` support only consider the request URL and already dynamically recalculates the proxy config if you provide an absolute URL when performing a call.
However, the recalculation doesn't currently happen for redirections.

I'm having a look at `Berkshelf` to understand how they follow redirects, but I couldn't find anything on master branch. Which version of the gem are you using?

**Comment by vdvcardoso** [comment]
I'm currently using version 6.3.1 of Berkshelf, which comes bundled with ChefDK (https://downloads.chef.io/chefdk | https://github.com/chef/chef-dk)

**Comment by iMacTia** [comment]
Hi @vdvcardoso sorry I only had time today to check this out again.
As I mentioned in my previous message, Faraday doesn't follow redirects out-of-the-box.
That functionality is provided by a middleware (and more precisely, [this one](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb)).

That middleware should probably reload the proxy/no-proxy when catching a 3xx response, but it doesn't at the moment.
I agree this is a missing functionality, but before I start doing any code change I wanted to ensure that `berkshelf` or `chef-dk` are actually using that middleware at all. There are many other ways to follow redirects and if they're using anything else, my fix will be completely useless.

I had a look at both but unfortunately couldn't find any trace of it and to be honest this is a bit low-priroty compared to the v1.0 roadmap.
I'd be inclined to park this for the time being, but if you can find any evidence of the middleware being used then I can of course reconsider.

**Comment by iMacTia** [comment]
Closing for the time being while waiting for further evidence.
Happy to reopen as soon as we get it 👍
