### ISSUE TITLE
empty array parameter value encodes incorrectly

### ISSUE THREAD

**Issue by senid231** [lostisland/faraday#800]
## Basic Info

parameters like `{ foo: { bar: [] } }` and `{ foo: [] }` encoded incorrectly

it's just being skipped. I don't think this is right behavior

related to https://github.com/JsonApiClient/json_api_client/issues/278

* Faraday Version:
0.15.1 and master github branch
* Ruby Version:
2.2.4

## Steps to reproduce
If possible, please provide the steps to reproduce the issue.
```ruby
>> Faraday::NestedParamsEncoder.encode(foo: { bar: [] }, baz: [])
=> "&"
```

I think correct behavior will be to encode it to `"baz%5B%5D&foo%5Bbar%5D%5B%5D"` or `"baz%5B%5D=&foo%5Bbar%5D%5B%5D="` or `"baz&foo%5Bbar%5D"`, `"baz=&foo%5Bbar%5D="`

**Comment by iMacTia** [comment]
Thanks for addressing this.
I agree this looks like a bug, I'll have a look at the PR as soon as possible.
Regarding the different solutions, I've tested them with Rails and:

* √ `"baz%5B%5D&foo%5Bbar%5D%5B%5D"` => `{ baz: [], foo: { bar: [] } }`
* X `"baz%5B%5D=&foo%5Bbar%5D%5B%5D="` => `{ baz: [""], foo: { bar: [""] } }`
* X `"baz&foo%5Bbar%5D"` => `{ baz: nil, foo: { bar: nil } }`
* X `"baz&foo%5Bbar%5D"` => `{ baz: "", foo: { bar: "" } }`

So the first one looks like the correct one to me 👍
