### ISSUE TITLE
SOCKS Proxy being ignored 

### ISSUE THREAD

**Issue by carlastabile** [lostisland/faraday#806]
## Basic Info

* Faraday Version: 0.14.0
* Ruby Version: 2.4.1

## Issue description
I've using Faraday for a while and now it seems the proxy I've configured is being ignored.

This is my configuration 

```
@manager = Faraday::Adapter::Typhoeus.setup_parallel_manager(max_concurrency: 3)

     Faraday.new(url: base_url, ssl: {verify: false}, parallel_manager: @manager, proxy: "socks5://#{ENV.fetch('TORPROXY_HOST')}:9050") do |c|
        c.options.open_timeout = 5
        c.options.timeout = 30
        c.use FaradayMiddleware::FollowRedirects, limit: 10
        c.use FaradayMiddleware::Gzip
        c.use :cookie_jar, jar: cookie_jar
        c.request :url_encoded
        c.request :retry, max: 10, interval: 0.1,
                  interval_randomness: 0.5, backoff_factor: 2,
                  exceptions: [
                      Zlib::GzipFile::Error,
                      Faraday::Error::TimeoutError,
                      Faraday::TimeoutError,
                      Faraday::Error::ConnectionFailed
                  ],
                  retry_if: -> (env, e) {
                    logger.info "Faraday retry: #{e.class}:#{e.message} (#{env})"
                    true
                  }
        c.adapter :typhoeus
      end

```

I was previously using version 0.13.2 of Faraday and read this issue [#786](https://github.com/lostisland/faraday/issues/786) so I updated to version 0.14.0 but I still get the same behaviour.

**Comment by iMacTia** [comment]
@carlastabile I'm sorry to hear you're having issues with Faraday, let's see if I can help.
Let's start with the easy question first: is this your full configuration? I don't see any adapter specified, which one are you using?

**Comment by carlastabile** [comment]
@iMacTia Hi, I updated the ticket with the complete configuration

**Comment by iMacTia** [comment]
Hi @carlastabile and apologies for the delay.
I only had time today to come back to this, and unfortunately I'm still unable to reproduce it.

I've tried the following (simplified) configuration using Faraday 0.15.2 and Ruby 2.4.1:

```
conn = Faraday.new(url: 'http://test.com', ssl: {verify: false}, proxy: "socks5://myproxy:9050") do |c|
  c.options.open_timeout = 5
  c.options.timeout = 30
  c.request :url_encoded
  c.adapter :typhoeus
end
```

If I remove the proxy option, my requests progress as expected, calling `http://test.com`.
However as soon as I specify the proxy option as shown above, my request times out, as that proxy doesn't exist. So I can't really say the proxy is being ignored, as it clearly changes the behaviour of the app. I don't have a proper proxy setup so I'm unable to investigate further without getting a setup.
Finally, adding the `parallel_manager` and the other middlewares didn't change anything: I'm still getting the timeout.

I'd suggest the following:

1. Try upgrading Faraday to 0.15.2
2. Try simplifying the configuration stack. Starts simple with just the adapter and the proxy config, and see if it works. The add the other middlewares and finally the parallel manager.

If this still doesn't help, then I'm gonna need some environment setup to reproduce the issue properly on my machine 😞. Like a docker image or a full setup guide. But honestly I hope we won't need to resolve to that 😅
