### ISSUE TITLE
Faraday::SSLError

### ISSUE THREAD

**Issue by resistorsoftware** [lostisland/faraday#807]
Trying the oAuth flow on a new App and this comes up:

    SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

* Faraday Version: 0.12.2
* Ruby Version: 2.5.1

## Issue description

SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
/Users/dlazar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:80:in `perform_request'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:38:in `block in call'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:33:in `call'
faraday (0.12.2) lib/faraday/request/url_encoded.rb:15:in `call'
faraday (0.12.2) lib/faraday/rack_builder.rb:141:in `build_response'
faraday (0.12.2) lib/faraday/connection.rb:386:in `run_request'
oauth2 (1.4.0) lib/oauth2/client.rb:99:in `request'
oauth2 (1.4.0) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.4.0) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
omniauth-oauth2 (1.5.0) lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'

So my Chrome browser version 67 seems to like my certificate, no trouble with HTTPS in the browser for my domain... but in the oAuth callback the calls choke. Any ideas?

**Comment by iMacTia** [comment]
Hi @resistorsoftware, could you please share your `Faraday::Connection` setup?
Unfortunately browser and Faraday (actually, Net::HTTP) use different tools to check certificates, so it may be that the latter doesn't like your certificate for some reason.

If that's the case, there are 3 solutions you can pursue:

1. Disable the SSL verification (discouraged). You can do so by passing `{ssl: {verify: false}}` as an option when initialising the connection.
2. Set the SSL verification depth. You can do so by passing `{ssl: {verify_depth: ...}}` as an option when  initialising the connection. I'm unsure what the best value for this option is, but that's more a question for Net::HTTP so I'd suggest you to do some research.
3. Customize Net::HTTP SSL verification by providing a `verify_callback` (see https://github.com/lostisland/faraday#nethttp).

Please let me know if any of these help 😄

**Comment by resistorsoftware** [comment]
Turned out, Puma-Dev failed to copy it's CA cert to the right place. Not sure how that suddenly happened, but in an upgrade of something somewhere, it did. Once I set the CA file in the chain, errors went away.

**Comment by iMacTia** [comment]
Thanks for the update and for closing the issue 👍!

**Comment by C-PET** [comment]
I am having the same issue regardless so far of the steps.
I have set SSL_VERT_FILE to the cacert.pem in system environment variables
I have also added 
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
as just a test in the .rb file.  Even with this in the code still getting 

D:/CBJ/f528053f/workspace/JENKINS-ADMIN/github_dsa_upload/github_dsa_upload/gh_license_report.rb:15: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER

D:/Ruby25-x64/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (Faraday::SSLError)

Of Note:  I am running the ruby job from a jenkins pipeline and I have added 'set' to the build commands just prior to running the ruby script.  In set it is not showing SSL_CERT_FILE though I can verify it is set globally on the build server.

**Comment by C-PET** [comment]
Traceback

Traceback (most recent call last):
        22: from gh_license_report.rb:31:in `<main>'
        21: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octoki
t/enterprise_admin_client/license.rb:13:in `license_info'
        20: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octoki
t/connection.rb:19:in `get'
        19: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octoki
t/connection.rb:156:in `request'
        18: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/
agent.rb:94:in `call'
        17: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/connection.rb:138:in `get'
        16: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/connection.rb:387:in `run_request'
        15: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/rack_builder.rb:143:in `build_response'
        14: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octoki
t/middleware/follow_redirects.rb:61:in `call'
        13: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octoki
t/middleware/follow_redirects.rb:73:in `perform_with_redirection'
        12: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/response.rb:8:in `call'
        11: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/response.rb:8:in `call'
        10: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/adapter/net_http.rb:38:in `call'
         9: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/adapter/net_http.rb:92:in `with_net_http_connection'
         8: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/adapter/net_http.rb:43:in `block in call'
         7: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/farad
ay/adapter/net_http.rb:85:in `perform_request'
         6: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:1213:in `get'
         5: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:1455:in `request'
         4: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:909:in `start'
         3: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         2: from D:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:981:in `connect'
         1: from D:/Ruby25-x64/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_
connect'
D:/Ruby25-x64/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_conne
ct returned=1 errno=0 state=error: certificate verify failed (unable to get loca
l issuer certificate) (Faraday::SSLError)

**Comment by C-PET** [comment]
Will try that.

Oddly enough running the script from another machine using Ruby24-x64 has no issue with running

**Comment by C-PET** [comment]
But it is using faraday-0.12.2

**Comment by iMacTia** [comment]
@C-PET However I see you're not using Faraday directly, but instead you're using [octokit](https://github.com/octokit/octokit.rb). My previous suggestion can't be done unless you have direct access to the faraday stack, which I'm unsure that gem will give you.

I'd suggest you open an issue in `octokit` if the problem persist and you can't get access to the Faraday initialiser.

**Comment by C-PET** [comment]
Will do.

Thanks

**Comment by C-PET** [comment]
Thanks for the insight I was able to make it work without issue, using the ruby 2.42 and a lower set of gems.

My guess would be that octokit has issue with the newer version of faraday possibly.

Thanks again
