### ISSUE TITLE
Faraday::ConnectionFailed: Connection reset by peer - SSL_connect on iphone hotspot

### ISSUE THREAD

**Issue by stephenarifin** [lostisland/faraday#808]
## Basic Info

* Faraday Version: 0.15.2
* Ruby Version: 2.3

## Issue description

I am receiving a `Faraday::ConnectionFailed: Connection reset by peer - SSL_connect error` whenever I try to make a Faraday connect to an specific API when I am on a hotspot with my iPhone. This issue only occurs with this specific domain using https on my hotspot, so I am wondering if I am missing something. When I use Faraday to connect to "https://www.google.com" on my hotspot, there are no issues.

Any help to figure out what is going would be great! I work a lot on hotspot and this would really help.

## Steps to reproduce

Connect yourself to your iPhone hotspot.

```ruby
faraday = Faraday.new(url: 'https://api.quovo.com/v3/') do |faraday|
  faraday.request :url_encoded
  faraday.response :logger
  faraday.use Faraday::Response::RaiseError
  faraday.adapter Faraday.default_adapter
end

faraday.get
# => Faraday::ConnectionFailed: Connection reset by peer - SSL_connect
```

**Comment by iMacTia** [comment]
Hi @stephenarifin,

since this works just fine on a normal Wifi (and I just tested it working on my laptop as well), I doubt this is an issue related to Faraday.
I can't test from a hotspot connection at the moment, but I'd suggest you to try the following:

1. Connect to your WiFi.
2. On a browser, try to open `https://api.quovo.com/v3/`

You should see the following XML message (this is what I see):
```xml
<error>
  <id>not_found</id>
  <message>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
  </message>
  <status>404</status>
</error>
```

3. Connect to the iPhone hotspot.
4. Try to reopen the page on the browser. Do you still see the xml message?

**Comment by stephenarifin** [comment]
Hey @iMacTia, thanks for the quick reply! You're right, this is not a Faraday issue. Following your steps, I do **not** see the xml message. I then tried to connect to `https://api.quovo.com/v3/` on my phone not connected to wifi and I still could not reach the host. Sorry for the false alarm.

Do you have any tips on how I can figure out what is going on? I'm a little bit of a noob in networking. I've had three other devices (all iphone) unable to connect to `https://www.quovo.com`. When my mac is tethered to my iPhone, I cannot connect to  `https://www.quovo.com`, but when my Windows computer is tethered, I can connect no problem.

You should be able to repro this if you have an iPhone. Go to the link  `https://www.quovo.com`. Any help would be appreciated, and feel free to close this issue.

**Comment by iMacTia** [comment]
@stephenarifin Glad that helped identifying the issue 👍.
I tried from my iPhone as well but unfortunately I can see `https://api.quovo.com/v3/` and `https://www.quovo.com` with no issues. I initially thought it was related to cellular data, but it seems like it's more localised. May be geographical, may be carrier-based. Companies may put these in place to avoid DDoS attacks.

Hard to investigate this further on your own, I'd strongly suggest sending an email to Quovo directly and ask them if they have any security measure in place that could prevent you from accessing their API while tethering.
