### ISSUE TITLE
Timeout config is not working

### ISSUE THREAD

**Issue by saiqulhaq** [lostisland/faraday#812]
## Basic Info

* Faraday Version: v0.12.0
* Ruby Version: 2.3.3

## Issue description
On my app, I use Rack-timeout gem to limit the request for 40 seconds, otherwise the app will return 500 HTTP error

this is the stacktrace:

```
13 File ".../2.3.3/lib/ruby/2.3.0/net/http.rb" line 1400 in block in request
14 File .../2.3.3/lib/ruby/2.3.0/net/http.rb" line 853 in start
15 File ".../2.3.3/lib/ruby/2.3.0/net/http.rb" line 1398 in request
16 File ".../lib/new_relic/agent/instrumentation/net.rb" line 36 in block in request_with_newrelic_trace
17 File.../lib/new_relic/agent.rb" line 495 in disable_all_tracing
18 File ".../lib/new_relic/agent/instrumentation/net.rb" line 35 in request_with_newrelic_trace
19 File ".../faraday-0.12.2/lib/faraday/adapter/net_http.rb" line 80 in perform_request
20 File ".../faraday-0.12.2/lib/faraday/adapter/net_http.rb" line 38 in block in call
21 File ".../faraday-0.12.2/lib/faraday/adapter/net_http.rb" line 85 in with_net_http_connection
22 File ".../faraday-0.12.2/lib/faraday/adapter/net_http.rb" line 33 in call
23 File ".../faraday-0.12.2/lib/faraday/request/url_encoded.rb" line 15 in call
24 File ".../faraday-0.12.2/lib/faraday/rack_builder.rb" line 141 in build_response
25 File ".../faraday-0.12.2/lib/faraday/connection.rb" line 386 in run_request
26 File "...faraday-0.12.2/lib/faraday/connection.rb" line 186 in post
27 File "...firebase_dynamic_link-1.0.3/lib/firebase_dynamic_link/client.rb" line 36 in shorten_link
```
if you see on the last line, it says **firebase_dynamic_link/client.rb**, [the actual code is](https://github.com/saiqulhaq/firebase_dynamic_link/blob/bce9e09e8ccab0dfef1374f1a4a0fbc1c0220936/lib/firebase_dynamic_link/client.rb#L36)

```
response = connection.post(nil, params.to_json)
```

`connection` is a `Faraday::Connection` instance

when I inspected the connection instance, this is the result:

```
#<FirebaseDynamicLink::Connection:0x00007fbdee33e718 
@client=#<Faraday::Connection:0x00007fbdee33e268 
@parallel_manager=nil, 
@headers={"Content-Type"=>"application/json", "User-Agent"=>"Faraday v0.12.2"}, 
@params={"key"=>"xxxx"}, 
@options=#<Faraday::RequestOptions timeout=2, open_timeout=2>, 
@ssl=#<Faraday::SSLOptions (empty)>, 
@default_parallel_manager=nil, 
@builder=#<Faraday::RackBuilder:0x00007fbdee33c828 @handlers=[Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp]>,
@url_prefix=#<URI::HTTPS https://xxx>, @proxy=nil>>
```

so it has `@options` variable with value `Faraday::RequestOptions timeout=2, open_timeout=2`

so it should be reject the request if more than two seconds, right?
but it seems infinite
I use Rollbar to report the exception, and the exception is `Rack::Timeout::RequestTimeoutException: Request ran for longer than 40000ms`

**Comment by iMacTia** [comment]
Hi @saiqulhaq, thanks for raising this.
Indeed, I would expect the request to respect the timeout config.
I've run this test locally against Faraday latest version (0.15.2) and it works as expected:

```ruby
conn = Faraday::Connection.new('https://httpstat.us')
conn.options.timeout = 1
conn.options.open_timeout = 1
conn.options
# => #<Faraday::RequestOptions timeout=1, open_timeout=1>
conn.get('/200?sleep=2000')
# => Faraday::TimeoutError (Net::ReadTimeout)
```

Could you please try this against your `Ruby`/`Faraday` combo and let me know if it works as expected?

**Comment by saiqulhaq** [comment]
Sorry I can't confirm this issue
the error is one-off bug
I just tried it, and it works

I will update this thread if I found what is the cause

**Comment by leoplct** [comment]
After 6 years, I still have this issue.

Loading development environment (Rails 7.1.3.2)
irb(main):001> conn = Faraday::Connection.new('https://httpstat.us')
irb(main):002> conn.options.timeout = 1
irb(main):003> conn.options.open_timeout = 1
irb(main):004> conn.options
irb(main):005> # => #<Faraday::RequestOptions timeout=1, open_timeout=1>
irb(main):006> conn.get('/200?sleep=2000')

irb(main):007> # => **Faraday::TimeoutError (Net::ReadTimeout)**
/Users/leonardo/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)
