### ISSUE TITLE
Is Faraday::Errors::ParsingError unused?

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#818]
## Basic Info

* Faraday Version: 1.0 HEAD
* Ruby Version: n/a

## Issue description

I searched for usages of ParsingErrors, and was unable to find any.

Is it still in use?

## Steps to reproduce

Search the codebase.

**Comment by iMacTia** [comment]
"usage" may have been moved to [`faraday_middleware`](https://github.com/lostisland/faraday_middleware/pull/144)

**Comment by olleolleolle** [comment]
Thanks, this question has been resolved. I added a reference to the Faraday middleware in the 1.0 YARD docs. Closing.
