### ISSUE TITLE
Incorrect encoding when receiving response with Faraday

### ISSUE THREAD

**Issue by noloman** [lostisland/faraday#822]
## Basic Info

* Faraday Version:
0.15.2
* Ruby Version:
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

## Issue description
I'm trying to make a GET request to a an API that returns a JSON with characters in UTF-8 such as `Temperatura m\xEDnima del aire` but it should be interpreted as `Temperatura máxima del aire`.

Not sure this is a bug tho, might be my bad or a misconfiguration.
Thanks in advance!

**Comment by iMacTia** [comment]
Hi @noloman, the response body encoding is usually defined by the server through a response header.

It would be really helpful if you could provide the following:

* Faraday connection initialise block (the one where you specify the API url and the middlewares)
* How you perform the request
* The full response you get back (headers and body possibly). You can get this through the console or you can plug in the `logger` middleware and enable body/headers output.

If the API is publicly available, it would also be great to get the URL and how to call it so I can try it directly.
