### ISSUE TITLE
Can we drop Ruby 2.2 (EOLd) from 1.0?

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#827]
## Basic Info

* Faraday Version: 1.0+
* Ruby Version: 2.2

## Issue description

Ruby 2.2 gets no further support. Perhaps we can cut it out of the Travis CI matrix in 1.0?

**Comment by iMacTia** [comment]
Makes sense to me!
I know the passage from 1.9 to 2.0 was quite hard, so we kept supporting 1.9 for quite a while.
However changing minor version is not that hard, so happy to officially support only 2.3+

**Comment by olleolleolle** [comment]
Fixed in #828
