### ISSUE TITLE
how to upload multiple files as form-data

### ISSUE THREAD

**Issue by chebyte** [lostisland/faraday#830]
hello there I need to upload using faraday the following example

````
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="listing"
{  
   "listing":{  
      "tickets":[  
         {  
            "row":"X",
            "seat":"201",
            "name":"file1"
         },

         {  
            "row":"X",
            "seat":"202",
            "name":"file2"
         }
      ]
   }
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file1"

------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="file2"

------WebKitFormBoundary7MA4YWxkTrZu0gW--

````

how can be transcribe to faraday way?

thanks

**Comment by ryanbyon** [comment]
I understand that this issue has been closed, but please help with the issue I am having which is close to this one. 

Below is what I need to upload
`-data-binary $'

------WebKitFormBoundaryInmulX6ait6ZMLdu\r\n
Content-Disposition: form-data; name="message"; filename="blob"\r\n
Content-Type: application/json
{
 "title":"title of the message to be sent",
 "body":"body of the message to be sent",
 "attachedFileName":null,
 "attachedFileName2":null,
 "attachedFileName3":null,
 "recipientIdList":[186554]
}
 ------WebKitFormBoundaryInmulX6ait6ZMLdu--\r\n' --compressed`

Please note content type that the server receives is `multipart/form-data`

my current code looks like below:
`
client = Faraday::Connection.new(url: BASE_URL) do |builder|
    builder.use :cookie_jar
    builder.use :multipart
    builder.use :url_encoded
    builder.adapter :net_http
end

message = {title: "title", body: "body of message", recipientIdList:[186554]}
payload = {message: JSON.dump(message}

response = @client.post(URL) do |request|
    request.headers['Content-Type'] = 'multipart/form-data'
    request.body = payload
end
`
However, the response I get from the server is `{"success"=>false, "errorCode"=>nil, "message"=>"Content type 'application/octet-stream' not supported", "data"=>nil}`

I tweaked the code little by little and tried again, and searched google for hours but could not find solution.
It would be greatly appreciated if someone can help me with this.
Thank you in advance :D
