### ISSUE TITLE
Receiving 403 error when hitting producthunt api using faraday api

### ISSUE THREAD

**Issue by kamesh27** [lostisland/faraday#831]
* Faraday Version: 0.15.3
* Ruby Version: 2.5.1 

When I am making a POST call to producthunt api, I do not see my request body in my terminal logs.  Every time I tried to hit producthunt api from faraday, I received a 403 forbidden error even though all the api_keys I used gave a perfectly good response when I used postman.

response: `#<Faraday::Response:0x00007fbdf3f501f0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n" @url=#<URI::HTTPS https://api.producthunt.com/v1/oauth/token> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Accept"=>"application/json", "Host"=>"api.producthost.com", "User-Agent"=>"Faraday v0.15.3", "Content-Type"=>"application/json"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00007fbdf3f501f0 ...> @response_headers={"server"=>"cloudflare", "date"=>"Wed, 24 Oct 2018 03:30:45 GMT", "content-type"=>"text/html", "content-length"=>"167", "connection"=>"close", "cf-ray"=>"46e95ddc49ec89a5-MAA"} @status=403 @reason_phrase="Forbidden">>`

request: 

```
conn = Faraday.new(url: BASE) do |faraday|
            faraday.response :logger
            faraday.request :json
            faraday.adapter Faraday.default_adapter
            faraday.headers['Accept'] = 'application/json'
            faraday.headers['Host'] = 'api.producthost.com'
        end
```

```
conn.post do |req|
            req.headers['Content-Type'] = 'application/json'
            req.body = '#{request_body}'
```

As I mentioned earlier the call is working fine when I am hitting with postman but it is failing when I am trying the same call using faraday not sure if I am doing something wrong.

**Comment by iMacTia** [comment]
Hi @kamesh27,

Can you please try moving the adapter at the very bottom of the connection build block (after the Accept and Host headers)?

Also, the logger middleware doesn’t log bodies by default (for security reasons), you can ask it to do so by passing `bodies: true` to it when setting it.

Let me know if this fixes it for you

**Comment by iMacTia** [comment]
Also, no need to set “Content-Type” header as the JSON middleware will do that for you. And the body should be a hash. Basically try performing the call like this:

`conn.post(‘/‘, body_as_hash)`

**Comment by kamesh27** [comment]
Hi @iMacTia,

Made changes as you suggested, 

but I am still getting the same response, please have a look at my changes to the code and see of I missed anything

```
def self.api
        conn = Faraday.new(url: BASE) do |faraday|
            faraday.response :logger
            faraday.request :json
            faraday.headers['Accept'] = 'application/json'
            faraday.headers['Host'] = 'api.producthost.com'
            faraday.adapter Faraday.default_adapter
        end

        conn.post(BASE, {:client_id => #client_id# ,
                        :client_secret => #client_secret#,
                        :grant_type => #grant_type#})
 end

**Comment by iMacTia** [comment]
@kamesh27 looks good now, but I think there's an issue with the url (`BASE`) and the path.
When you initialise the connection with `Faraday.new`, you just need to pass the `base_url` (your `BASE`, I guess). But when you call the endpoint with `conn.post`, you simply need to specify the path, not `BASE` again.
For example, if I want to call `http://api.producthost.com/api/v1/some_endpoint` then that would be:

```ruby
conn = Faraday.new(url: 'http://api.producthost.com/api/v1/') do |faraday|
  faraday.response :logger
  faraday.request :json
  faraday.headers['Accept'] = 'application/json'
  faraday.adapter Faraday.default_adapter
end

conn.post('some_endpoint', { :client_id => client_id ,
                  :client_secret => client_secret,
                  :grant_type => grant_type })
```

In my example, `BASE` would be `http://api.producthost.com/api/v1/` and the path would be `some_endpoint`.

**Comment by kamesh27** [comment]
@iMacTia 

Oh yes! I worked on that as well, still I am getting the same 403 in the response

Here it is:

`I, [2018-10-24T22:29:26.125371 #62898]  INFO -- request: POST https://api.producthunt.com/v1/oauth/token
D, [2018-10-24T22:29:26.126005 #62898] DEBUG -- request: Accept: "application/json"
Host: "api.producthost.com"
User-Agent: "Faraday v0.15.3"
I, [2018-10-24T22:29:26.437870 #62898]  INFO -- response: Status 403
D, [2018-10-24T22:29:26.438396 #62898] DEBUG -- response: server: "cloudflare"
date: "Wed, 24 Oct 2018 16:59:13 GMT"
content-type: "text/html"
content-length: "167"
connection: "close"
cf-ray: "46edfe2448bc8a49-BOM"
 => #<Faraday::Response:0x00007fbdf44489f0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n" @url=#<URI::HTTPS https://api.producthunt.com/v1/oauth/token> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Accept"=>"application/json", "Host"=>"api.producthost.com", "User-Agent"=>"Faraday v0.15.3", "Content-Type"=>"application/json"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00007fbdf44489f0 ...> @response_headers={"server"=>"cloudflare", "date"=>"Wed, 24 Oct 2018 16:59:13 GMT", "content-type"=>"text/html", "content-length"=>"167", "connection"=>"close", "cf-ray"=>"46edfe2448bc8a49-BOM"} @status=403 @reason_phrase="Forbidden">> `

Please have a look at it

**Comment by kamesh27** [comment]
Yeah, Please find the curl equivalent of the request.

```curl -X POST \
  https://api.producthunt.com/v1/oauth/token \
  -H 'accept: application/json' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'host: api.producthost.com' \
  -H 'postman-token: 16ed7642-71a1-c2f2-84cc-97cd717d8095' \
  -d '{
  "client_id": #client_id#,
  "client_secret": #client_secret#,
  "grant_type": #grant_type#
}	'

**Comment by iMacTia** [comment]
@kamesh27 please try the code below.
I've enabled the body logger (**so ensure you clean the output before posting here on GitHub to avoid exposing your client secret**).
I'm currently getting a 401 back because of the grant_type that clearly doesn't exist, but at least I'm not getting 403. I don't know where my code is different from yours, but it looks like is working fine for me.

```ruby
conn = Faraday.new(url: 'https://api.producthunt.com/v1/') do |faraday|
  faraday.response :logger, nil, bodies: true
  faraday.request :json
  faraday.headers['Accept'] = 'application/json'
  faraday.adapter Faraday.default_adapter
end

payload = {
    client_id: 'client_id',
    client_secret: 'secret',
    grant_type: 'type'
}

conn.post('oauth/token', payload)
```

**Comment by kamesh27** [comment]
Its working at last! though even I am not sure where our code is different

Thanks a lot for your help 👍 

closing the issue
