### ISSUE TITLE
Memory Issues with newest version of the faraday gem (0.15.2)

### ISSUE THREAD

**Issue by ryanclark2** [lostisland/faraday#837]
## Basic Info
* Faraday Version: 0.15.4
* Ruby Version: 2.5.3p105

## Issue description
Upgrading faraday from 0.12.2 causes memory issues on our workers. 
We use faraday to make requests to a 3rd party API, usually ~50k
per day. When we bump the gem version, memory usage goes up 
linearly until our worker(s) run out of memory. We've identified 
that a good number of the responses are 4XX, so not sure if 
that's related.

## Steps to reproduce
Making a large number of requests to a local rails app that returns
a 404 response using a faraday client will reproduce.

**Comment by iMacTia** [comment]
Hi @ryanclark2 and thanks for reporting.
Memory leak issues are indeed the most annoying ones to track.

Which adapter are you using? Have you tried using a different adapter to see if the memory leak disappears?

Since there have been plenty of changes between the two versions, it might be complicated to pinpoint the culprit, so if changing adapters doesn’t help, could you try upgrading one version at the time instead?

**Comment by ryanclark2** [comment]
Hey @iMacTia Thanks for the response. We're using the default adapter (Net::HTTP). I tries the Patron gem and adapter and it was actually better with 0.12.2, but I kept getting faraday connection errors with 15.4 just trying to talk to a local rails app. 

If it helps, here are our config settings: 
```
client = Faraday.new('http://www.example.test/') do |c| # local rails app
    c.request :json
    c.response :json, content_type: /\bjson$/
    c.request :basic_auth, "username", "password"
    c.adapter Faraday.default_adapter
```
I haven't tried with the versions between .12 and .15, but memory usage actually increases with both versions if we just create a client and make a lot of requests. 

I'm still kind of digging around, but any insights on your end would be great. Thanks!

**Comment by neos-guanliang** [comment]
FYI, we experienced similar memory leak after bumping from 0.15.3 to 0.15.4, and get back to normal memory consumption after rollback.

ruby version 2.5.1

**Comment by iMacTia** [comment]
That might help a lot! Are you saying you see no memory leaks with 0.15.3?

**Comment by ryanclark2** [comment]
We'll work through some of the intermediate versions to try to narrow down the scope of our issue. I am not sure if we have the same problem in our codebase with 0.15.3, but will update when we know more.

**Comment by neos-guanliang** [comment]
> That might help a lot! Are you saying you see no memory leaks with 0.15.3?

Yes we didn't have any memory issues in 0.15.3.

**Comment by iMacTia** [comment]
@neos-guanliang @ryanclark2 that's great news, at least we know which release introduced the leak.
@neos-guanliang are you also using the `Net::HTTP` adapter?

**Comment by iMacTia** [comment]
I had a look at the two versions [diff](https://github.com/lostisland/faraday/compare/v0.15.3...v0.15.4) and I can only see changes in the `Net::HTTP::Persistent` adapter

**Comment by ryanclark2** [comment]
Sorry to throw a wrench, but we definitely started experiencing this issue with an upgrade to 0.15.3. We tried 0.15.4 after making some changes to our codebase that we thought would help, but same issues. We're going to deploy 0.13.0 today and will update when we know if that's an issue or where it starts happening.

**Comment by iMacTia** [comment]
Thanks for the update, it actually makes sense since there are no changes from 0.15.3 to 0.15.4 that would explain that.
I know it’s painful but at the moment I don’t have the time to try every version and I believe you’re much better than me by in recognising the presence of the leak.

If you manage to identify the exact version bump that introduces the leak, I can then investigate exactly what is causing it.

Thanks!

**Comment by davidsuart** [comment]
@iMacTia - Regarding @neos-guanliang in  https://github.com/lostisland/faraday/issues/837#issuecomment-444813937 ... We bumped up more gems than just faraday in the change relating to that comment (For example, also `concurrent-ruby` and `rack`)... and in resolving the memory utilisation we did a full revert of all of those updated ... so our scenario is not a hygienic test case.

**Comment by technoweenie** [comment]
I whipped up a [quick script](https://gist.github.com/technoweenie/14736c54678b9ab615e7dc93db1ccabe) to make thousands of requests and print out GC information. It hits a sinatra endpoint that returns 404s roughly 80% of the time. I don't see any major differences when running this script against Faraday v0.12.2 or v0.15.3.

The script runs a loop 50 times that:

1. Makes 100 HTTP calls to the local Sinatra server
2. Calculate and print out GC info
3. Run GC

```
# Ruby 2.3.1, Faraday v0.15.3, net/http
total_allocated_objects: 3020157 (+54552, avg +60403)
total_freed_objects: 2925425 (+54579, avg +58509)
current: 94732, avg 94226

# Ruby 2.5.3, Faraday v0.15.3, net/http
total_allocated_objects: 2954545 (+55464, avg +59091)
total_freed_objects: 2885739 (+55449, avg +57715)
current: 68806, avg 68794

# Ruby 2.5.3, Faraday v0.15.3, Patron
total_allocated_objects: 1578520 (+28321, avg +31570)
total_freed_objects: 1528947 (+28269, avg +30579)
current: 49573, avg 49478
``` 

That means a complete run of the script generated 3M objects and freed 2.92M of them, with about 95k active objects in use. Definitely could be more efficient with object creation/destruction, but I'm not seeing a difference between different versions of Faraday. I'm also not seeing the active objects steadily climbing.

Here's a couple runs on Faraday v0.12.2 for comparison:

```
# Ruby 2.3.1, Faraday v0.12.2, net/http
total_allocated_objects: 2754312 (+49280, avg +55086)
total_freed_objects: 2664911 (+49268, avg +53298)
current: 89401, avg 89116

# Ruby 2.5.3, Faraday v0.12.2, net/http
total_allocated_objects: 2679296 (+49953, avg +53586)
total_freed_objects: 2610412 (+49960, avg +52208)
current: 68884, avg 68886

# Ruby 2.5.3, Faraday v0.12.2, Patron
total_allocated_objects: 1293278 (+22621, avg +25866)
total_freed_objects: 1245867 (+22657, avg +24917)
current: 47411, avg 47467
```

This isn't a perfect test though. @ryanclark2, based on your Faraday snippet above (https://github.com/lostisland/faraday/issues/837#issuecomment-444606963), what JSON request and response middleware are you using? Also, do you have an approximate size of the JSON responses? If you have a real JSON response, that'd be great, but I can try to find a sample with a similar size and structure.

I would appreciate anyone experiencing these issues to try my scripts, or even suggest better techniques for confirming this issue. I could inspect the heap dump my script generates using the approach detailed in [this blog post](https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby), but I don't think it's necessary based on the object counts in the results above.

FWIW: I did try running the tests without `GC.start`, and also against faraday v0.15.4. The numbers didn't differ much from the samples I posted.

**Comment by ryanclark2** [comment]
Hey @technoweenie, thanks for following up. I've actually moved on to a new company and haven't thought much more about this. If I recall, I just rewrote an endpoint in our rails app to return a 404 so I could test it locally. 

Since it doesn't look like anyone from my old company has followed up, probably also fine to close this for now.

**Comment by technoweenie** [comment]
@ryanclark2: ok thanks.

@neos-guanliang: you had a similar issue. Any thoughts on my results?
