### ISSUE TITLE
Faraday v1.0

### ISSUE THREAD

**Issue by technoweenie** [lostisland/faraday#903]
Faraday turns 10 this December, so I'd like to finally finish up Faraday v1.0. While there may have been a point in time that we could've refactored and cleaned up the cruft for v1.0, in reality Faraday has been "production ready" since around v0.8. It's very important that we don't inconvenience end users that are forced to upgrade Faraday due to something like an API client upgrade.

Some of the things I'd like tackle are:

* Drop-in upgrades full backwards compatibility and no runtime deprecation warnings.
* Expand the README documentation, fill in knowledge gaps
* Improve code quality (Rubocop, Code Climate, etc)
* Test harness that adapters like the `faraday-curb` gem can use for ensuring compatibility.

This will be tracked in the [v1.0 project](https://github.com/lostisland/faraday/projects/1). I'm open to any comments about this approach, or any issues that we should add to the project. Let me know!

**Comment by jasnow** [comment]
Only have 1 repo that uses faraday gem directly -- Upgraded it (no code change) and pushed it to GitHub. FYI: I have 10 gems in 13 repos that faraday as a sub-dependency.
Reference: https://github.com/lostisland/faraday/releases/tag/v1.0-rc1

**Comment by grosser** [comment]
please add a changelog entry even if it says "No change"

**Comment by jasnow** [comment]
What's the status on releasing?

**Comment by iMacTia** [comment]
I haven't been able to test rc1 in any project just yet, it would be great to hear feedback from someone who have been using it for a while with no issues

**Comment by 4geru** [comment]
Faraday v1.0 is released, so it seems to be already finished.

**Comment by olleolleolle** [comment]
Closing, done!
