### ISSUE TITLE
Faraday Website

### ISSUE THREAD

**Issue by technoweenie** [lostisland/faraday#949]
Should we throw up a Faraday website? What would be useful for users?

* [ ] Docs
  * [ ] Yard docs
  * [ ] Examples
  * [ ] (any rspec or code coverage stuff?)
* [ ] List related gems, adapters
* [ ] blog (docs, news, releases)
* [ ] Team page?

**Comment by iMacTia** [comment]
I've started working on a `gitHub-pages` website that uses `jekyll`.
On top of all the things you've listed above, we might have a mini-blog where we can write articles about HOW-TOs, new releases and other news

**Comment by olleolleolle** [comment]
I moved the Issue card about this to _In Progress_, to make the Roadmap match our efforts a little more.

**Comment by technoweenie** [comment]
Closing this, as we have something online now. Will unveil for the official v1.0 launch (or should we announce it now?)
