### ISSUE TITLE
URL with unicode query string nolonger work after 0.13.0

### ISSUE THREAD

**Issue by albb0920** [lostisland/faraday#960]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.5.0

## Issue description
Doing GET with Unicode characters like this used to work under 0.12.4.

```ruby
Faraday.get 'http://example.com/?a=測試'
```

After 0.13.0, this no longer works, an URI::InvalidURIError would be raised.
```
Traceback (most recent call last):
        10: from test_faraday.rb:12:in `<main>'
         9: from faraday-0.15.4/lib/faraday.rb:103:in `method_missing'
         8: from faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
         7: from faraday-0.15.4/lib/faraday/connection.rb:377:in `run_request'
         6: from faraday-0.15.4/lib/faraday/connection.rb:477:in `proxy_for_request'
         5: from faraday-0.15.4/lib/faraday/utils.rb:275:in `URI'
         4: from faraday-0.15.4/lib/faraday/utils.rb:275:in `call'
         3: from uri/common.rb:743:in `URI'
         2: from uri/common.rb:237:in `parse'
         1: from uri/rfc3986_parser.rb:73:in `parse'
uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "http://example.com/?a=\u6E2C\u8A66" (URI::InvalidURIError)
```

We found this recently as one of our dependency no longer locks to 0.12.x.

This might not be a bug, as unicode on url path never worked.
```ruby
Faraday.get 'http://example.com/測試'
```

I opened this issue to document this change of behavior.

There's two simple fix:

* repalce the uri parser
```ruby
Faraday::Utils.default_uri_parser = ->(uri) { Addressable::URI.parse(uri)
```

* Use hash parameters syntax
```ruby
Faraday.get 'http://example.com/', a: '測試'
```

## Steps to reproduce
If possible, please provide the steps to reproduce the issue.

```ruby
Faraday.get 'http://example.com/?a=測試'
```

**Comment by technoweenie** [comment]
Your analysis is correct: this seems like it's due to a change in how `URI.parse` works. Since `URI` is part of Ruby's standard lib, differing Faraday versions shouldn't affect this. Personally, I think setting the URL query params as a hash is the way to go.
