### ISSUE TITLE
.rvm/gems/ruby-head/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: tried to create Proc object without a block

### ISSUE THREAD

**Issue by localhostdotdev** [lostisland/faraday#961]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: ruby 2.7.0dev (2019-03-18 trunk 67296) [x86_64-darwin17]

## Issue description

I get many warnings like this:

```
.rvm/gems/ruby-head/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: tried to create Proc object without a block
```

## Steps to reproduce

- Using latest ruby-head (e.g. 2.7.0dev)
- I'm using faraday through discordrb but I think this might be for any faraday usage.

* Are you using the latest Faraday version? yes

**Comment by technoweenie** [comment]
This is a new change in Ruby v2.7.0, as shown in the [changelog](https://docs.ruby-lang.org/en/trunk/NEWS.html):

> Proc.new and proc with no block in a method called with a block is warned now.

Fixing it is a simple matter of using a `&block` argument in `Faraday::Options.memoized`.

Thanks for the issue!
