### ISSUE TITLE
Removing leading slash of Example

### ISSUE THREAD

**Issue by mom0tomo** [lostisland/faraday#976]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: ruby 2.6.1p33

## Issue description
I started using Faraday and got a problem that is same as #293 
I just used the example in README, and found there is a leading slash.

I hope other beginners do not make the same mistake again.

## Steps to reproduce
README.md
```diff
47 ```ruby
48 conn = Faraday.new(:url => 'http://www.example.com')
- 49 response = conn.get '/users'                 # GET http://www.example.com/users'
+ 49 response = conn.get 'users'                 # GET http://www.example.com/users'
50 ```
```

**Comment by iMacTia** [comment]
Hi @mom0tomo thanks for raising this again, I know it has been a painful discovery for many developers over the past and I agree with you this should be explained in a better way in the README.
However, I don't think just removing the leading slash from the example is going to help everyone, and may confuse others that need to use an absolute path for particular requests.

What do you think about changing the connection initial url into `http://www.example.com/api` instead and providing 2 example:
1. `response = conn.get 'users'` showing that this keeps the `/api` path provided to the connection
1. `response = conn.get '/users'` showing that this removes the `/api` path from the request

I think this way we can make this point clear for everyone

**Comment by mom0tomo** [comment]
Hi @iMacTia, I think it's a very good idea!
I would be glad if you would change README so, and everyone will surely be very happy.
