### ISSUE TITLE
CodeClimate test reporter complains: needs CC_TEST_REPORTER_ID for fork PRs

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday#984]
CodeClimate test reporter complains: needs CC_TEST_REPORTER_ID

```
#!/bin/bash -eo pipefail
./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter after-build [flags]

Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/circleci/project")

Global Flags:
  -d, --debug   run in debug mode

Exited with code 255
```

_Originally posted by @olleolleolle in https://github.com/lostisland/faraday/pull/983#issuecomment-495607748_

**Comment by iMacTia** [comment]
AH, I think I know why, this only happens for Fork PRs.
I've set that ENV variable in the CircleCI environment, but setting `Pass secrets to builds from forked pull requests` is currently turned OFF.
@olleolleolle how do you do in this cases? In TravisCI this was solved with secrets being encrypted and pushed with code, is there any equivalent in CircleCI?

**Comment by olleolleolle** [comment]
Interesting, we aren't then passing on CodeClimate stats in PR's. Makes it harder to use, right.

Q: is CC_TEST_REPORTER_ID a secret?

**Comment by iMacTia** [comment]
Well... yes and no.
It's not like you can do something destructive with it, but at the same time it allows you to push test coverage results on CodeClimate for Faraday.
It's technically a secret, anyway, we'll have the same issue for Rubygems deployment

**Comment by olleolleolle** [comment]
OK, then we could make the PR-without-credentials blithely skip that build step which uploads CC results.

**Comment by iMacTia** [comment]
We can, but we would lose the check on the code coverage drops

**Comment by iMacTia** [comment]
@olleolleolle I believe `Contexts` is what we want to use, I'll give it a try:
https://circleci.com/docs/2.0/contexts/

**Comment by olleolleolle** [comment]
Yep, that's the thing! Glad you figured it out!

**Comment by iMacTia** [comment]
Closing as we moved to GitHub Actions 👍
