### ISSUE TITLE
FYI: Warning after upgrading this gem to 2.7.0-preview1

### ISSUE THREAD

**Issue by jasnow** [lostisland/faraday#989]
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.7.0-preview1

## Issue description
Getting this warning after upgrading to Ruby 2.7.0-preview1:
```
faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the 
given block  using Proc.new is deprecated; use `&block` instead
```
and
```
faraday-0.15.4/lib/faraday/rack_builder.rb:55: warning: Capturing the 
given block using Proc.new is deprecated; use `&block` instead
```
## Steps to reproduce
Just upgrade a repo to Ruby 2.7.0-preview1 and then run "rake" command.
Here is a link to other repos working on this issue:
```
https://github.com/aws/aws-sdk-ruby/issues/2058
```

**Comment by iMacTia** [comment]
Hi @jasnow, thanks for raising this.
I can confirm this has already been fixed in `master` as of #962 👍

**Comment by jasnow** [comment]
I have 8 repos that use faraday gem (mostly as a sub-dependency).

**Comment by jasnow** [comment]
@iMacTia - Are we close to releasing a new version of this gem?

**Comment by iMacTia** [comment]
@jasnow quite close, although next version is going to be v1.0.
Don't be too scared about the major jump though, we did our best to make it backwards-compatible to minimise disruptions. I'm sorry I can't be more precise at the moment on the exact release date, but all the maintainers are working hard to make it happen.

**Comment by jasnow** [comment]
@iMacTia - Thanks for the update - I would normally just use the edge version on GitHub, but this gem is a sub-dependency for repos.

**Comment by jasnow** [comment]
FYI: https://github.com/lostisland/faraday/pull/993
