### ISSUE TITLE
Testing page for new documentation

### ISSUE THREAD

**Issue by Lewiscowles1986** [lostisland/faraday#997]
## Basic Info

* Faraday Version: master
* Ruby Version: 2.6.3

## Issue description

There is no documentation on testing with Faraday. Where I work Ruby on Rails was introduced because it's cool. Little thought was given to testing red-cases. I'd like to contribute some documentation to help others

## Steps to reproduce

* visit website.
* Click `usage`
* follow footer next links until you can proceed no further right (https://lostisland.github.io/faraday/usage/streaming)
* notice no testing in usage :scream_cat:

**Comment by technoweenie** [comment]
Thank you for bringing this up. In response, I have posted a PR to include live test/unit and rspec examples of using the Faraday Test adapter: #1000. This is the recommended way to test Faraday, instead of external test double libraries (rspec, mocha, webmock, etc).

**Comment by Lewiscowles1986** [comment]
I noticed at no point is it testing things such as timeouts, connection errors, etc. Is the subject frowned upon, or just the way PR #998 uses.

I suppose I don't get the syntax

**Comment by iMacTia** [comment]
Delivered with #1000
